Energinet-DataHub/opengeh-wholesale

README.md
=> Fix domain name reference

build/infrastructure/main/kv-shared-access-policies.tf
=> add function to kv access policy

build/infrastructure/main/kv-shared-resources.tf, build/infrastructure/main/mssql-database.tf, source/dotnet/DatabaseMigration/DatabaseMigration.csproj, source/dotnet/DatabaseMigration/Program.cs, source/dotnet/DatabaseMigration/Scripts/202206131400_Create_Batch_Table.sql, source/dotnet/DatabaseMigration/Upgrader.cs, source/dotnet/Wholesale.sln, source/dotnet/Wholesale.sln.DotSettings
Provision a SQL database and add batch model tables.
A batch model initially only holds a state and a list of grid area IDs, which is needed for [the current feature](https://github.com/Energinet-DataHub/geh-aggregations/issues/748).
* #33
=> Add batch SQL table

source/dotnet/Application/Application.csproj, source/dotnet/Application/BatchApplicationService.cs, source/dotnet/Application/IBatchApplicationService.cs, source/dotnet/Domain/BatchAggregate/Batch.cs, source/dotnet/Domain/BatchAggregate/IBatchRepository.cs, source/dotnet/Domain/Domain.csproj, source/dotnet/Infrastructure/BatchRepository.cs, source/dotnet/Infrastructure/Infrastructure.csproj, source/dotnet/IntegrationTests/IntegrationTests/WebApi/V1/BatchControllerTests.cs, source/dotnet/WebApi/Controllers/V1/BatchController.cs, source/dotnet/WebApi/Startup.cs, source/dotnet/WebApi/WebApi.csproj, source/dotnet/Wholesale.sln
Outlines code and project structure for creating a batch.
* #33
=> Add code for creating a batch - except persisting

build/infrastructure/main/app-wholesale-api.tf, build/infrastructure/main/kv-shared-resources.tf, build/infrastructure/main/locals.tf
=> Add wholesale-api IaC

build/infrastructure/main/app-wholesale-api.tf
=> Publish base url of wholesale-api

source/dotnet/IntegrationEventListener/Program.cs
This PR will add the following middlewares to the `IntegrationEventListener` in the wholesale domain:
- [FunctionTelemetry ](https://github.com/Energinet-DataHub/geh-core/blob/main/source/App/documents/functionTelemetryScopeMiddleware.md)
- [CorrelationId ](https://github.com/Energinet-DataHub/geh-core/blob/main/source/App/documents/correlationIdMiddleware.md)
* #784
=> Feat: Dependency/CorrelationContext middleware

source/dotnet/Application/Batches/BatchApplicationService.cs, source/dotnet/Application/Batches/BatchRequestDto.cs, source/dotnet/Application/Batches/IBatchApplicationService.cs, source/dotnet/DatabaseMigration/DatabaseMigration.csproj, source/dotnet/DatabaseMigration/Scripts/202206161400_Create_Batch_Table.sql, source/dotnet/Domain/BatchAggregate/Batch.cs, source/dotnet/Domain/GridAreaAggregate/GridAreaCode.cs, source/dotnet/Infrastructure/Persistence/Batches/BatchEntityConfiguration.cs, source/dotnet/IntegrationTests/Infrastructure/BatchRepositoryTests.cs, source/dotnet/IntegrationTests/WebApi/V1/BatchControllerTests.cs, source/dotnet/Tests/Domain/BatchAggregate/BatchTests.cs, source/dotnet/Tests/Domain/GridAreaAggregate/GridAreaCodeTests.cs, source/dotnet/WebApi/Configuration/ServiceCollectionExtensions.cs, source/dotnet/WebApi/Controllers/V1/BatchController.cs
The grid area code is unique as well as the id. Currently, we don't know the ids in the UI, so for now it's simpler to stick with the codes.
* #33
=> Use grid area code instead of id

build/infrastructure/main/outputs.tf
This is needed in order to update repo https://github.com/Energinet-DataHub/dh3-environments to run database migrations.
* #33
=> Output SQL connection string from terraform

.github/actions/dotnet-prepare-outputs/action.yml
=> Deploy artifacts of web API and db migration

source/dotnet/DatabaseMigration/Program.cs
=> Fix development database connection string

source/dotnet/WebApi/Startup.cs
=> Add web API authorization

build/infrastructure/main/kv-shared-access-policies.tf
=> fix: Add keyvault access policy for process manager

.github/actions/dotnet-prepare-outputs/action.yml
=> feat: Add process-manager artifacts

build/infrastructure/main/func-processmanager.tf
=> refac: Minor terraform improvement

build/infrastructure/main/func-processmanager.tf
=> Fix db connection string

source/dotnet/Infrastructure.Core/Infrastructure.Core.csproj, source/dotnet/Infrastructure/Infrastructure.csproj, source/dotnet/Infrastructure/Persistence/Batches/BatchEntityConfiguration.cs, source/dotnet/IntegrationEventListener/IntegrationEventListener.csproj, source/dotnet/IntegrationTests.Core/Fixtures/Database/WholesaleDatabaseManager.cs, source/dotnet/IntegrationTests.Core/IntegrationTests.Core.csproj, source/dotnet/IntegrationTests/IntegrationTests.csproj, source/dotnet/ProcessManager/ProcessManager.csproj, source/dotnet/ProcessManager/Program.cs, source/dotnet/Sender/Sender.csproj, source/dotnet/Tests/Tests.csproj, source/dotnet/WebApi/Configuration/ServiceCollectionExtensions.cs, source/dotnet/WebApi/WebApi.csproj
~~Perhaps this could solve the problem about process manager able to run in u-001.~~ (no it doesn't)
* #33
=> Upgrade all NuGet packages

.github/workflows/cd.yml
Update CD pipeline to latest .NET version and correct workflow version.
https://app.zenhub.com/workspaces/mighty-ducks---the-outlaws-6193fe815d79fc0011e741b1/issues/energinet-datahub/the-outlaws/367
=> Fix CD pipeline

build/infrastructure/main/func-sender.tf, build/infrastructure/main/kv-shared-resources-messagehub.tf, source/dotnet/Infrastructure.Core/EnvironmentVariableExtensions.cs, source/dotnet/Infrastructure/ServiceBus/ServiceBusMessageFactory.cs, source/dotnet/IntegrationTests.Core/Fixtures/FunctionApp/SenderFunctionAppFixture.cs, source/dotnet/IntegrationTests.Core/IntegrationTests.Core.csproj, source/dotnet/IntegrationTests/IntegrationTests.csproj, source/dotnet/IntegrationTests/Sender/DataAvailableSenderEndpointTests.cs, source/dotnet/IntegrationTests/Sender/ProcessRepositoryTests.cs, source/dotnet/ProcessManager/Endpoints/StartPendingBatches.cs, source/dotnet/Sender/Configuration/EnvironmentSettingNames.cs, source/dotnet/Sender/Endpoints/PeekEndpoint.cs, source/dotnet/Sender/IDocumentSender.cs, source/dotnet/Sender/Infrastructure/Persistence/Processes/ProcessRepository.cs, source/dotnet/Sender/Infrastructure/Services/DataAvailableNotificationFactory.cs, source/dotnet/Sender/Infrastructure/Services/DocumentFactory.cs, source/dotnet/Sender/Infrastructure/Services/DocumentSender.cs, source/dotnet/Sender/Infrastructure/Services/IDocumentFactory.cs, source/dotnet/Sender/Program.cs, source/dotnet/Sender/Sender.csproj
=> feat: Add peek of RSM-014

source/dotnet/Sender/Endpoints/PeekEndpoint.cs
=> fix: Update PeekEndpoint.cs

source/dotnet/IntegrationTests/IntegrationTests.csproj, source/dotnet/Sender/Sender.csproj
=> fix: messagehub core update

source/dotnet/Sender/Infrastructure/Services/DocumentFactory.cs, source/dotnet/Tests/Sender/Infrastructure/Services/DocumentFactoryTests.cs, source/dotnet/Tests/Tests.csproj
=> fix: Fix quotation error in RSM-014 template

source/dotnet/IntegrationEventListener/MeteringPoints/MeteringPointConnectedDto.cs, source/dotnet/IntegrationEventListener/MeteringPoints/MeteringPointConnectedDtoFactory.cs, source/dotnet/IntegrationEventListener/MeteringPoints/MeteringPointCreatedDto.cs, source/dotnet/IntegrationEventListener/MeteringPoints/MeteringPointCreatedDtoFactory.cs, source/dotnet/Tests/IntegrationEventListener/MeteringPointConnectedDtoFactoryTests.cs, source/dotnet/Tests/IntegrationEventListener/MeteringPointCreatedDtoFactoryTests.cs
This PR will add the `MeteringPointId` to the DTOs which represents the creation and the connected event.
* #91
=> feat: MeteringpointId on MP events

source/dotnet/Sender/Infrastructure/Services/DocumentFactory.cs, source/dotnet/Sender/Infrastructure/Services/DocumentIdGenerator.cs, source/dotnet/Sender/Infrastructure/Services/IDocumentIdGenerator.cs, source/dotnet/Sender/Program.cs, source/dotnet/Tests/Sender/Infrastructure/Services/DocumentFactoryTests.cs
=> Make CIM document ID unique

README.md
=> Fix path to databricks readme

.github/workflows/cd.yml, .github/workflows/ci.yml
Reenable integration tests in builds
https://app.zenhub.com/workspaces/mighty-ducks---the-outlaws-6193fe815d79fc0011e741b1/issues/energinet-datahub/the-outlaws/421
=> Reenable integration tests in builds

source/databricks/package/schemas/eventhub_integration_events_schema.py
=> 32 added metering point id

build/infrastructure/main/dbwj-calculator.tf, build/infrastructure/main/dbwj-integrationeventspersister.tf
Python wheel from geh-timeseries and opengeh-wholesale shared name and location in Databricks file system effectively causing overwrite on each pull-request.
* #32
=> Fix wheel collision

source/databricks/package/calculator.py, source/databricks/package/calculator_job.py, source/databricks/tests/integration/calculator/test_calculator.py
=> Fix broken calculator

.github/ISSUE_TEMPLATE/bug.md
=> Bug template for team mandalorian

.gitattributes
This PR should avoid the problem where lots of files shows up as changes in Git when working in mixed environment (.NET on Windows and pyspark on Linux in Docker).
In order to update current working files make sure you don't have any pending changes and execute the following commands:
```
git rm --cached -r .
git reset --hard
```
=> feat: Use Windows line endings

source/databricks/package/balance_fixing_total_production.py
Remove todos about optimization hints that are related to Delta tables, which are not used.
* #32
=> refac: Remove Delta table orienteret todos

.github/workflows/cd.yml, .github/workflows/ci.yml
Use v8 for reusable workflows/actions
https://app.zenhub.com/workspaces/mighty-ducks---the-outlaws-6193fe815d79fc0011e741b1/issues/energinet-datahub/the-outlaws/479
=> Use v8 for reusable workflows/actions

source/dotnet/Infrastructure.Core/Infrastructure.Core.csproj, source/dotnet/Infrastructure/Infrastructure.csproj, source/dotnet/IntegrationEventListener/IntegrationEventListener.csproj, source/dotnet/IntegrationTests/IntegrationEventListener/MarketParticipantChangedListenerEndpointTests.cs, source/dotnet/IntegrationTests/IntegrationTests.csproj, source/dotnet/ProcessManager/ProcessManager.csproj, source/dotnet/Sender/Sender.csproj, source/dotnet/Tests/Tests.csproj, source/dotnet/WebApi/WebApi.csproj
=> Update NuGet packages

source/databricks/package/balance_fixing_total_production.py, source/databricks/tests/integration/calculator/balance_fixing_total_production/test_get_grid_areas_df.py
=> Test that there is only one row per grid area when there are duplicate events

source/databricks/package/integration_events_persister.py
We were missing the append mode when writing the integration events down.
* #0000
=> integration_events_persister mode append

source/notebooks/Inspect basis data.py
=> feat: Add notebook to inspect basis data

source/dotnet/Tests/Sender/Infrastructure/Services/DocumentFactoryTests.cs, source/dotnet/Tests/Tests.csproj
=> RSM-014 schema validation test

source/contracts/enums/timeseries-quality.json, source/databricks/package/balance_fixing_total_production.py, source/databricks/package/codelists/time_series_quality.py, source/databricks/tests/integration/calculator/balance_fixing_total_production/test_get_result_df.py
Update time series quality contract according to [this fix](https://github.com/Energinet-DataHub/geh-timeseries/pull/540) in `geh-timeseries`.
* #188
=> fix: Update time series quality contract

source/databricks/tests/integration/calculator/test_calculator_job.py
This PR will refactor the one integration test of the calculator into multiple smaller tests
=> refac: test_calculator_job.py

source/dotnet/WebApi/Properties/launchSettings.json, source/dotnet/WebApi/Startup.cs
This PR disable JWT token security when running in a development environment  and adds local connection string to launch settings
* #0000
=> feat: Make local testing easy

build/infrastructure/main/dbwj-alert-integrationeventspersister.tf
Implemeted alert when integration events persister streaming job fails
#185
=> Implemented alert for integration events persister streaming job

build/infrastructure/main/func-integrationeventlistener.tf, build/infrastructure/main/sbs-integration-events.tf
=> fix: Topic and subscription fixes

source/contracts/events/metering-point-created.json, source/databricks/package/balance_fixing_total_production.py, source/databricks/package/calculator_job.py, source/databricks/package/schemas/metering_point_created_event_schema.py, source/databricks/package/schemas/metering_point_generic_event_schema.py, source/databricks/tests/integration/calculator/balance_fixing_total_production/test_get_master_basis_data.py, source/databricks/tests/integration/calculator/balance_fixing_total_production/test_get_metering_points_df.py, source/databricks/tests/integration/calculator/test_calculator_job.py, source/dotnet/IntegrationEventListener/MeteringPoints/MeteringPointCreatedDto.cs, source/dotnet/IntegrationEventListener/MeteringPoints/MeteringPointCreatedDtoFactory.cs, source/dotnet/Tests/IntegrationEventListener/MeteringPoints/MeteringPointCreatedDtoFactoryTests.cs
This PR will include
- Masterdata will be written when a calculation is requested.
- `FromGridAreaCode` and `ToGridAreaCode` is included from the `MeteringpointCreatedEvent`
* #0000
=> feat: master basis data

source/databricks/package/balance_fixing_total_production.py, source/databricks/tests/integration/calculator/balance_fixing_total_production/test_get_master_basis_data.py, source/databricks/tests/integration/calculator/test_calculator_job.py
=> refac: removed id from different gridarea types

source/databricks/package/balance_fixing_total_production.py, source/databricks/tests/integration/calculator/balance_fixing_total_production/test_get_master_basis_data.py, source/databricks/tests/integration/calculator/test_calculator_job.py
=> feat: EnergySupplierId to master basis data

source/dotnet/Services/DatabaseMigration/DatabaseMigration.csproj
This PR replaces the obsolete NuGet package `dbup` with the recommended alternative `dbup-sqlserver`.
It is the hope that this will solve the transient errors with database login failures in integration tests in the CI.
* #17
=> fix: Try fix db login in integration test

.github/workflows/packages-publish.yml, .gitignore, source/dotnet/Packages/Client.Tests/Client.Tests.csproj, source/dotnet/Packages/Client/Client.csproj, source/dotnet/Packages/Packages.sln, source/dotnet/Packages/documents/documentation.md, source/dotnet/Packages/documents/release-notes/release-notes.md
=> feat: Publish wholesale client NuGet package

source/dotnet/Services/Application/Application.csproj, source/dotnet/Services/Application/Batches/BatchExecutionStateHandler.cs, source/dotnet/Services/Tests/Application/BatchExecutionStateHandlerTests.cs
=> Skip run if it doesn't exist in Databricks

.github/workflows/cd.yml
Try small adjustments before rolling out to all domains.
https://app.zenhub.com/workspaces/mighty-ducks---the-outlaws-6193fe815d79fc0011e741b1/issues/energinet-datahub/the-outlaws/617
=> Small adjustments

.github/workflows/cd.yml
Update CD to skip dispatch if all are skipped.
https://app.zenhub.com/workspaces/mighty-ducks---the-outlaws-6193fe815d79fc0011e741b1/issues/energinet-datahub/the-outlaws/617
=> Skip if all are skipped

.github/workflows/cd.yml, .github/workflows/detect-changes.yml
Fix bug where some files are not part of path filters.
=> Update path filters

build/infrastructure/main/kv-shared-resources.tf, source/dotnet/Services/IntegrationTests/Fixture/FunctionApp/ProcessManagerFunctionAppFixture.cs, source/dotnet/Services/IntegrationTests/Hosts/ProcessManagerIntegrationTestHost.cs, source/dotnet/Services/IntegrationTests/ProcessManager/SubmitCreatedBatchesEndpointTests.cs
=> feat: Improve and fix tests

.github/workflows/cd.yml
Use DH3 implemented action to find PR number.
=> Use our own action to find PR

build/infrastructure/main/func-processmanager.tf, build/infrastructure/main/func-sender.tf, build/infrastructure/main/sbt-domain-events.tf
=> fix: Fix terraform errors

source/dotnet/Services/Infrastructure/BasisData/BatchFileManager.cs, source/dotnet/Services/IntegrationTests/Hosts/SenderIntegrationTestHost.cs, source/dotnet/Services/IntegrationTests/Sender/PeekEndpointTests.cs, source/dotnet/Services/ProcessManager/Program.cs, source/dotnet/Services/Sender/Program.cs, source/dotnet/Services/Tests/Hosts/ProcessManagerHostTests.cs, source/dotnet/Services/Tests/Infrastructure/BasisData/BatchFileManagerTests.cs
https://portal.azure.com/#view/AppInsightsExtension/DetailsV2Blade/ComponentId~/%7B%22SubscriptionId%22%3A%223c13ff3d-aad8-4ee8-94c6-8a938ace9699%22%2C%22ResourceGroup%22%3A%22rg-DataHub-SharedResouces-U-001%22%2C%22Name%22%3A%22appi-shared-sharedres-u-001%22%2C%22LinkedApplicationType%22%3A0%2C%22ResourceId%22%3A%22%252Fsubscriptions%252F3c13ff3d-aad8-4ee8-94c6-8a938ace9699%252FresourceGroups%252Frg-DataHub-SharedResouces-U-001%252Fproviders%252FMicrosoft.Insights%252Fcomponents%252Fappi-shared-sharedres-u-001%22%2C%22ResourceType%22%3A%22microsoft.insights%252Fcomponents%22%2C%22IsAzureFirst%22%3Afalse%7D/DataModel~/%7B%22eventId%22%3A%2229051c52-4dec-11ed-9464-000d3aac8edc%22%2C%22timestamp%22%3A%222022-10-17T07%3A19%3A54.050Z%22%2C%22cacheId%22%3A%2206061ce8-3f98-48b5-812f-4dfe06d5b0fa …
=> bug: fix sender ioc error

source/dotnet/Contracts/BatchDtoV1.cs, source/dotnet/Contracts/BatchDtoV2.cs, source/dotnet/Packages/Client/Client.csproj, source/dotnet/Packages/Client/IWholesaleClient.cs, source/dotnet/Packages/Client/WholesaleClient.cs, source/dotnet/Packages/documents/release-notes/release-notes.md, source/dotnet/Services/Application/Application.csproj, source/dotnet/Services/Application/Batches/BatchDto.cs, source/dotnet/Services/Application/Batches/BatchDtoMapper.cs, source/dotnet/Services/IntegrationTests/WebApi/BatchControllerTests.cs, source/dotnet/Services/Tests/Application/BatchDtoMapperTests.cs, source/dotnet/Services/WebApi/Configuration/ServiceCollectionExtensions.cs, source/dotnet/Services/WebApi/Controllers/V1/BatchDtoV1Mapper.cs, source/dotnet/Services/WebApi/Controllers/V1/IBatchDtoV1Mapper.cs, source/dotnet/Services/WebApi/Controllers/V2/BatchController.cs, source/dotnet/Services/WebApi/Controllers/V2/BatchDtoV2Mapper.cs, source/dotnet/Services/WebApi/Controllers/V2/IBatchDtoV2Mapper.cs, source/dotnet/Services/WebApi/WebApi.csproj, wordlist.txt
=> refac: Update batchDto to use batchId instead on runId

source/dotnet/Services/Test.Core/ObjectExtensions.cs, source/dotnet/Services/Test.Core/ReflectionExtensions.cs, source/dotnet/Services/Test.Core/Test.Core.csproj, source/dotnet/Services/Tests/Domain/BatchAggregate/BatchBuilder.cs, source/dotnet/Services/Tests/Tests.csproj, source/dotnet/Services/Wholesale.sln
Extract test utils shared by both unit and integration tests (different projects).
* #17
=> refac: Segregate test core project

source/dotnet/Services/IntegrationTests/Hosts/WebApiIntegrationTestHost.cs, source/dotnet/Services/IntegrationTests/WebApi/WebApiTests.cs, source/dotnet/Services/WebApi/Configuration/ServiceCollectionExtensions.cs, source/dotnet/Services/WebApi/Program.cs, source/dotnet/Services/WebApi/Startup.cs
Small refactor of the startup and a new test host for the WebApi to help test resolving the controllers
* #17
=> test: WebApiTestHost and IOC controller test

source/dotnet/Services/IntegrationTests/Hosts/IntegrationEventListenerIntegrationTestHost.cs, source/dotnet/Services/IntegrationTests/Hosts/ProcessManagerIntegrationTestHost.cs, source/dotnet/Services/IntegrationTests/IntegrationEventListener/MarketParticipantChangedListenerEndpointTests.cs, source/dotnet/Services/IntegrationTests/IntegrationEventListener/MeteringPointConnectedListenerEndpointTests.cs, source/dotnet/Services/IntegrationTests/IntegrationEventListener/MeteringPointCreatedListenerEndpointTests.cs, source/dotnet/Services/IntegrationTests/Sender/PeekEndpointTests.cs
This PR will do a minor clean up of the hosts created in my last few PRs.
* #17
=> refac: cleanup of hosts and ioc tests

source/dotnet/Services/IntegrationTests/Hosts/ProcessManagerIntegrationTestHost.cs, source/dotnet/Services/IntegrationTests/ProcessManager/BatchApplicationServiceTests.cs, source/dotnet/Services/IntegrationTests/ProcessManager/PublishProcessCompletedEventsEndpointTests.cs, source/dotnet/Services/IntegrationTests/ProcessManager/SubmitCreatedBatchesEndpointTests.cs, source/dotnet/Services/IntegrationTests/ProcessManager/UpdateBatchExecutionStateEndpointTests.cs, source/dotnet/Services/IntegrationTests/ProcessManager/ZipBasisEndpointTests.cs, source/dotnet/Services/IntegrationTests/TestCommon/ProcessManager/SubmitCreatedBatchesEndpointTests.cs, source/dotnet/Services/ProcessManager/Endpoints/PublishProcessCompletedEventsEndpoint.cs, source/dotnet/Services/ProcessManager/Endpoints/SubmitCreatedBatchesEndpoint.cs, source/dotnet/Services/ProcessManager/Endpoints/UpdateBatchExecutionStateEndpoint.cs, source/dotnet/Services/ProcessManager/Endpoints/ZipBasisDataEndpoint.cs
=> refac processmanager endpoint names and ioc test them

.docker/Dockerfile
=> install xdist

.github/CODEOWNERS
=> build: Update CODEOWNERS

source/databricks/tests/integration/calculator/test_calculator_job.py
=> tests: basisdata path tests

.docker/Dockerfile
=> moving downloading of dependecies to Docker image

source/dotnet/Services/Tests/Infrastructure/BasisData/BatchFileManagerTests.cs
=> tests: BatchFileManager paths

source/dotnet/Services/Infrastructure/BasisData/BatchFileManager.cs, source/dotnet/Services/IntegrationTests/ProcessManager/BasisDataApplicationServiceTests.cs, source/dotnet/Services/IntegrationTests/TestCommon/ProcessManager/SubmitCreatedBatchesEndpointTests.cs
=> refac: Remove obsolete todos

build/infrastructure/main/app-wholesale-api.tf, source/dotnet/Services/WebApi/Configuration/ServiceCollectionExtensions.cs, source/dotnet/Services/WebApi/EnvironmentSettingNames.cs
=> DataLakeFileSystemClient

source/dotnet/Services/Wholesale.sln
Fix these broken links:
* #0000
=> fix: Fix broken solution file links

source/dotnet/Services/IntegrationTests/CompositionRootTests.cs, source/dotnet/Services/IntegrationTests/Hosts/ProcessManagerIntegrationTestHost.cs, source/dotnet/Services/IntegrationTests/Hosts/WebApiIntegrationTestHost.cs, source/dotnet/Services/IntegrationTests/ProcessManager/BasisDataApplicationServiceTests.cs, source/dotnet/Services/IntegrationTests/ProcessManager/BatchApplicationServiceTests.cs, source/dotnet/Services/IntegrationTests/TestCommon/Fixture/ProcessManagerFixtureConfiguration.cs, source/dotnet/Services/IntegrationTests/TestCommon/Fixture/WebApi/WholesaleWebApiFixture.cs, source/dotnet/Services/IntegrationTests/TestCommon/WebApi/BatchControllerTests.cs
=> fix: testCommon / processManager test

.docker/Dockerfile
=> added databricks-cli

source/databricks/package/datamigration/uncommitted_migrations_count.py
=> feat: Add migration count python entrypoint

source/databricks/package/datamigration/uncommitted_migrations_count.py
=> fix: flake8 fix

.github/CODEOWNERS
Remove @Mech0z as code owner as requested by himself.
=> update: Remove @Mech0z as code owner

source/notebooks/lki-old-stuff/CSV to Delta Table.py, source/notebooks/lki-old-stuff/CosmosDBdemo.py, source/notebooks/lki-old-stuff/DeltaAndCosmosDataframeJoinTest.py, source/notebooks/lki-old-stuff/Demo 14-03-2022.py, source/notebooks/lki-old-stuff/Event playback.py, source/notebooks/lki-old-stuff/EventHub save periods to delta table.py, source/notebooks/lki-old-stuff/Eventhub streaming test.py, source/notebooks/lki-old-stuff/Events delta table.py, source/notebooks/lki-old-stuff/Hackathon Autoloader Test.py, source/notebooks/lki-old-stuff/LKI TEST.py, source/notebooks/lki-old-stuff/README.md, source/notebooks/lki-old-stuff/Read masterdata.py, source/notebooks/lki-old-stuff/Read timeseries data.py, source/notebooks/lki-old-stuff/StreamSource 1.py, source/notebooks/lki-old-stuff/Test events as json.py
Add old Databricks notebooks from former team member. The notebooks are related to the obsolete `geh-aggregations` GitHub repo.
=> Add former team members Databricks notebooks

.docker/Dockerfile
=> feat: Add `virtualenv` and `build` pip packages

source/databricks/package/balance_fixing_total_production.py, source/databricks/tests/integration/calculator/balance_fixing_total_production/test_get_master_basis_data.py
=> feat: EnergySupplierId in Basisdata

.docker/Dockerfile
=> Install azure-identity package in Docker image

source/databricks/package/calculator_job.py, source/databricks/package/datamigration/jobs.py, source/databricks/package/datamigration/uncommitted_migrations_count.py, source/databricks/tests/datamigration/test_uncommitted_migrations_count.py, source/databricks/tests/entry_points/test_entry_points.py, source/databricks/tests/integration/calculator/test_calculator_job.py
=> Unit test _get_valid_args_or_throw() directly instead of via subprocess

source/databricks/package/datamigration/data_lake_file_manager.py, source/databricks/package/datamigration/uncommitted_migrations_count.py, source/databricks/tests/datamigration/test_data_lake_file_manager.py, source/databricks/tests/datamigration/test_uncommitted_migrations_count.py
=> Centralize data lake file handling (Python)

source/databricks/package/datamigration/uncommitted_migrations_count.py, source/databricks/tests/entry_points/test_entry_points.py
=> test: Test remaining entry points

source/databricks/package/datamigration/data_lake_file_manager.py, source/databricks/package/datamigration/lock_storage.py, source/databricks/package/datamigration/uncommitted_migrations_count.py, source/databricks/tests/datamigration/test_data_lake_file_manager.py, source/databricks/tests/datamigration/test_lock_storage.py, source/databricks/tests/datamigration/test_uncommitted_migrations_count.py, source/databricks/tests/integration/calculator/test_calculator_job.py
=> created lock and unlock functions

source/databricks/package/balance_fixing_total_production.py, source/databricks/tests/integration/calculator/balance_fixing_total_production/test_get_metering_points_df.py
=> fix: refactor connectionstate windowing

source/databricks/package/datamigration/committed_migrations.py, source/databricks/package/datamigration/data_lake_file_manager.py, source/databricks/tests/datamigration/test_committed_migrations.py
=> create migration state file if it doesn't exist in the container

source/databricks/package/calculator_job.py, source/databricks/tests/integration/calculator/test_calculator_job.py
=> add storage container path as a required argument to start_calculator

source/databricks/package/calculator_job.py, source/databricks/tests/integration/calculator/test_calculator_job.py
The argument is required, this PR will update the parsing of the argument to reflect this.
* #508
=> refac: update log-level to be required for calculatorjob

source/databricks/package/calculator_job.py, source/databricks/package/datamigration/lock_storage.py, source/databricks/package/datamigration/migration.py, source/databricks/package/datamigration/uncommitted_migrations.py, source/databricks/package/infrastructure.py, source/databricks/package/integration_events_persister_streaming.py, source/databricks/tests/datamigration/test_lock_storage.py, source/databricks/tests/datamigration/test_migration.py, source/databricks/tests/datamigration/test_uncommitted_migrations.py, source/databricks/tests/integration/calculator/test_calculator_job.py
=> fix: islocked method needs arguments

source/databricks/package/calculator_job.py, source/databricks/package/integration_events_persister_streaming.py, source/databricks/tests/integration/calculator/test_calculator_job.py, source/databricks/tests/integration/integration_events_persister/test_integration_events_persister.py
=> fix: temporarily remove islocked call

source/databricks/package/calculator_job.py, source/databricks/package/integration_events_persister_streaming.py, source/databricks/tests/integration/calculator/test_calculator_job.py, source/databricks/tests/integration/integration_events_persister/test_integration_events_persister.py
This reverts commit 82dc65cd7efa8073c37d7df1ac302bb8cecc7d82.
* #508
=> Revert "fix: temporarily remove islocked call (#521)"

source/databricks/package/datamigration/committed_migrations.py, source/databricks/tests/datamigration/test_committed_migrations.py
=> fix: use correct method name - 'file_exists' to 'exists_file'

.devcontainer/devcontainer.json
Adds sonarlint to the devcointainer to help with clean code when developing.
* #0000
=> Add sonarlint to devcontainer

source/dotnet/Contracts/ProcessStepResultDto.cs, source/dotnet/Contracts/TimeSeriesPointDto.cs, source/dotnet/Packages/Client/Client.csproj, source/dotnet/Packages/Client/IWholesaleClient.cs, source/dotnet/Packages/Client/WholesaleClient.cs, source/dotnet/Packages/documents/release-notes/release-notes.md, source/dotnet/Services/Application/Batches/BatchApplicationService.cs, source/dotnet/Services/Application/Batches/IBatchApplicationService.cs, source/dotnet/Services/IntegrationTests/TestCommon/WebApi/BatchControllerTests.cs, source/dotnet/Services/WebApi/Controllers/V2/BatchController.cs
This PR adds a get method in the batchController that makes it possible to get a batch from a batchId
* #317
=> Implement get single batch call in batchController

source/databricks/package/calculator_args.py, source/databricks/package/calculator_job.py, source/databricks/package/infrastructure.py, source/databricks/package/integration_events_persister_streaming.py, source/databricks/tests/integration/calculator/test_calculator_job.py, source/databricks/tests/integration/integration_events_persister/test_integration_events_persister.py
=> refac: don't use external parameters that specifies container paths

source/databricks/package/balance_fixing_total_production.py, source/databricks/package/calculator_args.py, source/databricks/package/calculator_job.py
Add wholesale_container_path and fix mypy errors in package
* #507
=> refac: Add wholesale_container_path

source/databricks/package/balance_fixing_total_production.py
This PR will rename columns that are used more than once when joining from master basis data and times series to ensure no ambiguous references are left.
* #502
=> refac: ambigus refs in creating enriched timeseries

.gitignore
=> git: add mypy_cache to .gitignore

source/databricks/package/datamigration/migration_scripts/202212051200_Move_Events_To_Wholesale_Container.py, source/databricks/package/infrastructure.py, source/databricks/tests/datamigration/migration_scripts/test_202212051200_Move_Events_Wholesale_Container.py
=> migration: move events to wholesale container

source/dotnet/Services/DomainTests/WebApiTests.cs
=> test: change domaintests period

.github/workflows/packages-publish.yml, source/dotnet/Contracts/ProcessStepMeteringPointType.cs, source/dotnet/Contracts/ProcessStepResultDto.cs, source/dotnet/Packages/Client/Client.csproj, source/dotnet/Packages/documents/release-notes/release-notes.md, source/dotnet/Services/Application/Application.csproj, source/dotnet/Services/Application/ProcessResult/ProcessStepResultApplicationService.cs
Due to issues with generating the swagger model in the BFF when we used an enum called MeteringPointType (which was already in use by the MeteringPoint Domain). This PR will rename the enum to ProcessStepMeteringPointType
* #0000
=> refac: MeteringpointType -> ProcessStepMeteringPointType

source/databricks/package/__init__.py, source/databricks/package/balance_fixing_total_production.py, source/databricks/package/basis_data/__init__.py, source/databricks/tests/integration/calculator/basis_data/test_get_master_basis_data_df.py, source/databricks/tests/integration/calculator/basis_data/test_get_time_series_basis_data_dfs.py
=> refac: Begin segregating basis data functionality

docs/inter-domain-integration/metering-point-period-schema.py
=> doc: Fix metering point period to-date definition

source/databricks/package/balance_fixing.py, source/databricks/package/basis_data/__init__.py, source/databricks/package/calculation_input.py, source/databricks/package/constants/colname.py, source/databricks/tests/integration/calculator/balance_fixing/test_get_enriched_time_series_points_df.py, source/databricks/tests/integration/calculator/basis_data/test_get_master_basis_data_df.py, source/databricks/tests/integration/calculator/calculation_input/test_get_metering_point_periods_df.py, source/databricks/tests/integration/calculator/test_check_all_grid_areas_have_metering_points.py
=> refac: Use to/from date in lieu of effective date

source/dotnet/Services/DomainTests/Fixtures/WholesaleDomainConfiguration.cs, source/dotnet/Services/DomainTests/WebApiTests.cs
=> refact: hard coded grid area and batch id in domain test

source/databricks/package/balance_fixing.py, source/databricks/package/steps/aggregation/aggregation_result_formatter.py, source/databricks/package/steps/aggregation/aggregators.py
=> fix: Fix bad result in UI

source/contracts/internal/calculator-result.json, source/databricks/package/balance_fixing.py, source/dotnet/Services/Application/ProcessResult/ProcessResultPoint.cs
=> fix: Remove bad and not currently used/needed position

.docker/Dockerfile, .github/workflows/ci.yml, source/databricks/tests/integration/calculator/basis_data/test_get_master_basis_data_df.py
Updates from jupyter/pyspark-notebook:spark-3.1.2 to jupyter/pyspark-notebook:spark-3.3.0
and update the packages that are installed by mamba accordingly.
delta-spark==1.0.0 bumped to delta-spark==2.2.0
* #625
=> Build: Update Dockerfile jupyter spark version to 3.3.0

source/databricks/package/calculator_job.py, source/databricks/tests/integration/calculator/test_calculator_job.py
=> use correct schema for test data

source/dotnet/Services/Application/Batches/BatchApplicationService.cs, source/dotnet/Services/Application/Batches/BatchRequestDtoValidator.cs, source/dotnet/Services/Application/Batches/IBatchRequestDtoValidator.cs, source/dotnet/Services/Domain/BatchAggregate/Batch.cs, source/dotnet/Services/Domain/BatchAggregate/BatchFactory.cs, source/dotnet/Services/IntegrationTests/ProcessManager/BasisDataApplicationServiceTests.cs, source/dotnet/Services/IntegrationTests/TestCommon/ProcessManager/SubmitCreatedBatchesEndpointTests.cs, source/dotnet/Services/IntegrationTests/TestCommon/WebApi/BatchControllerTests.cs, source/dotnet/Services/Tests/Domain/BatchAggregate/BatchTests.cs, source/dotnet/Services/WebApi/Configuration/ServiceCollectionExtensions.cs, source/dotnet/Services/WebApi/Controllers/V2/BatchController.cs
This PR will refactor the `Batch` to support external validation, to support the WebApp with the ability to perform a validation check when requested to create a `Batch`.
Enabling it to return an `HttpRequest` with a 400 status code containing any validation errors from the `Batch`.
* #664
=> feat: Batch validation errors returns 400

source/dotnet/Services/Infrastructure/BasisData/BatchFileManager.cs
=> fix: GetZipFileName

source/databricks/package/infrastructure.py
=> fix: Update infrastructure.py Results_folder_name

source/dotnet/Services/Domain/BatchAggregate/Batch.cs, source/dotnet/Services/Tests/Domain/BatchAggregate/BatchTests.cs
=> feat: Batch validate startperiod

source/dotnet/Services/Application/Batches/BatchRequestDtoValidator.cs, source/dotnet/Services/Domain/BatchAggregate/Batch.cs, source/dotnet/Services/Domain/BatchAggregate/BatchFactory.cs, source/dotnet/Services/Infrastructure.Core/EnvironmentVariableHelper.cs, source/dotnet/Services/IntegrationTests/Hosts/ProcessManagerIntegrationTestHost.cs, source/dotnet/Services/IntegrationTests/Hosts/WebApiIntegrationTestHost.cs, source/dotnet/Services/IntegrationTests/ProcessManager/BasisDataApplicationServiceTests.cs, source/dotnet/Services/IntegrationTests/ProcessManager/BatchApplicationServiceTests.cs, source/dotnet/Services/IntegrationTests/TestCommon/Fixture/FunctionApp/ProcessManagerFunctionAppFixture.cs, source/dotnet/Services/IntegrationTests/TestCommon/Fixture/WebApi/WholesaleWebApiFixture.cs, source/dotnet/Services/IntegrationTests/TestCommon/Infrastructure/BatchRepositoryTests.cs, source/dotnet/Services/IntegrationTests/TestCommon/ProcessManager/SubmitCreatedBatchesEndpointTests.cs, source/dotnet/Services/IntegrationTests/TestCommon/WebApi/BatchControllerTests.cs, source/dotnet/Services/IntegrationTests/TestHelpers/Periods.cs, source/dotnet/Services/ProcessManager/EnvironmentSettingNames.cs, source/dotnet/Services/ProcessManager/Program.cs, source/dotnet/Services/Tests/Domain/BatchAggregate/BatchBuilder.cs, source/dotnet/Services/Tests/Domain/BatchAggregate/BatchFactoryTests.cs, source/dotnet/Services/Tests/Domain/BatchAggregate/BatchTests.cs, source/dotnet/Services/Tests/Hosts/ProcessManagerHostTests.cs, source/dotnet/Services/Tests/Infrastructure/JobRunner/DatabricksCalculatorJobParametersFactoryTests.cs, source/dotnet/Services/WebApi/Configuration/ServiceCollectionExtensions.cs, source/dotnet/Services/WebApi/EnvironmentSettingNames.cs
=> refac: Refactor hardcoded time zone id

source/databricks/package/datamigration/migration_scripts/202301031100_Move_Result_Json.py
Add the container to file path
* #199
=> fix: 202301031100_Move_Result_Json.py migration script

source/databricks/package/datamigration/migration_scripts/202301031100_Move_Result_Json.py
=> fix: 199 migration script 202301031100_Move_Result_Json.py

source/contracts/calculation-file-paths.yml, source/databricks/package/basis_data/__init__.py, source/databricks/package/calculator_job.py, source/databricks/package/datamigration/migration_scripts/202301091300_Move_Basis_Data.py, source/databricks/package/datamigration/migration_scripts/202301091500_Move_Master_Basis_Data.py, source/databricks/tests/integration/calculator/basis_data/test_get_master_basis_data_df.py, source/databricks/tests/integration/calculator/test_calculator_job.py, source/dotnet/Services/Infrastructure/BasisData/BatchFileManager.cs
Migrates basis-data and master-basis-data
* #199
=> Refac move basis data

source/databricks/package/datamigration/migration_scripts/202301101300_Clean_up_Old_Basis_Data_Folders.py
Deletes empty folders left after the latest migration of basis-data and master-basis-data
* #199
=> refac: Clean up Old Basis Data Folders

source/databricks/tests/integration/calculator/test_calculator_job.py
=> refac: clean-up test_calculator_job.py

source/contracts/calculation-file-paths.yml, source/databricks/package/balance_fixing.py, source/databricks/package/basis_data/__init__.py, source/databricks/package/calculator_job.py, source/databricks/package/datamigration/migration_scripts/202301120900_Rename_gln_for_basis_data.py, source/databricks/package/datamigration/migration_scripts/202301121000_Rename_gln_for_result.py, source/databricks/package/datamigration/migration_scripts/202301121100_Add_gln_for_zip.py, source/databricks/tests/integration/calculator/test_calculator_job.py, source/dotnet/Services/Infrastructure/BasisData/BatchFileManager.cs
=> Refac rename paths migration

source/dotnet/Services/Application/Infrastructure/IProcessCompletedIntegrationEventPublisher.cs, source/dotnet/Services/Application/Infrastructure/IProcessCompletedPublisher.cs, source/dotnet/Services/Application/Processes/IBasisDataApplicationService.cs, source/dotnet/Services/Application/Processes/IProcessApplicationService.cs, source/dotnet/Services/Application/Processes/IProcessTypeMapper.cs, source/dotnet/Services/Application/Processes/ProcessApplicationService.cs, source/dotnet/Services/Application/Processes/ProcessCompletedEventDto.cs, source/dotnet/Services/Application/Processes/ProcessTypeMapper.cs, source/dotnet/Services/Infrastructure/Batches/BatchCompletedPublisher.cs, source/dotnet/Services/Infrastructure/InstantExtensions.cs, source/dotnet/Services/Infrastructure/Integration/IProcessCompletedIntegrationEventMapper.cs, source/dotnet/Services/Infrastructure/Integration/ProcessCompleted.proto, source/dotnet/Services/Infrastructure/Integration/ProcessCompletedIntegrationEventMapper.cs, source/dotnet/Services/Infrastructure/Integration/ProcessCompletedIntegrationEventPublisher.cs, source/dotnet/Services/Infrastructure/Processes/ProcessCompletedPublisher.cs, source/dotnet/Services/Infrastructure/Processes/ServiceCollectionExtensions.cs, source/dotnet/Services/Infrastructure/ServiceBus/IServiceBusMessageFactory.cs, source/dotnet/Services/Infrastructure/ServiceBus/ServiceBusMessageFactory.cs, source/dotnet/Services/IntegrationTests/TestCommon/ProcessManager/PublishProcessCompletedIntegrationEventEndpointTests.cs, source/dotnet/Services/IntegrationTests/TestCommon/ProcessManager/SubmitCreatedBatchesEndpointTests.cs, source/dotnet/Services/IntegrationTests/TestCommon/ServiceBusTestListener.cs, source/dotnet/Services/ProcessManager/Endpoints/PublishProcessCompletedEventsEndpoint.cs, source/dotnet/Services/ProcessManager/Endpoints/PublishProcessCompletedIntegrationEventEndpoint.cs, source/dotnet/Services/ProcessManager/Endpoints/ZipBasisDataEndpoint.cs, source/dotnet/Services/ProcessManager/Program.cs, source/dotnet/Services/Tests/Application/Processes/ProcessApplicationServiceTest.cs, source/dotnet/Services/Tests/Infrastructure/Processes/ProcessCompletedIntegrationEventPublisherTests.cs
- Add period to contract
- Make process type dynamic (get it from the batch)
- Fix published integration event to be protobuf encoded
* #690
=> feature: Add period to process-completed-integration-event

source/dotnet/Services/Application/Batches/BatchApplicationService.cs, source/dotnet/Services/Application/Processes/IProcessCompletedEventDtoFactory.cs, source/dotnet/Services/Application/Processes/ProcessApplicationService.cs, source/dotnet/Services/Application/Processes/ProcessCompletedEventDtoFactory.cs, source/dotnet/Services/ProcessManager/Program.cs, source/dotnet/Services/Tests/Application/Processes/ProcessApplicationServiceTest.cs, source/dotnet/Services/Tests/Application/Processes/ProcessCompletedEventDtoFactoryTests.cs
The focus is on the `ProcessApplicationService`.
* #690
=> refac: Improve code cleanliness

source/dotnet/Services/ProcessManager/Program.cs
=> feat: Add integration events topic in health check

source/dotnet/Services/IntegrationTests/TestCommon/ProcessManager/PublishProcessCompletedIntegrationEventEndpointTests.cs, source/dotnet/Services/Tests/Infrastructure/InstantExtensionsTests.cs
=> test: Add test of `InstantExtensions`

source/dotnet/Services/Application/Batches/BatchApplicationService.cs, source/dotnet/Services/Application/Infrastructure/IBatchCompletedPublisher.cs, source/dotnet/Services/Infrastructure/Batches/BatchCompletedPublisher.cs, source/dotnet/Services/Infrastructure/Batches/ServiceCollectionExtensions.cs, source/dotnet/Services/IntegrationTests/TestCommon/ProcessManager/PublishProcessCompletedIntegrationEventEndpointTests.cs, source/dotnet/Services/IntegrationTests/TestCommon/ProcessManager/SubmitCreatedBatchesEndpointTests.cs, source/dotnet/Services/IntegrationTests/TestCommon/ServiceBusTestListener.cs
This PR will:
- minor refactor involving `ServiceBusTestListener.ListenForMessageAsync(string correlationId)`
- Namespace update for `IBatchCompletedPublisher`
* #690
=> refac: ListenForMessageAsync with specefic correlationId

source/databricks/package/balance_fixing.py, source/databricks/package/calculation_input.py
=> Re-introduce agg sum in balance_fixing

source/databricks/package/balance_fixing.py, source/databricks/package/calculation_output_writer.py, source/databricks/package/steps/aggregation/aggregators.py, source/databricks/tests/integration/calculator/steps/aggregation/test_consumption_ga_brp_es.py, source/databricks/tests/integration/calculator/steps/aggregation/test_non_profiled_consumption.py, source/databricks/tests/integration/calculator/steps/aggregation/test_production.py, source/databricks/tests/integration/calculator/steps/aggregation/test_production_ga_brp_es.py, source/databricks/tests/integration/calculator/test_calculator_job.py
This PR splits the functionality of balance fixing into small functions. It also gets rid of several of the uses of the result dictionary from aggregators and use explicit input/output
* #199
=> refac: make smaller functions in balance fixing

.github/workflows/cd.yml, .github/workflows/ci.yml, .github/workflows/packages-publish.yml, source/dotnet/Packages/Client.Documentation/release-notes/release-notes.md, source/dotnet/Packages/Client/Client.csproj, source/dotnet/Packages/Contracts.Documentation/release-notes/release-notes.md, source/dotnet/Packages/Contracts/Contracts.csproj, source/dotnet/Services/IntegrationTests/TestCommon/Fixture/FunctionApp/ProcessManagerFunctionAppFixture.cs, source/dotnet/Services/IntegrationTests/integrationtest.local.settings.sample.json
Refactor to use new secret/setting name.
https://app.zenhub.com/workspaces/the-outlaws-6193fe815d79fc0011e741b1/issues/gh/energinet-datahub/the-outlaws/720
=> Cleanup secrets

.github/workflows/detect-changes.yml, .github/workflows/packages-publish.yml
=> Add allow merge on nuget

source/dotnet/Services/ProcessManager/EnvironmentSettingNames.cs
=> refac: Update settings name

.github/workflows/packages-publish.yml
=> Compare ==

.github/workflows/packages-publish.yml, source/dotnet/Packages/Client.Documentation/release-notes/release-notes.md, source/dotnet/Packages/Client/Client.csproj, source/dotnet/Packages/Contracts.Documentation/release-notes/release-notes.md, source/dotnet/Packages/Contracts/Contracts.csproj
Change condition on NuGet package pipeline for allow_merge
=> Change condition

source/dotnet/Services/Infrastructure/BatchActor/ActorRepository.cs, source/dotnet/Services/Infrastructure/Integration/DataLake/DataLakeClient.cs, source/dotnet/Services/Infrastructure/Processes/ProcessStepResultRepository.cs, source/dotnet/Services/UnitTests/Infrastructure/Actor/ActorRepositoryTests.cs, source/dotnet/Services/UnitTests/Infrastructure/Integration/DataLake/DataLakeClientTests.cs, source/dotnet/Services/UnitTests/Infrastructure/Processes/ProcessStepResultRepositoryTests.cs
=> Clean up DataLakeClient usage

source/databricks/package/calculator_job.py, source/databricks/tests/integration/calculator/test_calculator_job.py
=> fix: use correct method name for getting container path

source/dotnet/Services/IntegrationTests/WebApi/ProcessStepControllerTests.cs, source/dotnet/Services/WebApi/Controllers/V2/ProcessStepController.cs
=> test: Add endpoint tests of process steps API

source/dotnet/Packages/Client.Documentation/release-notes/release-notes.md, source/dotnet/Packages/Client/Client.csproj, source/dotnet/Packages/Client/IWholesaleClient.cs, source/dotnet/Packages/Contracts.Documentation/release-notes/release-notes.md, source/dotnet/Packages/Contracts/Contracts.csproj
The GetProcessStepActorsAsync method has been implented, but is not available for clients. This PR fixes that. 
* #199
=> fix: expose GetProcessStepActorsAsync

source/databricks/package/codelists/time_series_quality.py, source/databricks/package/steps/aggregation/aggregators.py, source/databricks/tests/integration/calculator/steps/aggregation/test_production_ga_brp_es.py
Adds "incomplete A05" to the quality mix and makes sure that there can not be any None values in received quantity
* #199
=> fix: aggregate_sum_and_set_quality

source/dotnet/Services/DatabaseMigration/DatabaseMigration.csproj, source/dotnet/Services/DatabaseMigration/Scripts/202302031200_Drop_MessageHub.sql
=> refac: Remove MessageHub reminiscence

.docker/Dockerfile, source/databricks/package/shared/period.py, source/databricks/package/steps/aggregation/grid_loss_calculator.py, source/databricks/package/steps/wholesale/wholesale_initializer.py, source/databricks/tests/integration/calculator/steps/wholesale/test_wholesale_initializer.py
=> fix: minor mypy errors

source/databricks/README.md
=> doc: Update databricks README.md with mypy

source/dotnet/Services/IntegrationTests/WebApi/SwaggerTests.cs, source/dotnet/Services/WebApi/Startup.cs
=> test: Test Swagger doc and spec generation

source/dotnet/Services/IntegrationTests/Fixtures/TestCommon/Fixture/WebApi/WholesaleWebApiFixture.cs, source/dotnet/Services/IntegrationTests/Fixtures/WebApi/WebApiFactory.cs, source/dotnet/Services/IntegrationTests/WebApi/HealthCheckTests.cs, source/dotnet/Services/WebApi/Startup.cs
=> fix: Fix broken health check test

source/dotnet/Services/ProcessManager.IntegrationTests/SubmitCreatedBatchesEndpointTests.cs, source/dotnet/Services/WebApi.IntegrationTests/WebApi/DatabaseHealthCheckTests.cs
=> refac: SubmitCreatedBatchesEndpointTests Handle skipped tests

source/dotnet/Services/WebApi/Startup.cs
This PR will add the XML documentation from the WebApi project to the exposed Swagger.
* #782
=> feat: extend Swagger documentation

.github/CODEOWNERS
=> Add energinet-ajw as codeowner

source/databricks/package/datamigration/migration_scripts/202302231200_Remove_result_temp_folder.py
=> Clean up result_temp folders

source/contracts/calculation-file-paths.yml, source/databricks/package/balance_fixing.py, source/databricks/package/constants/partition_key_name.py, source/databricks/package/file_writers/process_step_result_writer.py, source/databricks/package/infrastructure.py, source/databricks/tests/helpers/assert_calculation_file_path.py, source/databricks/tests/integration/calculator/file_writers/test_process_step_result_writer.py, source/databricks/tests/integration/calculator/test_calculator_job.py, source/dotnet/Services/WebApi.UnitTests/Infrastructure/SettlementReport/CalculationFilePathsContract.cs
=> feat: calculate ga brp es

source/contracts/calculation-file-paths.yml, source/dotnet/Services/Infrastructure/Processes/ProcessStepResultRepository.cs, source/dotnet/Services/WebApi.UnitTests/Infrastructure/Processes/ProcessStepResultRepositoryTests.cs
=> feat: read result for es brp ga

source/databricks/package/datamigration/migration_scripts/202303031030_Remove_result_temp_folder.py
=> clean up result temp folder

source/databricks/package/balance_fixing.py, source/databricks/tests/integration/calculator/test_calculator_job.py
=> feat: add non-profiled consumption per grid area

source/dotnet/Services/Application/ProcessStep/Model/ProcessStepResultMapper.cs, source/dotnet/Services/Domain/ProcessStepResultAggregate/QuantityQuality.cs, source/dotnet/Services/Domain/ProcessStepResultAggregate/TimeSeriesPoint.cs, source/dotnet/Services/Domain/ProcessStepResultAggregate/TimeSeriesPointQuality.cs, source/dotnet/Services/Infrastructure/Processes/ProcessStepResultRepository.cs, source/dotnet/Services/WebApi.UnitTests/Application/ProcessStep/Model/ProcessStepMapperTests.cs, source/dotnet/Services/WebApi.UnitTests/Application/ProcessStep/ProcessStepApplicationServiceTests.cs, source/dotnet/Services/WebApi.UnitTests/Domain/ProcessStepResultAggregate/ProcessStepResultAggregateTests.cs, source/dotnet/Services/WebApi.UnitTests/Domain/ProcessStepResultAggregate/TimeSeriesPointQualityContractTests.cs, source/dotnet/Services/WebApi.UnitTests/Infrastructure/SettlementReport/SettlementReportRepositoryTests.cs
=> refac: timeseriespoint to have a enum for quality

source/dotnet/Contracts/calculation_result_completed.proto, source/dotnet/Packages/Client.Documentation/release-notes/release-notes.md, source/dotnet/Packages/Client/Client.csproj, source/dotnet/Packages/Contracts.Documentation/release-notes/release-notes.md, source/dotnet/Packages/Contracts/Contracts.csproj
=> fix: Correct errors in contract `calculation_result_completed.proto`

source/dotnet/Contracts/BatchDtoV2.cs, source/dotnet/Packages/Client.Documentation/release-notes/release-notes.md, source/dotnet/Packages/Client/Client.csproj, source/dotnet/Packages/Contracts.Documentation/release-notes/release-notes.md, source/dotnet/Packages/Contracts/Contracts.csproj, source/dotnet/Services/WebApi/V2/BatchDtoV2Mapper.cs
=> feat: add ProcessType to BatchDtoV2

source/dotnet/Services/WebApi/V2/BatchController.cs, source/dotnet/Services/WebApi/V2/BatchControllerV21.cs, source/dotnet/Services/WebApi/V2/ProcessStepControllerV21.cs, source/dotnet/Services/WebApi/V2/ProcessStepControllerV22.cs, source/dotnet/Services/WebApi/V2/ProcessStepControllerV23.cs, source/dotnet/Services/WebApi/V2/ProcessStepControllerV24.cs, source/dotnet/Services/WebApi/V2/SettlementReportController.cs
=> Add return type on api calls for swagger gen

source/dotnet/Services/WebApi/V3/ProcessStepBalanceResponsibleParty/ProcessStepBalanceResponsiblePartyController.cs, source/dotnet/Services/WebApi/V3/ProcessStepEnergySupplier/ProcessStepEnergySupplierController.cs, source/dotnet/Services/WebApi/V3/ProcessStepResult/ProcessStepResultController.cs
=> refec: return types on api v3

source/dotnet/Services/Infrastructure/Processes/ProcessStepResultRepository.cs
=> fix: incomplete QuantityQuality fix

source/dotnet/Packages/Client.Documentation/release-notes/release-notes.md, source/dotnet/Packages/Contracts.Documentation/release-notes/release-notes.md
Updated missing release-notes.
* #855
=> Updated release-notes.

source/dotnet/Services/Domain/BatchAggregate/Batch.cs, source/dotnet/Services/WebApi.UnitTests/Domain/BatchAggregate/BatchTests.cs
… and tests.
(https://app.zenhub.com/workspaces/mandalorian-5fd22a1a59e4740018f5ab5a/issues/gh/energinet-datahub/opengeh-wholesale/855)
=> Added missing resolution and quantity unit for new process types. 

source/dotnet/Services/Application/IIntegrationEventPublisher.cs, source/dotnet/Services/Application/Processes/ProcessApplicationService.cs, source/dotnet/Services/Infrastructure/EventPublishers/IntegrationEventPublisher.cs, source/dotnet/Services/Infrastructure/Integration/CalculationResultReadyIntegrationEventFactory.cs, source/dotnet/Services/Infrastructure/Integration/ICalculationResultReadyIntegrationEventFactory.cs, source/dotnet/Services/WebApi.UnitTests/Application/Processes/ProcessApplicationServiceTest.cs, source/dotnet/Services/WebApi.UnitTests/Infrastructure/Integration/CalculationResultReadyIntegrationEventFactoryTests.cs
=> feat: publish result for brp_ga

source/dotnet/Services/Infrastructure/Processes/ProcessStepResultRepository.cs, source/dotnet/Services/Infrastructure/Processes/QuantityQualityMapper.cs, source/dotnet/Services/WebApi.UnitTests/Infrastructure/Integration/TimeSeriesTypeMapperTests.cs, source/dotnet/Services/WebApi.UnitTests/Infrastructure/Processes/QuantityQualityMapperTests.cs
=> bug: handle "missing" quality

source/dotnet/Services/Application/IIntegrationEventPublisher.cs, source/dotnet/Services/Application/Processes/ProcessApplicationService.cs, source/dotnet/Services/Infrastructure/EventPublishers/IntegrationEventPublisher.cs, source/dotnet/Services/Infrastructure/Integration/CalculationResultReadyIntegrationEventFactory.cs, source/dotnet/Services/Infrastructure/Integration/ICalculationResultReadyIntegrationEventFactory.cs, source/dotnet/Services/WebApi.UnitTests/Application/Processes/ProcessApplicationServiceTest.cs, source/dotnet/Services/WebApi.UnitTests/Infrastructure/Integration/CalculationResultReadyIntegrationEventFactoryTests.cs
=> feat: publish result for es brp ga

source/dotnet/Services/Infrastructure/BatchActor/ActorRepository.cs, source/dotnet/Services/WebApi.UnitTests/Infrastructure/Actor/ActorRepositoryTests.cs
A task have been created to investigate this here: https://app.zenhub.com/workspaces/mandalorian-5fd22a1a59e4740018f5ab5a/issues/gh/energinet-datahub/opengeh-wholesale/886
* #886
=> bug: remove empty actor relations

source/dotnet/Services/Application/Processes/ProcessApplicationService.cs, source/dotnet/Services/WebApi.UnitTests/Application/Processes/ProcessApplicationServiceTest.cs
=> bug: publish result for brp

source/databricks/package/balance_fixing.py, source/databricks/package/codelists/__init__.py, source/databricks/package/codelists/aggregation_level.py, source/databricks/package/file_writers/basis_data_writer.py, source/databricks/package/file_writers/process_step_result_writer.py, source/databricks/package/infrastructure.py, source/databricks/tests/integration/calculator/file_writers/test_process_step_result_writer.py, source/databricks/tests/integration/calculator/test_calculator_job.py
This PR does not change the name of the data lake folder - that is still called 'grouping', and will require a migration (or delete of old data).
* #892
=> refac: rename Grouping enum to AggregationLevel

source/contracts/calculation-file-paths.yml, source/dotnet/Services/Infrastructure/Processes/ProcessStepResultRepository.cs
=> bug: read es_brp_ga on correct path

.github/workflows/packages-publish.yml, source/dotnet/DatabaseMigration/DatabaseMigration.csproj, source/dotnet/DomainTests/DomainTests.csproj, source/dotnet/Packages/Client.Documentation/release-notes/release-notes.md, source/dotnet/Packages/Client.Tests/Client.Tests.csproj, source/dotnet/Packages/Client/Client.csproj, source/dotnet/process-manager/ProcessManager.IntegrationTests/ProcessManager.IntegrationTests.csproj, source/dotnet/process-manager/ProcessManager/ProcessManager.csproj, source/dotnet/wholesale-api/Application/Application.csproj, source/dotnet/wholesale-api/DatabricksClient/DatabricksClient.csproj, source/dotnet/wholesale-api/Domain/Domain.csproj, source/dotnet/wholesale-api/Infrastructure.Core/Infrastructure.Core.csproj, source/dotnet/wholesale-api/Infrastructure/Infrastructure.csproj, source/dotnet/wholesale-api/WebApi.IntegrationTests/WebApi.IntegrationTests.csproj, source/dotnet/wholesale-api/WebApi.IntegrationTests/functionapphost.settings.json, source/dotnet/wholesale-api/WebApi.UnitTests/WebApi.UnitTests.csproj, source/dotnet/wholesale-api/WebApi/WebApi.csproj, source/dotnet/wholesale-integration-events-package/Contracts.Documentation/release-notes/release-notes.md, source/dotnet/wholesale-integration-events-package/Contracts.Tests/Contracts.Tests.csproj, source/dotnet/wholesale-integration-events-package/Contracts/Contracts.csproj
=> update: Bump NuGet package versions

.github/workflows/cd.yml
=> fix: Do not static check notebooks

.gitignore, .vscode/extensions.json, .vscode/launch.json, .vscode/settings.json
=> tools: Add VSCode extension recommendations

source/dotnet/wholesale-api/Application/Processes/ProcessApplicationService.cs, source/dotnet/wholesale-api/WebApi.UnitTests/Application/Processes/ProcessApplicationServiceTest.cs
This time with an enhanced test to ensure the correct result is returned for the given actor.
* #0000
=> fix: get correct result for brp + tests

source/dotnet/wholesale-api/WebApi/V3/Batch/BatchController.cs
=> refac: Add required to BatchCreate BatchRequestDto

source/dotnet/wholesale-api/WebApi.IntegrationTests/Infrastructure/Persistence/Outbox/OutboxRepositoryTests.cs
=> test: Optimize testsuite by parallelizing more

source/dotnet/wholesale-api/WebApi.IntegrationTests/WebApi/V3/BatchControllerTests.cs, source/dotnet/wholesale-api/WebApi/V3/Batch/BatchController.cs
The removed hack with 1 ms before midnight will need to be implemented in BFF, if this issue is not fixed in frontend
* #888
=> refac: Add get and search to v3 api

source/dotnet/process-manager/ProcessManager/Endpoints/DeleteOlderIntegrationEventsEndpoint.cs, source/dotnet/process-manager/ProcessManager/Endpoints/PublishIntegrationEventsEndpoint.cs, source/dotnet/process-manager/ProcessManager/Program.cs, source/dotnet/wholesale-api/Application/IntegrationEventsManagement/IIntegrationEventCleanUpService.cs, source/dotnet/wholesale-api/Application/IntegrationEventsManagement/IIntegrationEventDispatcher.cs, source/dotnet/wholesale-api/Application/IntegrationEventsManagement/IIntegrationEventPublisher.cs, source/dotnet/wholesale-api/Application/IntegrationEventsManagement/IIntegrationEventService.cs, source/dotnet/wholesale-api/Application/IntegrationEventsManagement/IntegrationEventDto.cs, source/dotnet/wholesale-api/Application/IntegrationEventsManagement/IntegrationEventService.cs, source/dotnet/wholesale-api/Application/Processes/ICalculationResultCompletedFactory.cs, source/dotnet/wholesale-api/Application/Processes/ProcessApplicationService.cs, source/dotnet/wholesale-api/Infrastructure/EventPublishers/CalculationResultCompletedToIntegrationEventFactory.cs, source/dotnet/wholesale-api/Infrastructure/IntegrationEventDispatching/IntegrationEventDispatcher.cs, source/dotnet/wholesale-api/Infrastructure/Persistence/Outbox/IntegrationEventCleanUpService.cs, source/dotnet/wholesale-api/WebApi.UnitTests/Application/IntegrationEventsManagement/IntegrationEventDispatcherServiceTests.cs, source/dotnet/wholesale-api/WebApi.UnitTests/Application/Processes/ProcessApplicationServiceTest.cs, source/dotnet/wholesale-api/WebApi.UnitTests/Infrastructure/EventPublishers/IntegrationEventCleanUpServiceTests.cs, source/dotnet/wholesale-api/WebApi.UnitTests/Infrastructure/IntegrationEventPublishing/IntegrationEventDispatcherTests.cs
Added two tests of DispatchIntegrationEventsAsync().
* #887
=> refac: tests of dispatcher 

source/dotnet/wholesale-api/Infrastructure/EventPublishers/IIntegrationEventDispatcher.cs, source/dotnet/wholesale-api/Infrastructure/IntegrationEventDispatching/IntegrationEventDispatcher.cs
Changed the comment on the interface method name "DispatchIntegrationEventsAsync".
* #887
=> refac: Comment on IIntegrationEventDispatcher.cs

source/dotnet/wholesale-api/Application/Application.csproj, source/dotnet/wholesale-api/Application/Batches/BatchApplicationService.cs, source/dotnet/wholesale-api/Application/Batches/CreateBatchCommand.cs, source/dotnet/wholesale-api/Application/Batches/CreateBatchHandler.cs, source/dotnet/wholesale-api/Application/Batches/IBatchApplicationService.cs, source/dotnet/wholesale-api/WebApi.IntegrationTests/Fixtures/WebApi/WebApiFactory.cs, source/dotnet/wholesale-api/WebApi.IntegrationTests/WebApi/V2/BatchControllerTests.cs, source/dotnet/wholesale-api/WebApi/Startup.cs, source/dotnet/wholesale-api/WebApi/V2/BatchController.cs, source/dotnet/wholesale-api/WebApi/V3/Batch/BatchController.cs, source/dotnet/wholesale-api/WebApi/WebApi.csproj
=> feat: create batch from mediatr

source/dotnet/Wholesale.sln.DotSettings, source/dotnet/process-manager/ProcessManager/Program.cs, source/dotnet/process-manager/ProcessManager/Root.cs, source/dotnet/wholesale-api/Application/Root.cs, source/dotnet/wholesale-api/Domain/Root.cs, source/dotnet/wholesale-api/Infrastructure/Root.cs, source/dotnet/wholesale-api/WebApi/Startup.cs
Unit tests will be added in another PR.
* #972
=> fix: Register all MediatR handlers

source/dotnet/wholesale-api/Infrastructure/IntegrationEventDispatching/IntegrationEventDispatcher.cs, source/dotnet/wholesale-api/Infrastructure/ServiceBus/IIntegrationEventTopicServiceBusSender.cs, source/dotnet/wholesale-api/Infrastructure/ServiceBus/IntegrationEventTopicServiceBusSender.cs, source/dotnet/wholesale-api/WebApi.UnitTests/Infrastructure/IntegrationEventPublishing/IntegrationEventDispatcherTests.cs
Trying to fix error while sending integration messages.
* #887
=> refac: send integration messages (bulk)

source/databricks/calculation-engine/package/file_writers/process_step_result_writer.py, source/databricks/calculation-engine/package/schemas/__init__.py, source/databricks/calculation-engine/package/schemas/results_schema.py, source/databricks/calculation-engine/tests/integration/calculator/calculator_job/test_calculator_job_results.py, source/databricks/calculation-engine/tests/integration/calculator/file_writers/test_process_step_result_writer.py
=> fix: Ensure create of and write to the `results` Delta table conforms to a schema

source/dotnet/wholesale-api/WebApi.IntegrationTests/WebApi/V3/OpenApiSpecificationTests.cs, source/dotnet/wholesale-api/WebApi/BinaryContentAttribute.cs, source/dotnet/wholesale-api/WebApi/BinaryContentFilter.cs, source/dotnet/wholesale-api/WebApi/Startup.cs, source/dotnet/wholesale-api/WebApi/V3/SettlementReport/SettlementReportController.cs
=> fix: swagger stream

source/dotnet/wholesale-api/WebApi.IntegrationTests/WebApi/V3/OpenApiSpecificationTests.cs, source/dotnet/wholesale-api/WebApi/V3/SettlementReport/SettlementReportController.cs
=> refac: GetSettlementReportAsync requires gridareacode

source/databricks/calculation-engine/package/steps/aggregation/exchange_aggregators.py, source/databricks/calculation-engine/tests/integration/calculator/steps/aggregation/test_net_exchange_grid_area_aggregation.py
=> fix: Update net exchange per ga aggregation to handle ga with outgoing exchange but no incoming

source/databricks/README.md
In order to re-trigger CD on t-001, which has been failing until now.
* #0000
=> Trigger CD

README.md
=> docs: swagger nswag section added

source/dotnet/wholesale-api/WebApi.UnitTests/WebApi.UnitTests.csproj
=> refac: removed Energinet.DataHub.Core.Schemas

source/dotnet/wholesale-api/Application/Batches/CreateBatchHandler.cs, source/dotnet/wholesale-api/Infrastructure/Pipelines/UnitOfWorkPipelineBehavior.cs, source/dotnet/wholesale-api/Test.Core/Periods.cs, source/dotnet/wholesale-api/Test.Core/Test.Core.csproj, source/dotnet/wholesale-api/WebApi.IntegrationTests/Infrastructure/Persistence/Batch/BatchRepositoryTests.cs, source/dotnet/wholesale-api/WebApi.IntegrationTests/WebApi/V3/BatchControllerTests.cs, source/dotnet/wholesale-api/WebApi.UnitTests/Application/Batches/CreateBatchHandlerTests.cs, source/dotnet/wholesale-api/WebApi.UnitTests/Infrastructure/Pipelines/UnitOfWorkPipelineBehaviorTests.cs, source/dotnet/wholesale-api/WebApi/Startup.cs
=> refac: added unit of work pipeline (mediatr)

source/dotnet/wholesale-api/Application/Batches/CreateBatchCommand.cs, source/dotnet/wholesale-api/Application/Batches/Model/BatchRequestDto.cs, source/dotnet/wholesale-api/WebApi.IntegrationTests/Application/RequestMatchingHandlerTests.cs, source/dotnet/wholesale-api/WebApi/WebApi.csproj
The added test ensures that a command or query also has a handler. 
The test scans the four main assemblies (WebApi, Application, Domain and Infrastructure).
* #972
=> refac: added request-handler test 

source/dotnet/wholesale-api/WebApi/Configuration/ServiceCollectionExtensions.cs
=> bug: fix IDomainEventDispatcher merge error

source/dotnet/wholesale-api/WebApi.IntegrationTests/Fixtures/Hosts/WebApiIntegrationTestHost.cs, source/dotnet/wholesale-api/WebApi/Configuration/Options/ConnectionStringsOptions.cs, source/dotnet/wholesale-api/WebApi/Configuration/Options/DateTimeOptions.cs, source/dotnet/wholesale-api/WebApi/Configuration/Options/JwtOptions.cs, source/dotnet/wholesale-api/WebApi/Configuration/Options/ServiceBusOptions.cs, source/dotnet/wholesale-api/WebApi/Configuration/ServiceCollectionExtensions.cs, source/dotnet/wholesale-api/WebApi/ConfigurationSettingNames.cs, source/dotnet/wholesale-api/WebApi/Startup.cs
More options have been added.
- Service Bus options have been added
- JWT options have been added
- DateTime options have been added
* #934
=> refac: Options pattern (part 3) 

source/dotnet/wholesale-api/WebApi.IntegrationTests/WebApi/HealthCheckTests.cs
=> Skip health check test in WebApi to see consequence on CI/CD stability

source/databricks/calculation-engine/package/file_writers/process_step_result_writer.py, source/databricks/calculation-engine/package/schemas/results_schema.py
=> doc: About ordering of data frame columns

source/dotnet/wholesale-api/WebApi.IntegrationTests/WebApi/DatabaseHealthCheckTests.cs, source/dotnet/wholesale-api/WebApi.IntegrationTests/WebApi/HealthCheckTests.cs
=> skip database health check

docs/test-strategy.md
=> Force redeploy to t-001

.github/workflows/cd.yml, .github/workflows/codeql.yml
=> move codeql cd trigger to cd.yml

.github/workflows/cd.yml
=> remove dotnet coverage upload on cd

source/dotnet/wholesale-api/WebApi.UnitTests/WebApi/V3/BatchDtoMapperTests.cs, source/dotnet/wholesale-api/WebApi.UnitTests/WebApi/V3/BatchStateMapperTests.cs, source/dotnet/wholesale-api/WebApi.UnitTests/WebApi/V3/ProcessStepResultFactoryTests.cs, source/dotnet/wholesale-api/WebApi.UnitTests/WebApi/V3/ProcessTypeMapperTests.cs, source/dotnet/wholesale-api/WebApi/V3/Batch/BatchController.cs, source/dotnet/wholesale-api/WebApi/V3/Batch/BatchDto.cs, source/dotnet/wholesale-api/WebApi/V3/Batch/BatchDtoMapper.cs, source/dotnet/wholesale-api/WebApi/V3/Batch/BatchRequestDto.cs, source/dotnet/wholesale-api/WebApi/V3/Batch/BatchSearchDto.cs, source/dotnet/wholesale-api/WebApi/V3/Batch/BatchState.cs, source/dotnet/wholesale-api/WebApi/V3/Batch/BatchStateMapper.cs, source/dotnet/wholesale-api/WebApi/V3/Batch/ProcessType.cs, source/dotnet/wholesale-api/WebApi/V3/Batch/ProcessTypeMapper.cs, source/dotnet/wholesale-api/WebApi/V3/ProcessStepResult/ProcessStepResultController.cs, source/dotnet/wholesale-api/WebApi/V3/ProcessStepResult/ProcessStepResultDto.cs, source/dotnet/wholesale-api/WebApi/V3/ProcessStepResult/ProcessStepResultFactory.cs
=> refac: V3 has its own models of Batch

source/dotnet/process-manager/ProcessManager/Program.cs, source/dotnet/wholesale-api/WebApi/Configuration/BatchesRegistration.cs, source/dotnet/wholesale-api/WebApi/Configuration/CalculationResultsRegistration.cs
=> refac: module registration in host

source/databricks/calculation-engine/package/balance_fixing.py
=> fix grid loss calculation prop order in balance fixing

source/dotnet/process-manager/ProcessManager/ProcessManager.csproj, source/dotnet/process-manager/ProcessManager/Program.cs, source/dotnet/wholesale-api/WebApi.IntegrationTests/CompositionRootTests.cs, source/dotnet/wholesale-api/WebApi/Configuration/BatchesRegistration.cs, source/dotnet/wholesale-api/WebApi/Configuration/IntegrationEventPublishingRegistration.cs, source/dotnet/wholesale-api/WebApi/Configuration/ServiceCollectionExtensions.cs, source/dotnet/wholesale-api/WebApi/Startup.cs
DI container configuration is owned by web API as process manager is planned to be removed. Meanwhile the modules configurations are available in the process manager using linked files:
* #972
=> test: Add test of web API DI container configuration

source/dotnet/wholesale-api/Batches/Batches.Application/Workers/StartCalculationWorker.cs, source/dotnet/wholesale-api/WebApi/Configuration/BatchesRegistration.cs, source/dotnet/wholesale-api/WebApi/Properties/launchSettings.json
=> fix: Fix batch calculation start

source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/CalculationResultClient/CalculationResultClient.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/CalculationResultClient/Mappers/AggregationLevelMapper.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/CalculationResultClient/Mappers/MeteringPointTypeMapper.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/CalculationResultClient/Mappers/ProcessTypeMapper.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/CalculationResultClient/Mappers/QuantityQualityMapper.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/CalculationResultClient/Mappers/SettlementMethodMapper.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/CalculationResultClient/Mappers/TimeSeriesTypeMapper.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/Processes/ProcessStepResultRepository.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Interfaces/CalculationResultClient/SettlementReportResultRow.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.UnitTests/CalculationResults.UnitTests.csproj, source/dotnet/wholesale-api/CalculationResults/CalculationResults.UnitTests/Infrastructure/CalculationResultClient/Mappers/AggregationLevelMapperTest.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.UnitTests/Infrastructure/CalculationResultClient/Mappers/MeteringPointTypeMapperTest.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.UnitTests/Infrastructure/CalculationResultClient/Mappers/ProcessTypeMapperTest.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.UnitTests/Infrastructure/CalculationResultClient/Mappers/QuantityQualityMapperTests.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.UnitTests/Infrastructure/CalculationResultClient/Mappers/SettlementMethodMapperTest.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.UnitTests/Infrastructure/CalculationResultClient/Mappers/TimeSeriesTypeMapperTest.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.UnitTests/Infrastructure/CalculationResultClient/QuantityQualityMapperTests.cs
=> refac: add mapper classes in CalculationResult

source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/CalculationResultClient/Mappers/MeteringPointTypeMapper.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/CalculationResultClient/Mappers/SettlementMethodMapper.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/CalculationResultClient/Mappers/TimeSeriesTypeMapper.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/Processes/TimeSeriesTypeMapper.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Interfaces/CalculationResultClient/TimeSeriesType.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Interfaces/ProcessStep/Model/TimeSeriesType.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Interfaces/ProcessStep/Model/TimeSeriesTypeMapper.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.UnitTests/Application/ProcessStep/Model/TimeSeriesTypeMapperTests.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.UnitTests/Infrastructure/CalculationResultClient/Mappers/TimeSeriesTypeMapperTest.cs
=> add NetExchangePerGridArea to TimeSeriesType in .NET

source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/CalculationResultClient/DatabricksSqlResponseParser.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.UnitTests/Infrastructure/CalculationResultClient/CalculationResultClientTests.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.UnitTests/Infrastructure/CalculationResultClient/DatabricksSqlResponseParserTests.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.UnitTests/Infrastructure/CalculationResultClient/TableTestHelper.cs
=> feat: return zero rows in settlement report if no relevant data

source/dotnet/Wholesale.sln, source/dotnet/domain-tests/DomainTests.csproj, source/dotnet/wholesale-api/Batches/Batches.Infrastructure/BatchExecutionStateDomainService/BatchExecutionStateDomainService.cs, source/dotnet/wholesale-api/Batches/Batches.Infrastructure/BatchExecutionStateDomainService/IBatchExecutionStateDomainService.cs, source/dotnet/wholesale-api/Common/Common.csproj, source/dotnet/wholesale-api/Common/Security/FrontendUser.cs, source/dotnet/wholesale-api/Common/Security/FrontendUserProvider.cs, source/dotnet/wholesale-api/Infrastructure.Core/EnvironmentVariableHelper.cs, source/dotnet/wholesale-api/WebApi.IntegrationTests/Fixtures/WebApi/WebApiFactory.cs, source/dotnet/wholesale-api/WebApi/Startup.cs, source/dotnet/wholesale-api/WebApi/V3/Batch/BatchController.cs, source/dotnet/wholesale-api/WebApi/WebApi.csproj
=> refac: renamed Application to Common

source/dotnet/database-migration/DatabaseMigration.csproj, source/dotnet/database-migration/Scripts/202305260800_Add_BatchCompleted_PublishedTime.sql, source/dotnet/database-migration/Scripts/202305260800_Add_Batch_CreatedTime.sql, source/dotnet/wholesale-api/Batches/Batches.Application/BatchAggregate/Batch.cs, source/dotnet/wholesale-api/Batches/Batches.Application/BatchAggregate/BatchFactory.cs, source/dotnet/wholesale-api/Batches/Batches.Infrastructure/Persistence/Batches/BatchEntityConfiguration.cs, source/dotnet/wholesale-api/Batches/Batches.IntegrationTests/Batches.IntegrationTests.csproj, source/dotnet/wholesale-api/Batches/Batches.IntegrationTests/Infrastructure/Persistence/Batch/BatchRepositoryTests.cs, source/dotnet/wholesale-api/Batches/Batches.UnitTests/Application/Batches/CreateBatchHandlerTests.cs, source/dotnet/wholesale-api/Batches/Batches.UnitTests/Infrastructure/BatchAggregate/BatchBuilder.cs, source/dotnet/wholesale-api/Batches/Batches.UnitTests/Infrastructure/BatchAggregate/BatchTests.cs, source/dotnet/wholesale-api/Batches/Batches.UnitTests/Infrastructure/Calculations/DatabricksCalculatorJobParametersFactoryTests.cs, source/dotnet/wholesale-api/IntegrationEventPublishing/IntegrationEventPublishing.Application/BatchAggregate/CompletedBatch.cs, source/dotnet/wholesale-api/IntegrationEventPublishing/IntegrationEventPublishing.Application/UseCases/Mappers/CompletedBatchMapper.cs, source/dotnet/wholesale-api/IntegrationEventPublishing/IntegrationEventPublishing.Application/UseCases/PublishCalculationResultsHandler.cs, source/dotnet/wholesale-api/IntegrationEventPublishing/IntegrationEventPublishing.Infrastructure/IntegrationEventPublishing.Infrastructure.csproj, source/dotnet/wholesale-api/IntegrationEventPublishing/IntegrationEventPublishing.Infrastructure/Persistence/Batches/CompletedBatchEntityConfiguration.cs, source/dotnet/wholesale-api/IntegrationEventPublishing/IntegrationEventPublishing.Infrastructure/Persistence/Batches/CompletedBatchRepository.cs, source/dotnet/wholesale-api/IntegrationEventPublishing/IntegrationEventPublishing.IntegrationTests/Infrastructure/Persistence/Batches/CompletedBatchRepositoryTests.cs, source/dotnet/wholesale-api/IntegrationEventPublishing/IntegrationEventPublishing.IntegrationTests/IntegrationEventPublishing.IntegrationTests.csproj, source/dotnet/wholesale-api/Test.Core/Fixture/Database/WholesaleDatabaseFixture.cs, source/dotnet/wholesale-api/Test.Core/Fixture/Database/WholesaleDatabaseManager.cs, source/dotnet/wholesale-api/Test.Core/Test.Core.csproj
Add timestamp for creation time of batches as this may deviate from execution time start and scheduled time (eventually).
Add timestamp for published time (of integration events) of completed batches for deeper insights.
Moved and made these generic in order to be able to reuse across modules
* #972
=> feat: Add batch timestamps

source/dotnet/domain-tests/WebApiTests.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/CalculationResultClient/CalculationResultClient.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/CalculationResultClient/DatabricksSqlResponseParser.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.UnitTests/Infrastructure/CalculationResultClient/CalculationResultClientTests.cs
=> fix: retry http post if warehouse returns CANCELED

source/dotnet/wholesale-api/Batches/Batches.Application/BatchApplicationService.cs, source/dotnet/wholesale-api/Batches/Batches.Application/UseCases/UpdateBatchExecutionStateHandler.cs, source/dotnet/wholesale-api/Batches/Batches.Application/UseCases/UpdateExecutionStateHandler.cs, source/dotnet/wholesale-api/Batches/Batches.Application/Workers/UpdateBatchExecutionStateWorker.cs, source/dotnet/wholesale-api/Batches/Batches.Interfaces/IUpdateBatchExecutionStateHandler.cs, source/dotnet/wholesale-api/Batches/Batches.Interfaces/IUpdateExecutionStateHandler.cs, source/dotnet/wholesale-api/Batches/Batches.UnitTests/Application/Batches/BatchApplicationServiceTests.cs, source/dotnet/wholesale-api/Batches/Batches.UnitTests/Application/Batches/UpdateExecutionStateHandlerTests.cs, source/dotnet/wholesale-api/WebApi/Configuration/Modules/BatchesRegistration.cs
Splitting BatchApplicationService into handlers:
- StartCalculation <-- Moved
- UpdateExecutionState <-- Moving
- Search <-- Next
- Get
* #972
=> Move UpdateExecutionState

source/dotnet/wholesale-api/Batches/Batches.Application/UseCases/GetBatchHandler.cs, source/dotnet/wholesale-api/Batches/Batches.Interfaces/IGetBatchHandler.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Application/SettlementReports/SettlementReportClient.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.UnitTests/Infrastructure/SettlementReport/SettlementReportApplicationServiceTests.cs, source/dotnet/wholesale-api/WebApi.IntegrationTests/Fixtures/WebApi/WebApiFactory.cs, source/dotnet/wholesale-api/WebApi.IntegrationTests/WebApi/V3/BatchControllerTests.cs, source/dotnet/wholesale-api/WebApi.IntegrationTests/WebApi/V3/ProcessStepResultTests.cs, source/dotnet/wholesale-api/WebApi/Configuration/Modules/BatchesRegistration.cs, source/dotnet/wholesale-api/WebApi/V3/Batch/BatchController.cs, source/dotnet/wholesale-api/WebApi/V3/ProcessStepResult/ProcessStepResultController.cs
Splitting BatchApplicationService into handlers:
- StartCalculation <-- Moved
- UpdateExecutionState <-- Moved
- Search <-- Moved
- Get <-- Moving
* #972
=> move get to handler

.github/workflows/ci-dotnet.yml, .github/workflows/ci-orchestrator.yml
Part of:
https://app.zenhub.com/workspaces/the-outlaws-6193fe815d79fc0011e741b1/issues/gh/energinet-datahub/team-the-outlaws/1141
=> Bump use of GitHub actions/workflows to v11

source/dotnet/wholesale-api/Common/Workers/RepeatingWorker.cs, source/dotnet/wholesale-api/WebApi.UnitTests/Common/RepeatingWorkerTests.cs, source/dotnet/wholesale-api/WebApi.UnitTests/WebApi/V3/ProcessTypeMapperTests.cs
=> test: Add unit tests of  `RepeatingWorker`

source/dotnet/wholesale-api/Batches/Batches.Application/ICalculationInfrastructureService.cs, source/dotnet/wholesale-api/Batches/Batches.Application/Model/CalculationState.cs, source/dotnet/wholesale-api/Batches/Batches.Infrastructure/BatchState/BatchStateMapper.cs, source/dotnet/wholesale-api/Batches/Batches.Infrastructure/Calculations/CalculationEngineClient.cs, source/dotnet/wholesale-api/Batches/Batches.Infrastructure/Calculations/CalculationInfrastructureService.cs, source/dotnet/wholesale-api/Batches/Batches.Infrastructure/Calculations/ICalculationEngineClient.cs, source/dotnet/wholesale-api/Batches/Batches.UnitTests/Infrastructure/BatchExecutionStateDomainService/BatchExecutionStateDomainTests.cs, source/dotnet/wholesale-api/Batches/Batches.UnitTests/Infrastructure/BatchExecutionStateDomainService/BatchStateMapperTests.cs, source/dotnet/wholesale-api/Batches/Batches.UnitTests/Infrastructure/Calculations/DatabricksCalculatorJobRunnerTests.cs
=> move calculation state

source/dotnet/wholesale-api/WebApi.UnitTests/Common/RepeatingWorkerTests.cs
=> fix: Optimize speed and try fix flakiness of tests of `RepeatingWorker`

source/dotnet/domain-tests/WebApiTests.cs
…t again when switching to serverless warehouse
* #1023
=> test: skip settlement report domain test because of timeout

source/dotnet/wholesale-api/Events/Events.Application/CalculationResultPublishing/CalculationResultPublisher.cs, source/dotnet/wholesale-api/Events/Events.Application/CalculationResultPublishing/ICalculationResultCompletedFactory.cs, source/dotnet/wholesale-api/Events/Events.Application/CalculationResultPublishing/ICalculationResultPublisher.cs, source/dotnet/wholesale-api/Events/Events.Application/CalculationResultPublishing/Model/ProcessCompletedEventDto.cs, source/dotnet/wholesale-api/Events/Events.Application/CompletedBatches/CompletedBatch.cs, source/dotnet/wholesale-api/Events/Events.Application/CompletedBatches/ICompletedBatchRepository.cs, source/dotnet/wholesale-api/Events/Events.Application/UseCases/Factories/CompletedBatchFactory.cs, source/dotnet/wholesale-api/Events/Events.Application/UseCases/Factories/ICompletedBatchFactory.cs, source/dotnet/wholesale-api/Events/Events.Application/UseCases/PublishCalculationResultsHandler.cs, source/dotnet/wholesale-api/Events/Events.Application/UseCases/RegisterCompletedBatchesHandler.cs, source/dotnet/wholesale-api/Events/Events.Infrastructure/EventPublishers/CalculationResultCompletedToIntegrationEventFactory.cs, source/dotnet/wholesale-api/Events/Events.Infrastructure/IntegrationEvents/Factories/CalculationResultCompletedIntegrationEventFactory.cs, source/dotnet/wholesale-api/Events/Events.Infrastructure/IntegrationEvents/Factories/ICalculationResultCompletedIntegrationEventFactory.cs, source/dotnet/wholesale-api/Events/Events.Infrastructure/Persistence/Batches/CompletedBatchEntityConfiguration.cs, source/dotnet/wholesale-api/Events/Events.Infrastructure/Persistence/Batches/CompletedBatchRepository.cs, source/dotnet/wholesale-api/Events/Events.Infrastructure/Persistence/EventsDatabaseContext.cs, source/dotnet/wholesale-api/Events/Events.Infrastructure/Persistence/IEventsDatabaseContext.cs, source/dotnet/wholesale-api/Events/Events.IntegrationTests/Infrastructure/Persistence/Batches/CompletedBatchRepositoryTests.cs, source/dotnet/wholesale-api/Events/Events.UnitTests/Application/UseCases/Factories/CompletedBatchFactoryTests.cs, source/dotnet/wholesale-api/Events/Events.UnitTests/Application/UseCases/Processes/ProcessApplicationServiceTest.cs, source/dotnet/wholesale-api/Events/Events.UnitTests/Application/UseCases/PublishCalculationResultsHandlerTests.cs, source/dotnet/wholesale-api/Events/Events.UnitTests/Application/UseCases/RegisterCompletedBatchesHandlerTests.cs, source/dotnet/wholesale-api/Events/Events.UnitTests/Infrastructure/EventPublishers/CalculationResultCompletedToIntegrationEventFactoryTests.cs, source/dotnet/wholesale-api/Events/Events.UnitTests/Infrastructure/IntegrationEvents/Factories/CalculationResultReadyIntegrationEventFactoryTests.cs, source/dotnet/wholesale-api/Events/Events.UnitTests/Infrastructure/Persistence/Batches/CompletedBatchRepositoryTests.cs, source/dotnet/wholesale-api/WebApi/Configuration/Modules/EventsRegistration.cs
=> refac: Minor events clean up

source/dotnet/wholesale-api/Events/Events.Application/CalculationResultPublishing/CalculationResultPublisher.cs, source/dotnet/wholesale-api/Events/Events.UnitTests/Application/UseCases/Processes/CalculationResultPublisherTest.cs
=> feat: publish all current result types

source/dotnet/domain-tests/Clients/Wholesale/V3/ReadMe.md
=> doc: Create ReadMe for nswag

source/databricks/calculation-engine/package/balance_fixing.py, source/databricks/calculation-engine/package/schemas/output/aggregation_result_schema.py, source/databricks/calculation-engine/package/steps/aggregation/grid_loss_calculator.py, source/databricks/calculation-engine/package/steps/aggregation/transformations/aggregation_result_formatter.py, source/databricks/calculation-engine/package/steps/aggregation/transformations/apply_grid_loss_adjustment.py, source/databricks/calculation-engine/package/steps/aggregation/transformations/combine_master_data.py, source/databricks/calculation-engine/tests/integration/calculator/steps/aggregation/test_adjust_flex_consumption.py, source/databricks/calculation-engine/tests/integration/calculator/steps/aggregation/test_adjust_production.py, source/databricks/calculation-engine/tests/integration/calculator/steps/aggregation/test_aggregation_result_formatter.py, source/databricks/calculation-engine/tests/integration/calculator/steps/aggregation/test_combine_master_data.py, source/databricks/calculation-engine/tests/integration/calculator/steps/aggregation/test_negative_grid_loss.py, source/databricks/calculation-engine/tests/integration/calculator/steps/aggregation/test_positive_grid_loss.py
Use sum_quantity instead of negative and positive grid loss columns
* #1125 #1054
=> refac: remove negative and positive grid loss column

source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/SettlementReports/SettlementReportResultsCsvWriter.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.UnitTests/Infrastructure/SettlementReport/SettlementReportResultsCsvWriterTests.cs
=> fix SettlementReportResultsCsvWriter E02 and D01

source/databricks/calculation-engine/package/balance_fixing.py, source/databricks/calculation-engine/tests/integration/calculator/calculator_job/test_calculator_job_results.py
=> fix: flex consumption on es brp ga

source/databricks/calculation-engine/contracts/result-table-column-names.json, source/databricks/calculation-engine/tests/contract_utils.py, source/databricks/calculation-engine/tests/integration/calculator/file_writers/test_process_step_result_writer.py, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/SqlStatements/DeltaTableConstants/ResultColumnNames.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.UnitTests/DeltaTableContracts/ResultColumnNameTests.cs
=> test: extend contract test to include column types check

source/dotnet/wholesale-api/Batches/Batches.Infrastructure/Persistence/Batches/BatchRepository.cs, source/dotnet/wholesale-api/Batches/Batches.IntegrationTests/Infrastructure/Persistence/Batch/BatchRepositoryTests.cs, source/dotnet/wholesale-api/Batches/Batches.UnitTests/Application/Batches/BatchesClientTests.cs
=> fix: do not include batches with a start time that coincides with period end time of the search period

source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/CalculationResults/CalculationResultQueries.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.UnitTests/Infrastructure/CalculationResults/CalculationResultQueriesTests.cs
=> fix: send one message per calculation result (not per table row)

.github/workflows/ci-dotnet.yml
Spinoff on [#1199](https://app.zenhub.com/workspaces/the-outlaws-6193fe815d79fc0011e741b1/issues/gh/energinet-datahub/team-the-outlaws/1199) in Outlaws backlog:
=> Use .github v12

source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/SqlStatements/DatabricksSqlResponseParser.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.UnitTests/Infrastructure/SqlStatements/DatabricksSqlResponseParserTests.cs
=> fix: GetRowCount

.github/workflows/cd.yml
=> Change secret to variable

source/dotnet/wholesale-api/Events/Communication/Communication/Internal/IntegrationEvent.cs, source/dotnet/wholesale-api/Events/Communication/Communication/Internal/ServiceBusMessageFactory.cs, source/dotnet/wholesale-api/Events/Events.Infrastructure/IntegrationEvents/Factories/CalculationResultIntegrationEventFactory.cs, source/dotnet/wholesale-api/Events/Events.UnitTests/Infrastructure/EventPublishers/CalculationResultIntegrationEventFactoryTests.cs
=> feat: Adjust to updated ADR-008

source/dotnet/database-migration/DatabaseMigration.csproj, source/dotnet/domain-tests/DomainTests.csproj, source/dotnet/wholesale-api/Batches/Batches.Application/Batches.Application.csproj, source/dotnet/wholesale-api/Batches/Batches.Infrastructure/Batches.Infrastructure.csproj, source/dotnet/wholesale-api/Batches/Batches.IntegrationTests/Batches.IntegrationTests.csproj, source/dotnet/wholesale-api/Batches/Batches.Interfaces/Batches.Interfaces.csproj, source/dotnet/wholesale-api/Batches/Batches.UnitTests/Batches.UnitTests.csproj, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Application/CalculationResults.Application.csproj, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/CalculationResults.Infrastructure.csproj, source/dotnet/wholesale-api/CalculationResults/CalculationResults.IntegrationTests/CalculationResults.IntegrationTests.csproj, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Interfaces/CalculationResults.Interfaces.csproj, source/dotnet/wholesale-api/CalculationResults/CalculationResults.UnitTests/CalculationResults.UnitTests.csproj, source/dotnet/wholesale-api/Common/Common.csproj, source/dotnet/wholesale-api/Events/Communication/Communication/Communication.csproj, source/dotnet/wholesale-api/Events/Events.Application/Events.Application.csproj, source/dotnet/wholesale-api/Events/Events.Infrastructure/Events.Infrastructure.csproj, source/dotnet/wholesale-api/Events/Events.IntegrationTests/Events.IntegrationTests.csproj, source/dotnet/wholesale-api/Events/Events.UnitTests/Events.UnitTests.csproj, source/dotnet/wholesale-api/Test.Core/Test.Core.csproj, source/dotnet/wholesale-api/WebApi.IntegrationTests/WebApi.IntegrationTests.csproj, source/dotnet/wholesale-api/WebApi.UnitTests/WebApi.UnitTests.csproj, source/dotnet/wholesale-api/WebApi/WebApi.csproj
=> chore: Update NuGet packages

source/databricks/calculation-engine/package/grid_loss_responsible/grid_loss_responsible.py
=> refac: read grid loss responsibles from csv file

source/databricks/calculation-engine/package/grid_loss_responsible/grid_loss_responsible.py
This reverts commit cdff9ad6d94ca94abf544585c99f77020a71e2bf.
* #0000
=> Revert "refac: read grid loss responsibles from csv file (#1296)"

source/dotnet/domain-tests/Fixtures/AuthorizedClientFixtureOutput.cs
=> Add logging to domaintest

source/databricks/calculation-engine/package/__init__.py, source/databricks/calculation-engine/package/calculator_args.py, source/databricks/calculation-engine/package/calculator_job.py, source/databricks/calculation-engine/tests/integration/calculator/calculator_job/conftest.py, source/databricks/calculation-engine/tests/integration/calculator/calculator_job/test_calculator_args.py, source/databricks/calculation-engine/tests/integration/calculator/calculator_job/test_calculator_job.py
=> refac: move argument handling to calculator_args.py

source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/SettlementReports/SettlementReportSqlStatementFactory.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.UnitTests/Infrastructure/SettlementReport/SettlementReportSqlStatementFactoryTests.cs
=> fix: add total consumption to settlement report for grid access providers

source/databricks/calculation-engine/package/__init__.py
=> fix: include execute in init file

source/dotnet/wholesale-api/Events/Communication/Communication/Internal/HostedServiceReadinessMonitor.cs, source/dotnet/wholesale-api/Events/Communication/Communication/Internal/IHostedServiceReadinessMonitor.cs, source/dotnet/wholesale-api/Events/Communication/Communication/Internal/OutboxSenderTrigger.cs, source/dotnet/wholesale-api/Events/Communication/Communication/Internal/RepeatingTrigger.cs, source/dotnet/wholesale-api/Events/Communication/Communication/Registration.cs, source/dotnet/wholesale-api/WebApi/HealthChecks/DataLakeHealthChecksBuilderExtensions.cs, source/dotnet/wholesale-api/WebApi/HealthChecks/HostedServicesHealthCheck.cs, source/dotnet/wholesale-api/WebApi/Startup.cs
=> feat: Add health check of `OutboxSenderTrigger` hosted service

source/dotnet/wholesale-api/Events/Communication/Communication/Internal/HostedServiceReadinessMonitor.cs, source/dotnet/wholesale-api/Events/Communication/Communication/Internal/IHostedServiceReadinessMonitor.cs, source/dotnet/wholesale-api/Events/Communication/Communication/Internal/RepeatingTrigger.cs
=> fix: Fix hosted services health check

.github/PULL_REQUEST_TEMPLATE.md
=> doc: Update PULL_REQUEST_TEMPLATE.md

source/dotnet/wholesale-api/Batches/Batches.Application/UseCases/CreateBatchHandler.cs, source/dotnet/wholesale-api/Batches/Batches.Application/UseCases/StartCalculationHandler.cs, source/dotnet/wholesale-api/WebApi/Logging/LoggingScopeMiddleware.cs, source/dotnet/wholesale-api/WebApi/Logging/Registration.cs, source/dotnet/wholesale-api/WebApi/Logging/RootLoggingScope.cs, source/dotnet/wholesale-api/WebApi/Startup.cs
=> feat: Add domain name to all trace logs

.github/workflows/ci-dotnet.yml
https://app.zenhub.com/workspaces/the-outlaws-6193fe815d79fc0011e741b1/issues/gh/energinet-datahub/team-the-outlaws/1201
=> Use new tenant variable

source/databricks/calculation-engine/package/steps/aggregation/transformations/aggregation_result_formatter.py, source/databricks/calculation-engine/package/steps/wholesale/fee_calculators.py, source/databricks/calculation-engine/package/steps/wholesale/subscription_calculators.py, source/databricks/calculation-engine/tests/datamigration/test_migration_scripts.py, source/databricks/calculation-engine/tests/integration/calculator/calculator_job/conftest.py, source/databricks/calculation-engine/tests/integration/calculator/calculator_job/test_calculator_job.py, source/databricks/calculation-engine/tests/integration/calculator/steps/aggregation/test_aggregation_result_formatter.py, source/databricks/calculation-engine/tests/integration/calculator/steps/aggregation/test_flex_consumption_ga_brp_es.py, source/databricks/calculation-engine/tests/integration/calculator/steps/aggregation/test_negative_grid_loss.py, source/databricks/calculation-engine/tests/integration/calculator/steps/aggregation/test_net_exchange_grid_area_aggregation.py, source/databricks/calculation-engine/tests/integration/calculator/steps/aggregation/test_net_exchange_neighbour.py, source/databricks/calculation-engine/tests/integration/calculator/steps/aggregation/test_non_profiled_consumption_ga_brp_es.py, source/databricks/calculation-engine/tests/integration/calculator/steps/aggregation/test_positive_grid_loss.py, source/databricks/calculation-engine/tests/integration/calculator/steps/aggregation/test_production_ga_brp_es.py, source/databricks/calculation-engine/tests/integration/calculator/steps/wholesale/conftest.py, source/databricks/calculation-engine/tests/integration/calculator/steps/wholesale/test_dataframe_creators.py, source/databricks/calculation-engine/tests/integration/calculator/steps/wholesale/test_wholesale_initializer.py
=> fix: Use correct module import

source/databricks/calculation-engine/tests/integration/calculator/calculator_job/test_calculator_job.py
=> test: Verify that schema of test input data matches published contracts

source/databricks/calculation-engine/tests/integration/calculator_job/conftest.py, source/databricks/calculation-engine/tests/integration/calculator_job/test_calculator_job_balance_fixing_results.py, source/databricks/calculation-engine/tests/integration/calculator_job/test_calculator_job_wholesale_fixing_results.py
=> test: Wholesale results are written to delta table

source/databricks/calculation-engine/package/codelists/time_series_type.py
=> Add comment to time series type

source/dotnet/wholesale-api/Events/Events.Application/InboxEvents/AggregatedTimeSeriesRequest.cs, source/dotnet/wholesale-api/Events/Events.Application/InboxEvents/AggregationPerBalanceResponsiblePartyPerGridArea.cs, source/dotnet/wholesale-api/Events/Events.Application/InboxEvents/AggregationPerEnergySupplierPerBalanceResponsiblePartyPerGridArea.cs, source/dotnet/wholesale-api/Events/Events.Application/InboxEvents/AggregationPerEnergySupplierPerGridArea.cs, source/dotnet/wholesale-api/Events/Events.Application/InboxEvents/AggregationPerGridArea.cs, source/dotnet/wholesale-api/Events/Events.Application/InboxEvents/IAggregatedTimeSeriesMessageFactory.cs, source/dotnet/wholesale-api/Events/Events.Application/InboxEvents/IAggregatedTimeSeriesRequestMessageParser.cs, source/dotnet/wholesale-api/Events/Events.Application/InboxEvents/Period.cs, source/dotnet/wholesale-api/Events/Events.Application/InboxEvents/TimeSeriesType.cs, source/dotnet/wholesale-api/Events/Events.Application/UseCases/AggregatedTimeSeriesRequestHandler.cs, source/dotnet/wholesale-api/Events/Events.Infrastructure/Events.Infrastructure.csproj, source/dotnet/wholesale-api/Events/Events.Infrastructure/InboxEvents/AggregatedTimeSeriesMessageFactory.cs, source/dotnet/wholesale-api/Events/Events.Infrastructure/InboxEvents/AggregatedTimeSeriesRequest.proto, source/dotnet/wholesale-api/Events/Events.Infrastructure/InboxEvents/AggregatedTimeSeriesRequestMessageParser.cs, source/dotnet/wholesale-api/Events/Events.UnitTests/Application/UseCases/ProcessAggregatedTimeSeriesRequestHandlerTests.cs, source/dotnet/wholesale-api/Events/Events.UnitTests/Events.UnitTests.csproj, source/dotnet/wholesale-api/WebApi/Configuration/Modules/EventsRegistration.cs
Handling AggregatedTimeSeriesRequest message service bus coming from EDI. 
Next: The next step will be to extend ICalculationResultQueries with a new method to fetch the result based on the requested data. 
https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-phoenix/60
* #0000
=> feat: receiving aggregated time series request sevice bus message

source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/CalculationResults/CalculationResultQueries.cs, source/dotnet/wholesale-api/Common/Logging/LoggerExtensions.cs, source/dotnet/wholesale-api/Events/Events.Application/UseCases/AggregatedTimeSeriesRequestHandler.cs, source/dotnet/wholesale-api/Events/Events.Application/Workers/AggregatedTimeSeriesServiceBusWorker.cs, source/dotnet/wholesale-api/WebApi.IntegrationTests/Fixtures/TestCommon/Fixture/WebApi/WholesaleWebApiFixture.cs, source/dotnet/wholesale-api/WebApi/Startup.cs
=> feat: added healt checks on edi and wholesale queues for inbox events

source/dotnet/wholesale-api/Events/Events.Application/Events.Application.csproj, source/dotnet/wholesale-api/Events/Events.Application/Workers/AggregatedTimeSeriesServiceBusWorker.cs, source/dotnet/wholesale-api/WebApi/Startup.cs, source/dotnet/wholesale-api/WebApi/WebApi.csproj
=> refac: Update Logging packages

source/databricks/calculation-engine/contracts/enums/basis-data-type.json, source/databricks/calculation-engine/contracts/enums/charge-quality.json, source/databricks/calculation-engine/contracts/enums/charge-resolution.json, source/databricks/calculation-engine/contracts/enums/charge-type.json, source/databricks/calculation-engine/contracts/enums/charge-unit.json, source/databricks/calculation-engine/contracts/enums/metering-point-resolution.json, source/databricks/calculation-engine/tests/contracts/test_enum_contracts.py
* https://app.zenhub.com/workspaces/mandalorian-5fd22a1a59e4740018f5ab5a/issues/gh/energinet-datahub/green-energy-hub/470
=> feat: Add missing enum contracts and corresponding python tests

source/databricks/calculation-engine/tests/integration/calculator_job/test_calculator_job_wholesale_fixing_results.py
* https://app.zenhub.com/workspaces/mandalorian-5fd22a1a59e4740018f5ab5a/issues/gh/energinet-datahub/green-energy-hub/470
=> test: Assert wholesale result types have been produced

source/databricks/calculation-engine/package/calculation/calculation.py
=> fix: missing correction settlement on wholesale

source/databricks/calculation-engine/package/calculation/wholesale/__init__.py, source/databricks/calculation-engine/package/calculation/wholesale/charges_reader.py, source/databricks/calculation-engine/package/calculation/wholesale/wholesale_calculation.py, source/databricks/calculation-engine/package/calculation/wholesale/wholesale_initializer.py, source/databricks/calculation-engine/tests/calculation/wholesale/test_charges_reader.py, source/databricks/calculation-engine/tests/calculation/wholesale/test_fee_calculators.py, source/databricks/calculation-engine/tests/calculation/wholesale/test_subscription_calculators.py, source/databricks/calculation-engine/tests/calculation/wholesale/test_wholesale_initializer.py, source/databricks/calculation-engine/tests/helpers/test_schemas/charges_with_price_and_links_schema.py
* https://app.zenhub.com/workspaces/mandalorian-5fd22a1a59e4740018f5ab5a/issues/gh/energinet-datahub/green-energy-hub/470
=> refac: Segregate charges data frame

README.md
* https://app.zenhub.com/workspaces/mandalorian-5fd22a1a59e4740018f5ab5a/issues/gh/energinet-datahub/team-mandalorian/31
=> doc: Add C4 to README.md

source/dotnet/wholesale-api/CalculationResults/CalculationResults.IntegrationTests/Fixtures/DatabricksSchemaManager.cs
=> fix: quick fix deltalake migration unstable

source/dotnet/wholesale-api/Batches/Batches.Application/Batches.Application.csproj, source/dotnet/wholesale-api/Common/Common.csproj, source/dotnet/wholesale-api/Events/Events.Application/Events.Application.csproj, source/dotnet/wholesale-api/Events/Events.Infrastructure/Events.Infrastructure.csproj, source/dotnet/wholesale-api/WebApi/WebApi.csproj
I could not find a title prefix that matches "updating dependency", so I chose "refac:".
Part of:
https://app.zenhub.com/workspaces/the-outlaws-6193fe815d79fc0011e741b1/issues/gh/energinet-datahub/team-the-outlaws/1435
=> refac: Bump App package

source/dotnet/wholesale-api/Edi/Validation/ValidationError.cs
split validation error text for max 1 month period and max 3 years back
=> fix: validation error messages

source/dotnet/wholesale-api/Edi.UnitTests/AggregatedTimeSeriesRequestHandlerTests.cs, source/dotnet/wholesale-api/Edi.UnitTests/AggregatedTimeSeriesRequestRejectedMessageFactoryTests.cs, source/dotnet/wholesale-api/Edi.UnitTests/Builders/AggregatedTimeSeriesRequestBuilder.cs, source/dotnet/wholesale-api/Edi.UnitTests/Validators/AggregatedTimeSeriesRequestValidatorTests.cs, source/dotnet/wholesale-api/Edi.UnitTests/Validators/EnergySupplierValidatorTest.cs, source/dotnet/wholesale-api/Edi.UnitTests/Validators/MeteringPointTypeValidatorTests.cs, source/dotnet/wholesale-api/Edi.UnitTests/Validators/PeriodValidatorTests.cs, source/dotnet/wholesale-api/Edi.UnitTests/Validators/SettlementMethodValidatorTest.cs, source/dotnet/wholesale-api/Edi.UnitTests/Validators/TimeSeriesTypeValidatorTests.cs, source/dotnet/wholesale-api/Edi/AggregatedTimeSeriesRequestHandler.cs, source/dotnet/wholesale-api/Edi/EdiRegistration.cs, source/dotnet/wholesale-api/Edi/Validation/AggregatedTimeSerie/Rules/EnergySupplierValidationRule.cs, source/dotnet/wholesale-api/Edi/Validation/AggregatedTimeSerie/Rules/MeteringPointTypeValidationRule.cs, source/dotnet/wholesale-api/Edi/Validation/AggregatedTimeSerie/Rules/PeriodValidationRule.cs, source/dotnet/wholesale-api/Edi/Validation/AggregatedTimeSerie/Rules/SettlementMethodValidationRule.cs, source/dotnet/wholesale-api/Edi/Validation/AggregatedTimeSerie/Rules/TimeSeriesTypeValidationRule.cs, source/dotnet/wholesale-api/Edi/Validation/ValidationError.cs
Align validation rules for aggregated measure data
=> refac: align validation rules for aggregated time serie request

source/dotnet/wholesale-api/CalculationResults/CalculationResults.UnitTests/Infrastructure/SqlStatements/Mappers/WholesaleResult/ChargeResolutionMapperTests.cs
Added 2 charge resolution mapper tests (contract tests).
https://app.zenhub.com/workspaces/mandalorian-5fd22a1a59e4740018f5ab5a/issues/gh/energinet-datahub/green-energy-hub/476
=> test: Added tests of charge resolution mapper

source/dotnet/wholesale-api/Edi/Contracts/AggregatedTimeSeriesRequest.proto
=> refac: Update AggregatedTimeSeriesRequest.proto

.github/workflows/ci-databricks.yml
https://github.com/Energinet-DataHub/opengeh-wholesale/pull/1555
=> refac: calculation_engine

source/databricks/calculation_engine/contracts/enums/quantity-quality.json, source/databricks/calculation_engine/package/codelists/quantity_quality.py, source/databricks/calculation_engine/package/datamigration/migration_scripts/202310241300_Alter_energy_result_quality_to_array.sql, source/databricks/calculation_engine/package/datamigration/migration_scripts/202310241300_Remove_and_disallow_quality_incomplete.sql, source/databricks/calculation_engine/tests/datamigration/test_energy_results_migrations.py, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/SqlStatements/Mappers/QuantityQualityMapper.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Interfaces/CalculationResults/Model/QuantityQuality.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.UnitTests/Infrastructure/SqlStatements/Mappers/QuantityQualityMapperTests.cs, source/dotnet/wholesale-api/Edi.UnitTests/Mappers/QuantityQualityMapperTests.cs, source/dotnet/wholesale-api/Edi/Mappers/QuantityQualityMapper.cs, source/dotnet/wholesale-api/Events/Events.Infrastructure/IntegrationEvents/Mappers/AmountPerChargeResultProducedV1/QuantityQualityMapper.cs, source/dotnet/wholesale-api/Events/Events.Infrastructure/IntegrationEvents/Mappers/CalculationResultCompleted/QuantityQualityMapper.cs, source/dotnet/wholesale-api/Events/Events.Infrastructure/IntegrationEvents/Mappers/EnergyResultProducedV1/QuantityQualityMapper.cs, source/dotnet/wholesale-api/Events/Events.UnitTests/Infrastructure/IntegrationEvents/Mappers/AmountPerChargeResultProducedV1/QuantityQualityMapperTests.cs, source/dotnet/wholesale-api/Events/Events.UnitTests/Infrastructure/IntegrationEvents/Mappers/CalculationResultCompleted/QuantityQualityMapperTests.cs, source/dotnet/wholesale-api/Events/Events.UnitTests/Infrastructure/IntegrationEvents/Mappers/EnergyResultProducedV1/QuantityQualityMapperTests.cs
Quality "incomplete" is solely related to CIM/ebIX communication and is therefor removed from wholesale.
=> feat: Remove quality `incomplete`

source/databricks/calculation_engine/package/calculation/energy/aggregators.py, source/databricks/calculation_engine/package/calculation/energy/exchange_aggregators.py, source/databricks/calculation_engine/package/calculation/energy/schemas/basis_data_time_series_points_schema.py, source/databricks/calculation_engine/package/calculation/energy/schemas/time_series_quarter_points_schema.py, source/databricks/calculation_engine/package/calculation/energy/transformations/aggregate_sum_and_quality.py, source/databricks/calculation_engine/package/calculation/preparation/transformations/enriched_time_series.py, source/databricks/calculation_engine/package/calculation/preparation/transformations/hour_to_quarter.py, source/databricks/calculation_engine/package/constants/colname.py, source/databricks/calculation_engine/tests/calculation/energy/aggregators/test_flex_consumption_ga_brp_es.py, source/databricks/calculation_engine/tests/calculation/energy/aggregators/test_non_profiled_consumption_ga_brp_es.py, source/databricks/calculation_engine/tests/calculation/energy/aggregators/test_production_ga_brp_es.py, source/databricks/calculation_engine/tests/calculation/preparation/transformations/test_get_enriched_time_series_points_df.py, source/databricks/calculation_engine/tests/calculation/preparation/transformations/test_transform_hour_to_quarter.py
Fix schema of python function `get_basis_data_time_series_points_df`.
In addition, a few simple clean-ups have been done too.
=> feat: Fix schema of `get_basis_data_time_series_points_df`

source/databricks/calculation_engine/package/calculation/energy/transformations/aggregation_result_formatter.py
Temporary workaround to resolve broken domain tests in order to unblock deployments.
=> fix: Temp workaround for null qualities

source/databricks/calculation_engine/package/calculation/energy/energy_results.py, source/databricks/calculation_engine/package/calculation/preparation/quarterly_metering_point_time_series.py, source/databricks/calculation_engine/package/common/data_frame_wrapper.py
Make wrapped data frame instance immutable.
Make code to add nullable columns generic and reusable for alle typed data frames.
=> refac: Improve typed data frame concept

source/dotnet/wholesale-api/Events/Events.Infrastructure/IntegrationEvents/EventProviders/WholesaleResultEventProvider.cs, source/dotnet/wholesale-api/Events/Events.Infrastructure/IntegrationEvents/Factories/AmountPerChargeResultProducedV1Factory.cs, source/dotnet/wholesale-api/Events/Events.Infrastructure/IntegrationEvents/Factories/IAmountPerChargeResultProducedV1Factory.cs, source/dotnet/wholesale-api/Events/Events.Infrastructure/IntegrationEvents/Factories/IMonthlyAmountPerChargeResultProducedV1Factory.cs, source/dotnet/wholesale-api/Events/Events.Infrastructure/IntegrationEvents/Factories/MonthlyAmountPerChargeResultProducedV1Factory.cs, source/dotnet/wholesale-api/Events/Events.UnitTests/Fixtures/WholesaleResultBuilder.cs, source/dotnet/wholesale-api/Events/Events.UnitTests/Infrastructure/IntegrationEvents/EventProviders/WholesaleResultEventProviderTests.cs, source/dotnet/wholesale-api/Events/Events.UnitTests/Infrastructure/IntegrationEvents/Factories/AmountPerChargeResultProducedV1FactoryTests.cs, source/dotnet/wholesale-api/Events/Events.UnitTests/Infrastructure/IntegrationEvents/Factories/MonthlyAmountPerChargeResultProducedV1FactoryTests.cs
Adding unit tests, but also modifying factory classes to have a CanCreate method that can be used from WholesaleResultEventProvider
=> test: Unit test WholesaleResultEventProvider and event factory classes

.github/PULL_REQUEST_TEMPLATE.md
Added check to PR template so we remember to update the Event catalogue if relevant.
=> Added check to PR template

.docker/Dockerfile
Reference:
https://app.zenhub.com/workspaces/mandalorian-5fd22a1a59e4740018f5ab5a/issues/gh/energinet-datahub/team-mandalorian/33
=> build: Added Python package azure-monitor-opentelemetry to docker file

.docker/Dockerfile
Add the library in order to use in another PR to intercept selected functions in the `logging` library.
=> feat: Add python `intercepts` library

source/dotnet/wholesale-api/Batches/Batches.Application/GridArea/IGridAreaOwnerRepository.cs, source/dotnet/wholesale-api/Batches/Batches.Infrastructure/Persistence/GridArea/GridAreaOwnerRepository.cs, source/dotnet/wholesale-api/Batches/Batches.IntegrationTests/Infrastructure/Persistence/GridArea/GridAreaOwnerRepositoryTests.cs
We should return a validation error if grid area owner doesn't exists. 
- the validation error is impl in next pr (https://github.com/Energinet-DataHub/opengeh-wholesale/pull/1698)
=> refac: returns null if grid area owner doesn't exists

source/dotnet/wholesale-api/Events/Events.Application/Workers/AggregatedTimeSeriesServiceBusWorker.cs, source/dotnet/wholesale-api/Events/Events.Application/Workers/ReceiveIntegrationEventServiceBusWorker.cs, source/dotnet/wholesale-api/Events/Events.Application/Workers/ServiceBusWorker.cs, source/dotnet/wholesale-api/WebApi/Properties/launchSettings.json
=> fix: integration event used inbox event configuration

source/dotnet/wholesale-api/Edi.UnitTests/Validators/AggregatedTimeSeriesRequestValidatorTests.cs, source/dotnet/wholesale-api/Edi/EdiRegistration.cs
=> fix: missing ioc config of grid area validation

.docker/Dockerfile
Needed for upcoming PR with integration test of logging to Azure Monitor.
=> feat: Add azure-keyvault-secrets to Docker

source/dotnet/domain-tests/Features/Databricks/CalculationJobScenario.cs, source/dotnet/domain-tests/Features/Databricks/Fixtures/CalculationJobScenarioFixture.cs
Update our Calculation Job performance test by reducing the wait and max duration, now that the calculation is much faster.
=> refac: Reduce calculation job wait and max duration

source/databricks/calculation_engine/package/calculation_input/table_reader.py
=> refac: Test tables with different Z Ordering

source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/CalculationResults/Statements/AggregatedTimeSeriesQueryStatement.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.IntegrationTests/Infrastructure/RequestCalculationResult/AggregatedTimeSeriesQueriesTests.cs
fix
https://adb-2347415096653272.12.azuredatabricks.net/sql/history?lookupKey=CiQwMWVlOThjOC1hNTRlLTFiMTctYTY0Yi03MDE5YTk1OGU4MmQQt%2FWW6cUxGhAyZDg4ZjQzZWUzMmUzMmMzIILB6LKAquoL&o=2347415096653272&preset=d_last_8_hours&status=FAILED
=> fix: syntax error when query requested calculation result

source/dotnet/domain-tests/Fixtures/DatabricksClientExtensions.cs
=> Set Job list limit to 100

.docker/entrypoint.sh, source/databricks/calculation_engine/tests/conftest.py
Example run where I forced an error, which was detected: https://github.com/Energinet-DataHub/opengeh-wholesale/actions/runs/7183607513?pr=1738
=> refac: When exception occur in python tests then fail

source/dotnet/domain-tests/Fixtures/Identity/B2CUserTokenConfiguration.cs
Part of:
https://app.zenhub.com/workspaces/mandalorian-5fd22a1a59e4740018f5ab5a/issues/gh/energinet-datahub/opengeh-wholesale/1485
=> refac: Refactor token configuration to support old and new environments

source/databricks/calculation_engine/package/calculation/calculation.py, source/databricks/calculation_engine/package/calculation/energy/energy_calculation.py, source/databricks/calculation_engine/package/calculation/wholesale/wholesale_calculation.py, source/databricks/calculation_engine/package/calculation_output/basis_data_writer.py, source/databricks/calculation_engine/package/calculation_output/energy_calculation_result_writer.py, source/databricks/calculation_engine/package/calculator_job.py, source/databricks/calculation_engine/package/infrastructure/logging_configuration.py, source/databricks/calculation_engine/tests/calculator_job/test_start.py
=> feat: Use spans for operation duration insights

.github/workflows/packages-publish.yml, source/dotnet/wholesale-integration-events-package/Contracts.Documentation/release-notes/release-notes.md, source/dotnet/wholesale-integration-events-package/Contracts/Contracts.csproj
Ref: https://app.zenhub.com/workspaces/the-outlaws-6193fe815d79fc0011e741b1/issues/gh/energinet-datahub/team-the-outlaws/1813
=> Remove code_coverage_flags

source/dotnet/subsystem-tests/Features/Calculations/WholesaleFixingCalculationScenario.cs, source/dotnet/wholesale-api/Batches/Batches.Application/Batches.Application.csproj, source/dotnet/wholesale-api/Common.Infrastructure/Common.Infrastructure.csproj, source/dotnet/wholesale-api/Events/Events.Application/Workers/AggregatedTimeSeriesServiceBusWorker.cs, source/dotnet/wholesale-api/Events/Events.Application/Workers/ReceiveIntegrationEventServiceBusWorker.cs, source/dotnet/wholesale-api/Events/Events.Application/Workers/ServiceBusWorker.cs, source/dotnet/wholesale-api/WebApi/WebApi.csproj
Part of:
https://app.zenhub.com/workspaces/mandalorian-5fd22a1a59e4740018f5ab5a/issues/gh/energinet-datahub/team-mandalorian/38
=> Cleanup assignment of service name

.github/actions/dotnet-tests-prepare-outputs/action.yml, .github/workflows/ci-dotnet.yml, .github/workflows/packages-publish.yml, source/dotnet/Directory.Build.props, source/dotnet/global.json, source/dotnet/wholesale-api/WebApi/V3/SettlementReport/SettlementReportController.cs, source/dotnet/wholesale-integration-events-package/Contracts.Documentation/release-notes/release-notes.md, source/dotnet/wholesale-integration-events-package/Contracts/Contracts.csproj
Requires infrastructure PR: https://github.com/Energinet-DataHub/dh3-infrastructure/pull/981
Part of:
https://app.zenhub.com/workspaces/mandalorian-5fd22a1a59e4740018f5ab5a/issues/gh/energinet-datahub/team-mandalorian/163
=> refac: Upgrade to net8.0

source/dotnet/subsystem-tests/Features/Calculations/Fixtures/CalculationScenarioFixture.cs
A missing ";" caused the problem.
=> fix: Failing domain test

source/dotnet/subsystem-tests/Features/Calculations/TestData/Positive_gridLoss 543.csv
Missing column header in test CVS file added.
=> fix: Subsystem test failed

source/databricks/calculation_engine/package/calculation/CalculationResults.py, source/databricks/calculation_engine/package/calculation/calculation.py
Step 1: Return basis data from the calculation.
Note: The basis data returned is not in the final form as further transformation is done in the basis data writer. This will be refactored in another PR.
=> refac: Calculation results as output - step 1

source/databricks/calculation_engine/package/calculation/CalculationResults.py, source/databricks/calculation_engine/package/calculation/calculation.py, source/databricks/calculation_engine/package/calculation/energy/energy_calculation.py
Step 1: Return energy results from the calculation (instead of writing them inside the calculation).
Note: The energy results returned are not in the final form as further transformation is done in the energy results writer. This will be refactored in another PR.
=> refac: Calculation results as output - step 2

source/databricks/calculation_engine/package/calculation/CalculationResults.py, source/databricks/calculation_engine/package/calculation/calculation.py, source/databricks/calculation_engine/package/calculation/wholesale/wholesale_calculation.py, source/databricks/calculation_engine/tests/calculation/wholesale/test_wholesale_calculation.py
Step 3: Return wholesale results from the calculation (instead of writing them inside the calculation).
Note: The wholesale results returned are not in the final form as further transformation is done in the results writer. This will be refactored in another PR.
=>  refac: Calculation results as output - step 3

source/dotnet/subsystem-tests/Features/SettlementReport/SettlementReportScenario.cs
One single rename of "process type" in test method name.
Part of:
https://app.zenhub.com/workspaces/mandalorian-5fd22a1a59e4740018f5ab5a/issues/gh/energinet-datahub/opengeh-wholesale/1280
=> Rename test method

source/dotnet/wholesale-api/Edi.UnitTests/Calculations/LatestCalculationsForPeriodTests.cs, source/dotnet/wholesale-api/Edi/Calculations/LatestCalculationsForPeriod.cs
=> fix: LatestCalculationsForPeriod when calculation period is larger than requested period

source/databricks/calculation_engine/package/calculation/CalculationResults.py, source/databricks/calculation_engine/package/calculation/calculation.py, source/databricks/calculation_engine/package/calculation/energy/energy_results.py, source/databricks/calculation_engine/package/calculation/output/basis_data.py, source/databricks/calculation_engine/package/calculation/output/energy_results.py, source/databricks/calculation_engine/package/calculation/output/wholesale_results.py
The purpose of this PR is to move the write-code to separate modules to reduce the size/complexity of calculation.py.
=> refac: Segregate calculation write code into modules

source/dotnet/wholesale-api/Events/Events.Infrastructure/IntegrationEvents/AmountPerChargeResultProducedV1/AmountPerChargeResultProducedV1.cs, source/dotnet/wholesale-api/Events/Events.Infrastructure/IntegrationEvents/AmountPerChargeResultProducedV1/Factories/AmountPerChargeResultProducedV1Factory.cs, source/dotnet/wholesale-api/Events/Events.Infrastructure/IntegrationEvents/AmountPerChargeResultProducedV1/Protos/amount_per_charge_result_produced_v1.proto, source/dotnet/wholesale-api/Events/Events.UnitTests/Infrastructure/IntegrationEvents/AmountPerChargeResultProducedV1/Factories/AmountPerChargeResultProducedV1FactoryTests.cs, source/dotnet/wholesale-integration-events-package/Contracts.Documentation/release-notes/release-notes.md, source/dotnet/wholesale-integration-events-package/Contracts.Tests/AmountPerChargeResultProducedV1Tests.cs, source/dotnet/wholesale-integration-events-package/Contracts/Contracts.csproj
=> feat: add calculation version to amount per charge result produced event

source/databricks/calculation_engine/setup.py
Several tests failed because of inccorect urllib3 version.
=> fix: Updated urllib3 to version 2.2.1

.docker/requirements.txt, .github/workflows/detect-changes.yml, source/databricks/calculation_engine/setup.py
To get around bug: https://github.com/databricks/databricks-cli/issues/634
which causes CD to fail https://github.com/Energinet-DataHub/dh3-environments/actions/runs/8009071371
=> Bump databricks CLI version

.docker/requirements.txt
Pinned versions in requirements.txt
=> Pinned code dependencies

source/dotnet/wholesale-api/WebApi.IntegrationTests/CompositionRootTests.cs
Part of:
https://app.zenhub.com/workspaces/mandalorian-5fd22a1a59e4740018f5ab5a/issues/gh/energinet-datahub/team-mandalorian/219
=> refac: Avoid using environment variables in composite root test

source/databricks/calculation_engine/package/calculation/wholesale/tariff_calculators.py, source/databricks/calculation_engine/tests/calculation/output/test_wholesale_storage_model_factory.py, source/databricks/calculation_engine/tests/calculation/wholesale/test_tariff_calculators.py
Counting charges is only relevant for fees and subscriptions
=> refac: No need to count charges for tariffs

source/dotnet/wholesale-api/Calculations/Calculations.Infrastructure/Calculations.Infrastructure.csproj, source/dotnet/wholesale-api/Common.Infrastructure/Common.Infrastructure.csproj
Update Databricks to reduce health check exceptions.
=> fix: Update Databricks to reduce health check exceptions

source/dotnet/subsystem-tests/Clients/Wholesale/V3/WholesaleClient.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/SqlStatements/Mappers/MeteringPointTypeMapper.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.UnitTests/Infrastructure/SqlStatements/Mappers/MeteringPointTypeMapperTests.cs, source/dotnet/wholesale-api/Calculations/Calculations.UnitTests/Calculations.UnitTests.csproj, source/dotnet/wholesale-api/Calculations/Calculations.UnitTests/Infrastructure/Calculations/DatabricksCalculatorJobParametersFactoryTests.cs, source/dotnet/wholesale-api/Calculations/Calculations.UnitTests/Interfaces/CalculationResults/Model/MeteringPointTypeTests.cs, source/dotnet/wholesale-api/Events/Events.Infrastructure/IntegrationEvents/AmountPerChargeResultProducedV1/AmountPerChargeResultProducedV1.cs, source/dotnet/wholesale-api/Events/Events.Infrastructure/IntegrationEvents/AmountPerChargeResultProducedV1/Mappers/MeteringPointTypeMapper.cs, source/dotnet/wholesale-api/Events/Events.Infrastructure/IntegrationEvents/AmountPerChargeResultProducedV1/Protos/amount_per_charge_result_produced_v1.proto, source/dotnet/wholesale-api/Events/Events.UnitTests/Infrastructure/IntegrationEvents/AmountPerChargeResultProducedV1/Mappers/MeteringPointTypeMapperTests.cs, source/dotnet/wholesale-integration-events-package/Contracts.Documentation/release-notes/release-notes.md, source/dotnet/wholesale-integration-events-package/Contracts.Tests/AmountPerChargeResultProducedV1Tests.cs, source/dotnet/wholesale-integration-events-package/Contracts/Contracts.csproj
Add missing metering point type mappings
=> feat: Add missing metering point type mappings

source/dotnet/subsystem-tests/Features/Calculations/WholesaleFixingCalculationScenario.cs
=> feat: Update event counts in subsystem tests

source/databricks/calculation_engine/package/calculation/calculation.py
Unit tests are not suitable for this change. A logic test is planned.
=> feat: Add grid loss to basis data

source/dotnet/wholesale-api/Edi.UnitTests/Validators/WholesaleServicesRequest/PeriodValidationRuleTests.cs, source/dotnet/wholesale-api/Edi.UnitTests/Validators/WholesaleServicesRequest/WholesaleServicesRequestValidatorTests.cs, source/dotnet/wholesale-api/Edi/Validation/WholesaleServicesRequest/Rules/PeriodValidationRule.cs
=> feat: Validate endpoints of period for wholeesale service requests

source/databricks/calculation_engine/package/calculation/calculation.py, source/databricks/calculation_engine/package/calculation/energy/calculated_grid_loss.py, source/databricks/calculation_engine/package/calculation/energy/energy_calculation.py, source/databricks/calculation_engine/package/calculation/energy/hour_to_quarter.py, source/databricks/calculation_engine/package/calculation/output/basis_data_factory.py, source/databricks/calculation_engine/package/calculation/preparation/prepared_data_reader.py, source/databricks/calculation_engine/package/calculation/preparation/prepared_metering_point_time_series.py, source/databricks/calculation_engine/package/calculation/preparation/transformations/basis_data.py, source/databricks/calculation_engine/package/calculation/preparation/transformations/charge_types/tariffs.py, source/databricks/calculation_engine/package/calculation/preparation/transformations/metering_point_time_series.py, source/databricks/calculation_engine/package/calculation/wholesale/get_wholesale_metering_point_time_series.py, source/databricks/calculation_engine/tests/calculation/charges_factory.py, source/databricks/calculation_engine/tests/calculation/energy/aggregations/exchange_aggregators/test_aggregate_net_exchange_per_ga_v8.py, source/databricks/calculation_engine/tests/calculation/energy/quarterly_metering_point_time_series_factories.py, source/databricks/calculation_engine/tests/calculation/energy/test_transform_hour_to_quarter.py, source/databricks/calculation_engine/tests/calculation/output/test_basis_data_writer.py, source/databricks/calculation_engine/tests/calculation/preparation/test_prepared_metering_point_time_series.py, source/databricks/calculation_engine/tests/calculation/preparation/transformations/charge_types/test_tariffs.py, source/databricks/calculation_engine/tests/calculation/preparation/transformations/prepared_metering_point_time_series_factory.py, source/databricks/calculation_engine/tests/calculation/preparation/transformations/test_get_metering_point_time_series.py, source/databricks/calculation_engine/tests/calculation/preparation/transformations/test_get_metering_point_time_series_basis_data_dfs.py
=> refac: Introduce `PreparedMeteringPointTimeSeries`

source/databricks/calculation_engine/package/calculation/preparation/data_structures/__init__.py, source/databricks/calculation_engine/package/calculation/preparation/data_structures/prepared_charges.py, source/databricks/calculation_engine/package/calculation/preparation/prepared_data_reader.py, source/databricks/calculation_engine/package/calculation/wholesale/wholesale_calculation.py
=> feat: Add fee preparion in calculation flow

.github/workflows/ci-databricks.yml
Split python tests to get faster feedback on CI builds
=> build: Split python tests

source/databricks/calculation_engine/package/calculation/wholesale/calculate_total_quantity_and_amount.py, source/databricks/calculation_engine/package/calculation/wholesale/fee_calculators.py, source/databricks/calculation_engine/tests/calculation/wholesale/test_subscription_calculators.py
=> fix: Rounding issue in tariff calculator

source/dotnet/subsystem-tests/Features/Calculations/WholesaleFixingCalculationScenario.cs
=> test: Included fees in expected monthly amount events

source/databricks/calculation_engine/tests/entry_points/test_entry_points.py
Fix entry point tests that failed in PyCharm and used obsolete lib.
=> chore: Update to non-obsolete lib and fix test failing in PyCharm

.docker/entrypoint.sh
=> fix: Fix broken entrypoint.sh

.github/workflows/ci-databricks.yml, .github/workflows/detect-changes.yml, source/databricks/calculation_engine/package/datamigration/schema_config.py
=> chore: Split delta migration tests to reduce CI time

.docker/Dockerfile
=> doc: Improve docker maintainability

.github/workflows/ci-orchestrator.yml
See title.
See example of run that shows the issue: https://github.com/Energinet-DataHub/opengeh-wholesale/actions/runs/8555883503
=> build: Ensure we don't allow merge if "changes" workflow fails

source/dotnet/wholesale-api/Edi.UnitTests/Factories/WholesaleServices/WholesaleServiceRequestAcceptedMessageFactoryTests.cs, source/dotnet/wholesale-api/Edi/Factories/WholesaleServices/WholesaleServiceRequestAcceptedMessageFactory.cs
=> fix: Correct period for wholesale settlement requests

source/databricks/calculation_engine/tests/features/given_a_wholesale_calculation/daily_tariff_per_ga_co_es/when_with_child_metering_point/test_output.py, source/databricks/calculation_engine/tests/features/given_a_wholesale_calculation/daily_tariff_per_ga_co_es/when_with_grid_loss/test_output.py, source/databricks/calculation_engine/tests/features/given_a_wholesale_calculation/fee_per_ga_co_es/when_flex_metering_point_with_child/test_output.py, source/databricks/calculation_engine/tests/features/given_a_wholesale_calculation/hourly_tariff_per_ga_co_es/when_only_for_grid_loss_metering_points/test_output.py, source/databricks/calculation_engine/tests/features/given_a_wholesale_calculation/hourly_tariff_per_ga_co_es/when_with_child_metering_point/test_output.py, source/databricks/calculation_engine/tests/features/given_a_wholesale_calculation/hourly_tariff_per_ga_co_es/when_without_child_metering_point/test_output.py, source/databricks/calculation_engine/tests/features/given_a_wholesale_calculation/monthly_fee_per_ga_co_es/when_with_parent_and_child_metering_points/test_output.py, source/databricks/calculation_engine/tests/features/given_a_wholesale_calculation/monthly_tariff_from_daily_per_ga_co_es/when_with_child_metering_point/test_output.py, source/databricks/calculation_engine/tests/features/given_a_wholesale_calculation/monthly_tariff_from_daily_per_ga_co_es/when_with_negative_grid_loss/test_output.py, source/databricks/calculation_engine/tests/features/given_a_wholesale_calculation/monthly_tariff_from_daily_per_ga_co_es/when_without_child_metering_point/test_output.py, source/databricks/calculation_engine/tests/features/given_a_wholesale_calculation/monthly_tariff_from_hourly_per_ga_co_es/when_montly_amount_with_child_time_series/test_output.py, source/databricks/calculation_engine/tests/features/given_a_wholesale_calculation/monthly_tariff_from_hourly_per_ga_co_es/when_montly_amount_with_parent_and_child_time_series/test_output.py, source/databricks/calculation_engine/tests/features/given_a_wholesale_calculation/monthly_tariff_from_hourly_per_ga_co_es/when_with_negative_grid_loss/test_output.py, source/databricks/calculation_engine/tests/features/given_a_wholesale_calculation/subscription_per_ga_co_es/when_charge_link_starts_later/test_output.py, source/databricks/calculation_engine/tests/features/given_a_wholesale_calculation/subscription_per_ga_co_es/when_quantity_values_differs_from_one/test_output.py, source/databricks/calculation_engine/tests/features/given_a_wholesale_calculation/when_es_change/test_output.py, source/databricks/calculation_engine/tests/features/given_an_energy_calculation/flex_consumption_per_ga_and_brp_and_es/when_with_single_metering_point/test_output.py, source/databricks/calculation_engine/tests/features/given_an_energy_calculation/flex_consumption_per_ga_and_es/when_period_is_one_day/test_output.py, source/databricks/calculation_engine/tests/features/given_an_energy_calculation/flex_consumption_per_ga_and_es/when_period_is_one_hour/test_output.py, source/databricks/calculation_engine/tests/features/given_an_energy_calculation/flex_consumption_per_ga_and_es/when_period_is_two_days_with_es_and_res_change/test_output.py, source/databricks/calculation_engine/tests/features/given_an_energy_calculation/flex_consumption_per_ga_and_es/when_with_single_metering_point/test_output.py, source/databricks/calculation_engine/tests/features/given_an_energy_calculation/grid_loss/when_has_no_non_profiled/test_output.py, source/databricks/calculation_engine/tests/features/given_an_energy_calculation/negative_grid_loss/when_period_is_one_hour/test_output.py, source/databricks/calculation_engine/tests/features/given_an_energy_calculation/nonprofiled_consumption_per_ga_and_es/when_period_is_two_days_with_es_and_res_change/test_output.py, source/databricks/calculation_engine/tests/features/given_an_energy_calculation/when_standard_scenario/test_output.py, source/databricks/calculation_engine/tests/features/given_an_energy_calculation/when_with_only_one_exchange_grid_loss_and_system_correction_metering_point/test_output.py, source/databricks/calculation_engine/tests/features/utils/Use-template.ps1, source/databricks/calculation_engine/tests/features/utils/template.py
Add a template `template.py` for all the `test_output.py` files and a script `Use-Template.ps1` to apply changes from the template to all the test files.
=> refac: Make maintenance of logic test code easier

source/databricks/calculation_engine/package/datamigration/current_state_scripts/views/__init__.py
=> fix: Add missing init file

.docker/entrypoint.sh
Log all individual tests in the CI log output. This is useful when investigating which tests are executed.
=> chore: Better python tests insights in CI

source/databricks/calculation_engine/package/datamigration/current_state_scripts/views/create_settlement_report_metering_point_periods.sql, source/databricks/calculation_engine/package/datamigration/current_state_scripts/views/create_settlement_report_metering_point_time_series.sql, source/databricks/calculation_engine/package/datamigration/migration_scripts/202404191000_Add_version_to_views.sql, source/databricks/calculation_engine/package/datamigration/schema_config.py, source/databricks/calculation_engine/package/infrastructure/paths.py, source/databricks/calculation_engine/tests/views/view_reader.py
=> feat: Introduce delta view versions

source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/CalculationResults/Statements/AggregatedTimeSeriesQueryStatement.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.IntegrationTests/Infrastructure/RequestCalculationResult/AggregatedTimeSeriesQueriesData.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.IntegrationTests/Infrastructure/RequestCalculationResult/AggregatedTimeSeriesQueriesTests.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Interfaces/CalculationResults/Model/EnergyResults/AggregatedTimeSeriesQueryParameters.cs, source/dotnet/wholesale-api/Edi.UnitTests/AggregatedTimeSeriesRequestHandlerTests.cs, source/dotnet/wholesale-api/Edi.UnitTests/Builders/AggregatedTimeSeriesRequestBuilder.cs, source/dotnet/wholesale-api/Edi.UnitTests/Factories/AggregatedTimeSeries/AggregatedTimeSeriesRequestFactoryTests.cs, source/dotnet/wholesale-api/Edi.UnitTests/Validators/AggregatedTimeSeriesRequest/RequestedByActorRoleValidationRuleTest.cs, source/dotnet/wholesale-api/Edi/AggregatedTimeSeriesRequestHandler.cs, source/dotnet/wholesale-api/Edi/Contracts/AggregatedTimeSeries/AggregatedTimeSeriesRequest.proto, source/dotnet/wholesale-api/Edi/Factories/AggregatedTimeSeries/AggregatedTimeSeriesRequestFactory.cs, source/dotnet/wholesale-api/Edi/Models/AggregationPerRoleAndGridArea.cs, source/dotnet/wholesale-api/Edi/Validation/AggregatedTimeSeriesRequest/Rules/BalanceResponsibleValidationRule.cs, source/dotnet/wholesale-api/Edi/Validation/AggregatedTimeSeriesRequest/Rules/EnergySupplierValidationRule.cs, source/dotnet/wholesale-api/Edi/Validation/AggregatedTimeSeriesRequest/Rules/GridAreaValidationRule.cs, source/dotnet/wholesale-api/Edi/Validation/AggregatedTimeSeriesRequest/Rules/RequestedByActorRoleValidationRule.cs, source/dotnet/wholesale-api/Edi/Validation/AggregatedTimeSeriesRequest/Rules/TimeSeriesTypeValidationRule.cs
Support multiple grid area's when requesting aggregated time series data.
Task: https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-mosaic/148
EDI PR: https://github.com/Energinet-DataHub/opengeh-edi/pull/981
=> feat: Support multiple grid areas for RequestAggregatedTimeSeries

source/databricks/calculation_engine/tests/features/conftest.py, source/databricks/calculation_engine/tests/features/given_an_energy_calculation/when_with_only_one_exchange_grid_loss_and_system_correction_metering_point/test_output.py, source/databricks/calculation_engine/tests/features/public_data_models/given_basis_data_for_settlement_report/simple_scenario/test_output.py, source/databricks/calculation_engine/tests/features/utils/csv_to_dataframe_parser.py, source/databricks/calculation_engine/tests/features/utils/templates/public-model-test-template.py, source/databricks/calculation_engine/tests/features/utils/views/assertion.py, source/databricks/calculation_engine/tests/features/utils/views/dataframe_wrapper.py, source/databricks/calculation_engine/tests/features/utils/views/view_scenario_executor.py
Fixed an error in the view test engine.
=> refac: Improving view tests engine

.github/CODEOWNERS
=> raccoons: Update CODEOWNERS

source/databricks/calculation_engine/package/calculator_job.py, source/databricks/calculation_engine/package/container.py, source/databricks/calculation_engine/tests/conftest.py
=> feat: Add spark to DI container

.github/workflows/ci-databricks.yml
**Before**
All migration tests where executed always. And some where executed again if there where changes to migrations.
**Now**
All migration tests are only executed once - and only if there are changes to migrations.
=> chore: Optimize migrations in CI

source/databricks/calculation_engine/package/calculator_job.py, source/databricks/calculation_engine/package/container.py, source/databricks/calculation_engine/tests/conftest.py
This reverts commit 466117702de4bca3c8366b8ad638dbca4e54bbd4.
=> Revert "feat: Add spark to DI container (#2196)"

source/databricks/calculation_engine/package/datamigration/current_state_scripts/tables/create_basis_data_calculations.sql, source/databricks/calculation_engine/package/datamigration/current_state_scripts/views/create_settlement_report_energy_result_v1_view.sql, source/databricks/calculation_engine/package/datamigration/migration_scripts/202404301330_Add_basis_data_calculations.sql, source/databricks/calculation_engine/package/datamigration/migration_scripts/202405011000_Create_settlement_report_energy_result_v1_view.sql, source/databricks/calculation_engine/package/datamigration/schema_config.py
Reverts Energinet-DataHub/opengeh-wholesale#2216
=> Revert "fix: Delete migration"

source/databricks/calculation_engine/package/datamigration/current_state_scripts/tables/create_energy_results.sql, source/databricks/calculation_engine/package/datamigration/current_state_scripts/tables/create_total_monthly_amounts.sql, source/databricks/calculation_engine/package/datamigration/current_state_scripts/tables/create_wholesale_results.sql
=> refac: fix current state

source/databricks/calculation_engine/package/calculation/output/schemas/total_monthly_amounts_schema.py, source/databricks/calculation_engine/package/datamigration/current_state_scripts/tables/create_total_monthly_amounts.sql, source/databricks/calculation_engine/package/datamigration/migration_scripts/202404111300_Create_total_monthly_amounts_table.sql
=> refac: total monthly amount energy supplier nullable

source/dotnet/wholesale-api/Orchestrations.IntegrationTests/Fixtures/OrchestrationsAppFixture.cs, source/dotnet/wholesale-api/Orchestrations/host.json
⚠️ Must merge infrastructure PR first: https://github.com/Energinet-DataHub/dh3-infrastructure/pull/1455
See title.
Part of: https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-mosaic/182
=> refac: Configure durable functions Task Hub Name

docs/public-data-models/README.md
=> doc: Add link to business documentation

.github/workflows/ci-dotnet.yml
Set `use_azure_functions_tools` to `true` to install Azurite, which we need for another PR.
=> build: Install Azurite

source/dotnet/database-migration/DatabaseMigration.csproj, source/dotnet/database-migration/Scripts/202405141445_Add_Period_To_SettlementReport.sql, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Application/SettlementReports_v2/GetSettlementReportsHandler.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Application/SettlementReports_v2/SettlementReport.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Application/SettlementReports_v2/UpdateFailedSettlementReportsHandler.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/Extensions/DependencyInjection/CalculationResultsExtensions.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.IntegrationTests/Application/SettlementReports/GetSettlementReportsHandlerIntegrationTests.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.IntegrationTests/Application/SettlementReports/SettlementReportFinalizeHandlerIntegrationTests.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.IntegrationTests/Application/SettlementReports/UpdateFailedSettlementReportsHandlerIntegrationTests.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.IntegrationTests/Infrastructure/SettlementReports_v2/Persistence/SettlementReportRepositoryTests.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Interfaces/SettlementReports_v2/IGetSettlementReportsHandler.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Interfaces/SettlementReports_v2/ISettlementReportInitializeHandler.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Interfaces/SettlementReports_v2/IUpdateFailedSettlementReportsHandler.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Interfaces/SettlementReports_v2/Models/RequestedSettlementReportDto.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Interfaces/SettlementReports_v2/Models/SettlementReportStatus.cs, source/dotnet/wholesale-api/Common.Infrastructure/Security/FrontendUser.cs, source/dotnet/wholesale-api/Orchestrations.IntegrationTests/Functions/SettlementReports/SettlementReportOrchestrationTests.cs, source/dotnet/wholesale-api/Orchestrations/Functions/SettlementReports/SettlementReportListHttpTrigger.cs, source/dotnet/wholesale-api/Orchestrations/Functions/SettlementReports/SettlementReportRequestTrigger.cs
=> feat: Add list settlement reports API.

source/dotnet/subsystem-tests/Features/Calculations/WholesaleFixingCalculationScenario.cs
=> refac: update total monthly amount subsystem the  received events

source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/Extensions/DependencyInjection/StorageExtensions.cs, source/dotnet/wholesale-api/Orchestrations.IntegrationTests/Fixtures/OrchestrationsAppFixture.cs
=> fix: Incorrect settlement report blob URI.

source/dotnet/subsystem-tests/Features/SettlementReport/SettlementReportScenario.cs
=> refac: SettlementReportScenario

source/dotnet/subsystem-tests/Features/Calculations/BalanceFixingCalculationScenario.cs, source/dotnet/subsystem-tests/Features/Calculations/WholesaleFixingCalculationScenario.cs
=> refac: Fix subsystem tests

source/databricks/calculation_engine/package/calculation/preparation/transformations/metering_point_periods_for_calculation_type.py, source/databricks/calculation_engine/tests/calculation/preparation/transformations/test_get_metering_point_periods_for_calculation_type.py
=> refac: Fix missing parent metering points for child metering points

source/databricks/calculation_engine/package/datamigration/migration_scripts/202405281400_Modify_settlement_report_wholesale_result_v1_view.sql, source/databricks/calculation_engine/tests/features/public_data_models/given_wholesale_results_for_settlement_report/when_wholesale_results_have_amount_per_charge/output/wholesale_results_v1.csv, source/databricks/calculation_engine/tests/features/utils/dataframes/settlement_report/wholesale_results_v1_view_schema.py
=> feat: Add metering_point_type and settlement_method in wholesale_results_v1

.github/workflows/detect-changes.yml, source/databricks/calculation_engine/tests/datamigration/test_migration.py, source/databricks/calculation_engine/tests/helpers/spark_sql_migration_helper.py
=> fix: Fix bugs related to executing migrations in test

source/dotnet/subsystem-tests/Features/Telemetry/RequestTelemetryScenario.cs
=> fix: Skip Then_TelemetryEventsAreLoggedWithinWaitTime

source/databricks/calculation_engine/tests/testsession_configuration.py
=> fix: Many warnings in CI due to false test class

source/dotnet/wholesale-api/WebApi/V3/SettlementReport/SettlementReportApplicableCalculationDto.cs, source/dotnet/wholesale-api/WebApi/V3/SettlementReport/SettlementReportController.cs
=> feat: Add calculation time to settlement report calculations.

source/databricks/calculation_engine/package/calculation/wholesale/total_monthly_amount_calculator.py, source/databricks/calculation_engine/package/calculation/wholesale/wholesale_calculation.py, source/databricks/calculation_engine/tests/calculation/wholesale/test_total_monthly_amount_calculator.py
=> fix: total monthly amount bug

source/databricks/calculation_engine/package/calculation/basis_data/basis_data_results.py, source/databricks/calculation_engine/package/calculation/input/table_reader.py, source/databricks/calculation_engine/package/calculation/output/calculation_writer.py, source/databricks/calculation_engine/package/calculation/output/energy_results.py, source/databricks/calculation_engine/package/calculation/output/monthly_amounts.py, source/databricks/calculation_engine/package/calculation/output/total_monthly_amounts.py, source/databricks/calculation_engine/package/calculation/output/wholesale_results.py, source/databricks/calculation_engine/package/datamigration/schema_config.py, source/databricks/calculation_engine/package/datamigration/substitutions.py, source/databricks/calculation_engine/package/infrastructure/paths.py, source/databricks/calculation_engine/tests/calculation/input/table_reader/test_read_time_series_points.py, source/databricks/calculation_engine/tests/calculation/input/test_input_table_schemas.py, source/databricks/calculation_engine/tests/calculation/output/test_energy_storage_model_factory.py, source/databricks/calculation_engine/tests/calculation/output/test_monthly_amounts_storage_model_factory.py, source/databricks/calculation_engine/tests/calculation/output/test_total_monthly_amounts_storage_model_factory.py, source/databricks/calculation_engine/tests/calculation/output/test_wholesale_storage_model_factory.py, source/databricks/calculation_engine/tests/calculator_job/conftest.py, source/databricks/calculation_engine/tests/calculator_job/test_energy_calculation.py, source/databricks/calculation_engine/tests/calculator_job/test_wholesale_calculation.py, source/databricks/calculation_engine/tests/conftest.py, source/databricks/calculation_engine/tests/datamigration/all_scripts/test_scripts.py, source/databricks/calculation_engine/tests/datamigration/subsystem/test_energy_results_migrations.py, source/databricks/calculation_engine/tests/datamigration/subsystem/test_grid_loss_metering_points_migrations.py, source/databricks/calculation_engine/tests/datamigration/subsystem/test_monthly_amounts_migrations.py, source/databricks/calculation_engine/tests/datamigration/subsystem/test_total_monthly_amounts_migrations.py, source/databricks/calculation_engine/tests/datamigration/subsystem/test_wholesale_results_migrations.py
All changes are the result of organizing the variables of `paths.py` into classes.
=> refac: Bring structure to `paths.py`

source/databricks/calculation_engine/tests/features/public_data_models/wholesale_calculation_results/output/wholesale_calculation_results.energy_result_points_per_brp_ga_v1.csv, source/databricks/calculation_engine/tests/features/public_data_models/wholesale_calculation_results/output/wholesale_calculation_results.energy_result_points_per_es_brp_ga_v1.csv
Add missing feature tests of views.
=> test: Add `wholesale_calculation_results` feature tests

source/dotnet/wholesale-api/Edi.UnitTests/Builders/WholesaleServicesRequestBuilder.cs, source/dotnet/wholesale-api/Edi.UnitTests/Validators/WholesaleServicesRequest/GridAreaValidatorTest.cs, source/dotnet/wholesale-api/Edi.UnitTests/WholesaleServicesRequestHandlerTests.cs, source/dotnet/wholesale-api/Edi/Validation/AggregatedTimeSeriesRequest/Rules/BalanceResponsibleValidationRule.cs, source/dotnet/wholesale-api/Edi/Validation/AggregatedTimeSeriesRequest/Rules/GridAreaValidationRule.cs, source/dotnet/wholesale-api/Edi/Validation/AggregatedTimeSeriesRequest/Rules/RequestedByActorRoleValidationRule.cs, source/dotnet/wholesale-api/Edi/Validation/AggregatedTimeSeriesRequest/Rules/SettlementVersionValidationRule.cs, source/dotnet/wholesale-api/Edi/Validation/AggregatedTimeSeriesRequest/Rules/TimeSeriesTypeValidationRule.cs, source/dotnet/wholesale-api/Edi/WholesaleServicesRequestHandler.cs
=> test: Test of invalid grid area check.

source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/CalculationResults/WholesaleResultQueries.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/Factories/WholesaleResultFactory.cs, source/dotnet/wholesale-api/Edi.UnitTests/Validators/WholesaleServicesRequest/PeriodValidationRuleTests.cs, source/dotnet/wholesale-api/Edi.UnitTests/WholesaleServicesRequestHandlerTests.cs, source/dotnet/wholesale-api/Edi/Validation/Helpers/PeriodValidationHelper.cs, source/dotnet/wholesale-api/Edi/Validation/WholesaleServicesRequest/Rules/PeriodValidationRule.cs, source/dotnet/wholesale-api/Edi/WholesaleServicesRequestHandler.cs
=> feat: allow start to not be of the first, when it is precisly 3 years and 2 months ago

source/dotnet/wholesale-api/CalculationResults/CalculationResults.IntegrationTests/Application/SettlementReports/SettlementReportFileRequestHandlerIntegrationTests.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.IntegrationTests/Fixtures/MigrationsFreeDatabricksSchemaManager.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.IntegrationTests/Fixtures/MigrationsFreeDatabricksSqlStatementApiFixture.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.IntegrationTests/Infrastructure/SettlementReports_v2/SettlementReportEnergyResultRepositoryTests.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.IntegrationTests/Infrastructure/SettlementReports_v2/SettlementReportWholesaleRepositoryTests.cs
=> fix: Change to migration free Databricks Fixture.

source/databricks/calculation_engine/package/calculation/calculation.py, source/databricks/calculation_engine/package/calculation/energy/calculated_grid_loss.py
=> refac: Calculated grid loss resolution

source/databricks/calculation_engine/package/calculation/calculation.py, source/databricks/calculation_engine/package/calculation/energy/calculated_grid_loss.py
Reverts Energinet-DataHub/opengeh-wholesale#2386
=> Revert "refac: Calculated grid loss resolution"

source/dotnet/wholesale-api/CalculationResults/CalculationResults.Application/SettlementReports_v2/SettlementReportFileRequestHandler.cs
=> fix: Conflict in storage name for settlement reports.

source/dotnet/wholesale-api/CalculationResults/CalculationResults.Application/SettlementReports_v2/ISettlementReportFileGenerator.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Application/SettlementReports_v2/SettlementReportFileRequestHandler.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/SettlementReports_v2/Generators/ChargeLinkPeriodsFileGenerator.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/SettlementReports_v2/Generators/EnergyResultFileGenerator.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/SettlementReports_v2/Generators/WholesaleResultFileGenerator.cs
=> fix: Remove headers from merged settlement report files.

source/dotnet/wholesale-api/CalculationResults/CalculationResults.Application/SettlementReports_v2/SettlementReportFromFilesHandler.cs
=> test: Use a different file threshold in settlement report.

source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/SettlementReports_v2/Statements/SettlementReportMeteringPointTimeSeriesResultCountQueryStatement.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/SettlementReports_v2/Statements/SettlementReportMeteringPointTimeSeriesResultQueryStatement.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.IntegrationTests/Infrastructure/SettlementReports_v2/SettlementReportMeteringPointTimeSeriesResultRepositoryTests.cs
=> fix: anmodning og download - mpts skip take

source/dotnet/wholesale-api/CalculationResults/CalculationResults.Application/SettlementReports_v2/ISettlementReportEnergyResultRepository.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/SettlementReports_v2/Generators/ChargeLinkPeriodsFileGenerator.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/SettlementReports_v2/Generators/ChargePriceFileGenerator.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/SettlementReports_v2/Generators/CsvFileGeneratorBase.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/SettlementReports_v2/Generators/EnergyResultFileGenerator.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/SettlementReports_v2/Generators/MeteringPointMasterDataFileGenerator.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/SettlementReports_v2/Generators/MonthlyAmountFileGenerator.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/SettlementReports_v2/Generators/WholesaleResultFileGenerator.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/SettlementReports_v2/SettlementReportEnergyResultRepository.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/SettlementReports_v2/Statements/SettlementReportLatestEnergyResultCountQueryStatement.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/SettlementReports_v2/Statements/SettlementReportLatestEnergyResultPerEnergySupplierCountQueryStatement.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/SettlementReports_v2/Statements/SettlementReportLatestEnergyResultPerEnergySupplierQueryStatement.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/SettlementReports_v2/Statements/SettlementReportLatestEnergyResultQueryStatement.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.IntegrationTests/Infrastructure/SettlementReports_v2/SettlementReportEnergyResultRepositoryTests.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Interfaces/SettlementReports/SettlementReportLatestEnergyResultPerEnergySupplierQueryFilter.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Interfaces/SettlementReports/SettlementReportLatestEnergyResultQueryFilter.cs
=> feat: Enable latest version of balancefixing settlement reports.

source/dotnet/wholesale-api/CalculationResults/CalculationResults.Application/SettlementReports_v2/SettlementReport.cs
=> fix: IncludeBasisData not assigned in mapper.

source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/SettlementReports_v2/Generators/ChargeLinkPeriodsFileGenerator.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/SettlementReports_v2/Generators/ChargePriceFileGenerator.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/SettlementReports_v2/Generators/EnergyResultFileGenerator.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/SettlementReports_v2/Generators/MeteringPointMasterDataFileGenerator.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/SettlementReports_v2/Generators/MeteringPointTimeSeriesFileGenerator.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/SettlementReports_v2/Generators/MonthlyAmountFileGenerator.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/SettlementReports_v2/Generators/WholesaleResultFileGenerator.cs
=> change: Decrease chunk size in settlement reports.

source/databricks/calculation_engine/contracts/data_products/calculation_results/amounts_per_charge_v1.py, source/databricks/calculation_engine/contracts/data_products/settlement_report/charge_link_periods_v1.py, source/databricks/calculation_engine/contracts/data_products/settlement_report/charge_prices_v1.py, source/databricks/calculation_engine/contracts/data_products/settlement_report/energy_result_points_per_ga_v1.py, source/databricks/calculation_engine/contracts/data_products/settlement_report/wholesale_results_v1.py
Fix bad nullabilities in data product contracts.
=> fix: Correct nullability of data product contracts

source/dotnet/wholesale-api/CalculationResults/CalculationResults.Application/SettlementReports_v2/ISettlementReportFileGenerator.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Application/SettlementReports_v2/SettlementReportFileRequestHandler.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Application/SettlementReports_v2/SettlementReportRequestHandler.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/SettlementReports_v2/Generators/CsvFileGeneratorBase.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/SettlementReports_v2/Generators/MeteringPointTimeSeriesFileGenerator.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.IntegrationTests/Application/SettlementReports/SettlementReportRequestHandlerIntegrationTests.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.IntegrationTests/Infrastructure/SettlementReports_v2/Generators/MeteringPointTimeSeriesFileGeneratorTests.cs
=> feat: anmodning og download - market roles passed to file gens

source/dotnet/database-migration/DatabaseMigration.csproj, source/dotnet/database-migration/Scripts/202406210900_Add_IsHiddenFromActor_to_SettlementReport.sql, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Application/SettlementReports_v2/SettlementReport.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Application/SettlementReports_v2/SettlementReportDownloadHandler.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Application/SettlementReports_v2/SettlementReportInitializeHandler.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Application/SettlementReports_v2/SettlementReportRequestHandler.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/Persistence/SettlementReportRequest/SettlementReportRepository.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.IntegrationTests/Application/SettlementReports/GetSettlementReportsHandlerIntegrationTests.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.IntegrationTests/Application/SettlementReports/SettlementReportDownloadHandlerIntegrationTests.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.IntegrationTests/Application/SettlementReports/SettlementReportFinalizeHandlerIntegrationTests.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.IntegrationTests/Application/SettlementReports/SettlementReportRequestHandlerIntegrationTests.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.IntegrationTests/Application/SettlementReports/UpdateFailedSettlementReportsHandlerIntegrationTests.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.IntegrationTests/Infrastructure/SettlementReports_v2/Persistence/SettlementReportRepositoryTests.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Interfaces/SettlementReports_v2/ISettlementReportInitializeHandler.cs, source/dotnet/wholesale-api/Orchestrations/Functions/SettlementReports/SettlementReportRequestTrigger.cs
=> feat: Hide settlement reports from actors.

source/dotnet/wholesale-api/CalculationResults/CalculationResults.Application/SettlementReports_v2/SettlementReportMonthlyAmountRow.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/SettlementReports_v2/Generators/MonthlyAmountFileGenerator.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/SettlementReports_v2/SettlementReportMonthlyAmountRowFactory.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Interfaces/SettlementReports/Model/SettlementReportMonthlyAmountRow.cs
Add supprot for null in charge type for MonthlyAmount
=> bug: Added support for null in ChargeType

source/dotnet/wholesale-api/Edi.UnitTests/Factories/AggregatedTimeSeries/AggregatedTimeSeriesRequestAcceptedMessageFactoryTests.cs, source/dotnet/wholesale-api/Edi/Contracts/AggregatedTimeSeries/AggregatedTimeSeriesRequestAccepted.proto, source/dotnet/wholesale-api/Edi/Factories/AggregatedTimeSeries/AggregatedTimeSeriesRequestAcceptedMessageFactory.cs
=> fix: Add settlement version to aggregated accepted contract

source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/SettlementReports_v2/Generators/ChargeLinkPeriodsFileGenerator.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/SettlementReports_v2/Generators/ChargePriceFileGenerator.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/SettlementReports_v2/Generators/CsvFileGeneratorBase.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/SettlementReports_v2/Generators/EnergyResultFileGenerator.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/SettlementReports_v2/Generators/MeteringPointMasterDataFileGenerator.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/SettlementReports_v2/Generators/MonthlyAmountFileGenerator.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/SettlementReports_v2/Generators/WholesaleResultFileGenerator.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Interfaces/SettlementReports_v2/Models/MarketRole.cs, source/dotnet/wholesale-api/Common.Infrastructure/Security/FrontendActorMarketRole.cs, source/dotnet/wholesale-api/Common.Infrastructure/Security/FrontendUserProvider.cs, source/dotnet/wholesale-api/Orchestrations/Functions/SettlementReports/SettlementReportRequestTrigger.cs
=> feat: anmodning og download - market roles passed to specific filegnerators

source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/CalculationResults/Statements/AggregatedTimeSeriesQueryStatement.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/CalculationResults/Statements/WholesaleServicesQueryStatement.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.IntegrationTests/Infrastructure/RequestCalculationResult/AggregatedTimeSeriesQueriesTests.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.IntegrationTests/Infrastructure/RequestCalculationResult/WholesaleServicesQueriesTests.cs
=> fix: Corrected actor number null check for aggregated request

docs/diagrams/c4-model/model.dsl, docs/diagrams/c4-model/views.json
=> doc: Add Databricks SQL warehouses to C4 diagrams

source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/SettlementReports_v2/SettlementReportMeteringPointTimeSeriesResultQueries.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/SettlementReports_v2/Statements/SettlementReportMeteringPointTimeSeriesResultCountQueryStatement2.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/SettlementReports_v2/Statements/SettlementReportMeteringPointTimeSeriesResultQueryStatement2.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.IntegrationTests/Application/SettlementReports/SettlementReportFileRequestHandlerIntegrationTests.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.IntegrationTests/Infrastructure/SettlementReports_v2/SettlementReportMeteringPointTimeSeriesResultRepositoryTests.cs, source/dotnet/wholesale-api/Orchestrations/Functions/SettlementReports/SettlementReportOrchestration.cs
=> Test performance of time series points.

source/databricks/calculation_engine/package/calculation/wholesale/subscription_calculators.py, source/databricks/calculation_engine/tests/calculation/wholesale/test_subscription_calculators.py
=> refac: Round charge price per day for subscription to 6 decimals

source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/SettlementReports_v2/Generators/MeteringPointTimeSeriesFileGenerator.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/SettlementReports_v2/Statements/SettlementReportMeteringPointTimeSeriesResultCountQueryStatement2.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/SettlementReports_v2/Statements/SettlementReportMeteringPointTimeSeriesResultQueryStatement2.cs
=> change: Test settlement report grouped by mp id.

.vscode/settings.json
=> chore: Avoid some VSCode popups

source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/SettlementReports_v2/Statements/SettlementReportMonthlyAmountCountQueryStatement.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/SettlementReports_v2/Statements/SettlementReportMonthlyAmountQueryStatement.cs
The regular monthly amounts still had some totals included, this pr fixes the filters in the query to correctly exclude theese
=> update: fix regular monthly amounts to exclude totals

source/dotnet/subsystem-tests/SubsystemTests.csproj, source/dotnet/wholesale-api/CalculationResults/CalculationResults.IntegrationTests/Fixtures/MigrationsFreeDatabricksSchemaManager.cs, source/dotnet/wholesale-api/Calculations/Calculations.Infrastructure/Calculations.Infrastructure.csproj, source/dotnet/wholesale-api/Common.Infrastructure/Common.Infrastructure.csproj
=> Upgrade Databricks Core package.

source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/SettlementReports_v2/Generators/CsvFileGeneratorBase.cs
=> fix: Broken chunk count.

source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/SettlementReports_v2/Generators/ChargeLinkPeriodsFileGenerator.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/SettlementReports_v2/Generators/ChargePriceFileGenerator.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/SettlementReports_v2/Generators/CsvFileGeneratorBase.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/SettlementReports_v2/Generators/EnergyResultFileGenerator.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/SettlementReports_v2/Generators/MeteringPointMasterDataFileGenerator.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/SettlementReports_v2/Generators/MeteringPointTimeSeriesFileGenerator.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/SettlementReports_v2/Generators/MonthlyAmountFileGenerator.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/SettlementReports_v2/Generators/MonthlyAmountTotalFileGenerator.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/SettlementReports_v2/Generators/WholesaleResultFileGenerator.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.IntegrationTests/Application/SettlementReports/SettlementReportFileRequestHandlerIntegrationTests.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.IntegrationTests/Infrastructure/SettlementReports_v2/Generators/MeteringPointTimeSeriesFileGeneratorTests.cs
=> feat: settlement reports - quoted grid area mp ids and actor numbers

source/dotnet/subsystem-tests/SubsystemTests.csproj, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/CalculationResults.Infrastructure.csproj, source/dotnet/wholesale-api/CalculationResults/CalculationResults.IntegrationTests/CalculationResults.IntegrationTests.csproj, source/dotnet/wholesale-api/CalculationResults/CalculationResults.UnitTests/CalculationResults.UnitTests.csproj, source/dotnet/wholesale-api/Calculations/Calculations.Infrastructure/Calculations.Infrastructure.csproj, source/dotnet/wholesale-api/Calculations/Calculations.IntegrationTests/Calculations.IntegrationTests.csproj, source/dotnet/wholesale-api/Calculations/Calculations.UnitTests/Calculations.UnitTests.csproj, source/dotnet/wholesale-api/Edi.UnitTests/Edi.UnitTests.csproj, source/dotnet/wholesale-api/Events/Events.Infrastructure/Events.Infrastructure.csproj, source/dotnet/wholesale-api/Events/Events.IntegrationTests/Events.IntegrationTests.csproj, source/dotnet/wholesale-api/Events/Events.UnitTests/Events.UnitTests.csproj, source/dotnet/wholesale-api/Orchestrations.IntegrationTests/Orchestrations.IntegrationTests.csproj, source/dotnet/wholesale-api/Test.Core/Test.Core.csproj, source/dotnet/wholesale-api/WebApi.IntegrationTests/WebApi.IntegrationTests.csproj, source/dotnet/wholesale-api/WebApi.UnitTests/WebApi.UnitTests.csproj
=> build: Update (subset of) NuGet packages

source/databricks/calculation_engine/tests/helpers/data_frame_utils.py, source/databricks/calculation_engine/tests/test.local.settings.sample.yml, source/databricks/calculation_engine/tests/testsession_configuration.py
=> refac: Add count to actual and expected in feature test with toggle

.github/workflows/detect-changes.yml, source/dotnet/wholesale-api/Calculations/Calculations.UnitTests/Infrastructure/Calculations/DatabricksCalculatorJobParametersFactoryTests.cs
=> test: Update .NET test to accept optional `--simulation` parameter for calculations

source/dotnet/wholesale-api/CalculationResults/CalculationResults.Application/SettlementReports_v2/SettlementReportRequestHandler.cs
Until basis data is ready for Balance fixing, we need to remove the files from Settlement reports, to avoid leaking data
=> Remove basis data files from Balancefixing temporarily

source/databricks/calculation_engine/package/calculation/output/schemas/__init__.py, source/databricks/calculation_engine/package/calculation/output/schemas/energy_results_schema.py, source/databricks/calculation_engine/package/datamigration_hive/schema_config.py, source/databricks/calculation_engine/tests/datamigration/subsystem/test_energy_results_migrations.py
=> refac: Rename to `hive_energy_results_schema`

source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/Experimental/DatabricksSqlRowHydrator.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/SettlementReports_v2/Statements/SettlementReportEnergyResultPerEnergySupplierViewSchemaDefinition.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/SettlementReports_v2/Statements/SettlementReportEnergyResultViewSchemaDefinition.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/SettlementReports_v2/Statements/SettlementReportWholesaleViewColumns.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.IntegrationTests/Infrastructure/SettlementReports_v2/SettlementReportEnergyResultRepositoryTests.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.IntegrationTests/Infrastructure/SettlementReports_v2/SettlementReportWholesaleRepositoryTests.cs
=> fix: Incorrect nullability in settlement reports.

.github/workflows/ci-databricks.yml
=> refac: Small CI name update

source/databricks/calculation_engine/package/codelists/aggregation_level.py, source/databricks/calculation_engine/package/codelists/time_series_type.py, source/databricks/calculation_engine/tests/calculator_job/conftest.py, source/databricks/calculation_engine/tests/calculator_job/test_energy_calculation.py
=> test: Update calculator job tests for energy results to Unity Catalog

source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/SettlementReports_v2/Generators/ChargePriceFileGenerator.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/SettlementReports_v2/SettlementReportChargePriceRepository.cs
=> fix: settlement reports - charge price file generator count

source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/Persistence/Databricks/SettlementReportChargePriceResultViewEntity.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/SettlementReports_v2/SettlementReportChargeLinkPeriodsRepository.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/SettlementReports_v2/SettlementReportChargePriceRepository.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/SettlementReports_v2/SettlementReportMonthlyAmountRepository.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/SettlementReports_v2/SettlementReportMonthlyAmountTotalRepository.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/SettlementReports_v2/SettlementReportWholesaleRepository.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.IntegrationTests/Infrastructure/SettlementReports_v2/SettlementReportChargeLinkPeriodsRepositoryTests.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.IntegrationTests/Infrastructure/SettlementReports_v2/SettlementReportChargePricesRepositoryTests.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.IntegrationTests/Infrastructure/SettlementReports_v2/SettlementReportMonthlyAmountRepositoryTests.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.IntegrationTests/Infrastructure/SettlementReports_v2/SettlementReportWholesaleRepositoryTests.cs, source/dotnet/wholesale-api/Orchestration.SettlementReports/host.json
=> fix: Wrong is_tax included in settlement report.

source/dotnet/wholesale-api/CalculationResults/CalculationResults.Application/SettlementReports_v2/ISettlementReportEnergyResultRepository.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/SettlementReports_v2/Generators/EnergyResultFileGenerator.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/SettlementReports_v2/SettlementReportEnergyResultRepository.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.IntegrationTests/Infrastructure/SettlementReports_v2/Generators/EnergyResultFileGeneratorTests.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.IntegrationTests/Infrastructure/SettlementReports_v2/SettlementReportEnergyResultRepositoryTests.cs
=> fix: Change energy results for FAS to include es.

source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/SettlementReports_v2/Generators/MeteringPointMasterDataFileGenerator.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/SettlementReports_v2/SettlementReportEnergyResultRepository.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/SettlementReports_v2/SettlementReportMonthlyAmountTotalRepository.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/SettlementReports_v2/SettlementReportWholesaleRepository.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.IntegrationTests/Application/SettlementReports/SettlementReportFileRequestHandlerIntegrationTests.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.IntegrationTests/Infrastructure/SettlementReports_v2/SettlementReportEnergyResultRepositoryTests.cs, source/dotnet/wholesale-api/Orchestration.SettlementReports/host.json
=> fix: Lookup on chargeowner, when not FAS for monthly amounts.

source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/Extensions/Options/DeltaTableOptions.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/Persistence/Databricks/SettlementReportMeteringPointTimeSeriesEntityConfiguration.cs
=> perf: Change settlement report view to test view.

source/dotnet/wholesale-api/CalculationResults/CalculationResults.Application/SettlementReports_v2/SettlementReportFileRequestHandler.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.UnitTests/Application/SettlementReports_v2/SettlementReportFileRequestHandlerTests.cs
=> fix: Always include ddm/ddq in file names.

source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/Extensions/Options/DeltaTableOptions.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/Persistence/Databricks/SettlementReportMeteringPointTimeSeriesEntityConfiguration.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/SettlementReports_v2/Generators/MeteringPointTimeSeriesFileGenerator.cs
=> perf: Revert view name after test.

source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/SettlementReports_v2/Generators/MeteringPointTimeSeriesFileGenerator.cs
=> revert: Chunk size for time series points.

source/databricks/calculation_engine/package/databases/wholesale_internal/schemas/executed_migrations_schema.py, source/databricks/calculation_engine/package/databases/wholesale_migrations_wholesale/__init__.py, source/databricks/calculation_engine/package/databases/wholesale_results/__init__.py, source/databricks/calculation_engine/package/databases/wholesale_results_internal/energy_results.py, source/databricks/calculation_engine/package/databases/wholesale_results_internal/schemas/__init__.py, source/databricks/calculation_engine/package/databases/wholesale_results_internal/schemas/energy_per_brp_schema.py, source/databricks/calculation_engine/package/databases/wholesale_results_internal/schemas/energy_per_es_schema.py, source/databricks/calculation_engine/package/databases/wholesale_results_internal/schemas/energy_schema.py, source/databricks/calculation_engine/package/databases/wholesale_results_internal/schemas/exchange_per_neighbor_schema.py, source/databricks/calculation_engine/package/databases/wholesale_results_internal/schemas/grid_loss_metering_point_time_series_schema.py, source/databricks/calculation_engine/package/databases/wholesale_settlement_reports/__init__.py, source/databricks/calculation_engine/package/datamigration/schema_config.py, source/databricks/calculation_engine/tests/datamigration/subsystem/test_energy_results_migrations.py
Creates packages for all databases and modules for all tables. This includes databases without tables (data products) and it includes tables without read or write operations (`executed_migrations`). This is to make the storage model more explicit to developers.
Some descriptions have been added and a few names have also been fixed.
=> refac: Create packages for all databases and modules for all tables

source/dotnet/wholesale-api/Orchestration.SettlementReports/Functions/SettlementReports/SettlementReportOrchestration.cs
=> change: Show 1% to easier see when an orch has been scheduled.

source/databricks/calculation_engine/package/databases/migrations_wholesale/table_reader.py, source/databricks/calculation_engine/package/databases/repository_helper.py, source/databricks/calculation_engine/package/databases/wholesale_internal/table_reader.py
=> refac: Move reusable code to repository_helper

source/databricks/calculation_engine/package/calculator_job_args.py, source/databricks/calculation_engine/package/infrastructure/environment_variables.py, source/databricks/calculation_engine/package/infrastructure/infrastructure_settings.py, source/databricks/calculation_engine/tests/conftest.py, source/databricks/calculation_engine/tests/infrastructure/test_get_calculator_args.py
=> feat: Add calculation_input_database to infrastructure_settings

source/databricks/calculation_engine/tests/calculator_job/test_energy_calculation.py, source/databricks/calculation_engine/tests/calculator_job/test_wholesale_calculation.py
=> test: Only test UC views in calculator job tests

source/databricks/calculation_engine/tests/calculator_job/conftest.py, source/databricks/calculation_engine/tests/conftest.py, source/databricks/calculation_engine/tests/datamigration/unity_catalog/test_unity_catalog.py
=> refac: Fix is managed test

source/databricks/calculation_engine/package/calculation/preparation/prepared_data_reader.py, source/databricks/calculation_engine/package/calculation/preparation/transformations/charges_reader.py, source/databricks/calculation_engine/package/calculation/preparation/transformations/grid_loss_responsible.py, source/databricks/calculation_engine/package/calculation/preparation/transformations/metering_point_periods.py, source/databricks/calculation_engine/package/calculation/preparation/transformations/time_series_points.py, source/databricks/calculation_engine/package/calculator_job.py, source/databricks/calculation_engine/package/databases/migrations_wholesale/__init__.py, source/databricks/calculation_engine/package/databases/migrations_wholesale/repository.py, source/databricks/calculation_engine/package/databases/wholesale_internal/__init__.py, source/databricks/calculation_engine/package/databases/wholesale_internal/repository.py, source/databricks/calculation_engine/tests/calculation/preparation/test_prepared_data_reader.py, source/databricks/calculation_engine/tests/calculation/preparation/transformations/test_charges_reader_read_charge_links.py, source/databricks/calculation_engine/tests/calculation/preparation/transformations/test_charges_reader_read_charges.py, source/databricks/calculation_engine/tests/calculation/preparation/transformations/test_get_metering_point_periods_df.py, source/databricks/calculation_engine/tests/calculation/preparation/transformations/test_get_time_series_points.py, source/databricks/calculation_engine/tests/calculation/preparation/transformations/test_grid_loss_responsible.py, source/databricks/calculation_engine/tests/calculator_job/conftest.py, source/databricks/calculation_engine/tests/databases/migrations_wholesale/table_reader/test_read_charge_links_periods.py, source/databricks/calculation_engine/tests/databases/migrations_wholesale/table_reader/test_read_charge_price_information_periods.py, source/databricks/calculation_engine/tests/databases/migrations_wholesale/table_reader/test_read_charge_price_points.py, source/databricks/calculation_engine/tests/databases/migrations_wholesale/table_reader/test_read_metering_point_periods.py, source/databricks/calculation_engine/tests/databases/migrations_wholesale/table_reader/test_read_time_series_points.py, source/databricks/calculation_engine/tests/databases/wholesale_internal/table_reader/test_read_calculations.py, source/databricks/calculation_engine/tests/databases/wholesale_internal/table_reader/test_read_grid_loss_metering_points.py, source/databricks/calculation_engine/tests/features/utils/input_specifications.py
=> refac: Rename table readers

source/dotnet/wholesale-api/CalculationResults/CalculationResults.Application/SettlementReports_v2/SettlementReportRequestHandler.cs
=> fix: Count each file in parallel.

source/databricks/calculation_engine/package/infrastructure/paths.py
=> fix: Fix migration_wholesale view naming

source/dotnet/database-migration/DatabaseMigration.csproj, source/dotnet/subsystem-tests/Fixtures/DatabricksClientExtensions.cs, source/dotnet/subsystem-tests/SubsystemTests.csproj, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Application/CalculationResults.Application.csproj, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/CalculationResults.Infrastructure.csproj, source/dotnet/wholesale-api/CalculationResults/CalculationResults.IntegrationTests/CalculationResults.IntegrationTests.csproj, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Interfaces/CalculationResults.Interfaces.csproj, source/dotnet/wholesale-api/CalculationResults/CalculationResults.UnitTests/CalculationResults.UnitTests.csproj, source/dotnet/wholesale-api/Calculations/Calculations.Application/Calculations.Application.csproj, source/dotnet/wholesale-api/Calculations/Calculations.Infrastructure/Calculations.Infrastructure.csproj, source/dotnet/wholesale-api/Calculations/Calculations.IntegrationTests/Calculations.IntegrationTests.csproj, source/dotnet/wholesale-api/Calculations/Calculations.Interfaces/Calculations.Interfaces.csproj, source/dotnet/wholesale-api/Calculations/Calculations.UnitTests/Calculations.UnitTests.csproj, source/dotnet/wholesale-api/Common.Infrastructure/Common.Infrastructure.csproj, source/dotnet/wholesale-api/Common.Interfaces/Common.Interfaces.csproj, source/dotnet/wholesale-api/Edi.UnitTests/Edi.UnitTests.csproj, source/dotnet/wholesale-api/Edi/Edi.csproj, source/dotnet/wholesale-api/Events/Events.Application/Events.Application.csproj, source/dotnet/wholesale-api/Events/Events.Infrastructure/Events.Infrastructure.csproj, source/dotnet/wholesale-api/Events/Events.IntegrationTests/Events.IntegrationTests.csproj, source/dotnet/wholesale-api/Events/Events.Interfaces/Events.Interfaces.csproj, source/dotnet/wholesale-api/Events/Events.UnitTests/Events.UnitTests.csproj, source/dotnet/wholesale-api/Orchestration.SettlementReports/Orchestration.SettlementReports.csproj, source/dotnet/wholesale-api/Orchestrations.IntegrationTests/Orchestrations.IntegrationTests.csproj, source/dotnet/wholesale-api/Orchestrations/Orchestrations.csproj, source/dotnet/wholesale-api/Test.Core/Test.Core.csproj, source/dotnet/wholesale-api/WebApi.IntegrationTests/WebApi.IntegrationTests.csproj, source/dotnet/wholesale-api/WebApi.UnitTests/WebApi.UnitTests.csproj, source/dotnet/wholesale-api/WebApi/WebApi.csproj
Update NuGet packages.
Because of a change in Databricks Jobs API (client SDK) some code was refactored.
Deployed to `dev_002`: https://github.com/Energinet-DataHub/dh3-environments/actions/runs/10382516077
=> chore: Bump NuGet packages

.github/workflows/cd.yml
Ref: https://app.zenhub.com/workspaces/the-outlaws-6193fe815d79fc0011e741b1/issues/gh/energinet-datahub/team-the-outlaws/2251
=> Add workflow dispatch to cd.yml

source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/CalculationResults.Infrastructure.csproj, source/dotnet/wholesale-api/Calculations/Calculations.Application/Calculations.Application.csproj, source/dotnet/wholesale-api/Calculations/Calculations.Infrastructure/Calculations.Infrastructure.csproj, source/dotnet/wholesale-api/Common.Infrastructure/Common.Infrastructure.csproj, source/dotnet/wholesale-api/Events/Events.Infrastructure/Events.Infrastructure.csproj, source/dotnet/wholesale-api/Orchestration.SettlementReports/Orchestration.SettlementReports.csproj, source/dotnet/wholesale-api/Orchestrations/Orchestrations.csproj, source/dotnet/wholesale-api/WebApi/WebApi.csproj
Use a App package prerelease to test a preview of DarkLoop.
Part of:
https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-mosaic/285
=> refac: Try App package prerelease

source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/CalculationResults.Infrastructure.csproj, source/dotnet/wholesale-api/Calculations/Calculations.Application/Calculations.Application.csproj, source/dotnet/wholesale-api/Calculations/Calculations.Infrastructure/Calculations.Infrastructure.csproj, source/dotnet/wholesale-api/Common.Infrastructure/Common.Infrastructure.csproj, source/dotnet/wholesale-api/Events/Events.Infrastructure/Events.Infrastructure.csproj, source/dotnet/wholesale-api/Orchestration.SettlementReports/Orchestration.SettlementReports.csproj, source/dotnet/wholesale-api/Orchestrations/Orchestrations.csproj, source/dotnet/wholesale-api/WebApi/WebApi.csproj
See title.
Deployed to `dev_002`: https://github.com/Energinet-DataHub/dh3-environments/actions/runs/10486300226
Part of:
https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-mosaic/285
=> refac: Use latest App package

source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/Extensions/DependencyInjection/CalculationResultsExtensions.cs
=> fix: missing ioc config for energy databricks contracts

source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/SettlementReports_v2/Generators/MeteringPointTimeSeriesFileGenerator.cs
=> increase the LIMIT for metering point time series

source/dotnet/subsystem-tests/Features/Calculations/BalanceFixingCalculationScenario.cs
=> refac: Increase time limit until only saving to uc

source/dotnet/subsystem-tests/Features/Telemetry/RequestTelemetryScenario.cs
=> refac: Skip telemetry subsystem test for now

source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/SettlementReports_v2/Generators/ChargeLinkPeriodsFileGenerator.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/SettlementReports_v2/Generators/ChargePriceFileGenerator.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/SettlementReports_v2/Generators/EnergyResultFileGenerator.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/SettlementReports_v2/Generators/MeteringPointMasterDataFileGenerator.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/SettlementReports_v2/Generators/MeteringPointTimeSeriesFileGenerator.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/SettlementReports_v2/Generators/MonthlyAmountFileGenerator.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/SettlementReports_v2/Generators/MonthlyAmountTotalFileGenerator.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/SettlementReports_v2/Generators/WholesaleResultFileGenerator.cs
=> change limit for each view

source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/SettlementReports_v2/Generators/ChargePriceFileGenerator.cs
=> Charge price count chunks should return 1

source/databricks/calculation_engine/package/datamigration/migration_scripts/202409031110_add__basis_data_internal__clustering__metering_point_periods.sql
=> refac: Update clustering on basis data metering points periods

source/databricks/calculation_engine/contracts/settlement-report-job-parameters-reference.txt, source/databricks/calculation_engine/package/settlement_report_job/args_helper.py, source/databricks/calculation_engine/package/settlement_report_job/settlement_report_args.py, source/databricks/calculation_engine/package/settlement_report_job/settlement_report_job_args.py, source/databricks/calculation_engine/tests/settlement_report_job/test_settlement_report_args.py
=> feat: Add calculation_id_by_grid_area_code and energy_supplier_id parameter to settlement report job

source/dotnet/wholesale-api/Edi/Edi.csproj, source/dotnet/wholesale-api/Edi/Extensions/DependencyInjection/EdiExtensions.cs, source/dotnet/wholesale-api/Events/Events.Infrastructure/Extensions/DependencyInjection/EventsExtensions.cs, source/dotnet/wholesale-api/Orchestrations/Extensions/DependencyInjection/WholesaleInboxExtensions.cs, source/dotnet/wholesale-api/WebApi/Extensions/DependencyInjection/EventsExtensions.cs
- https://github.com/Energinet-DataHub/dh3-environments/actions/runs/10884158520
=> feat: Add dead-letter health checks

.github/workflows/cd.yml
=> fix databricks pipeline

source/databricks/settlement_report/settlement_report_job/domain/report_generator.py, source/databricks/settlement_report/settlement_report_job/domain/time_series_factory.py
=> fix: Fix report_generator.py

source/databricks/calculation_engine/package/databases/wholesale_results_internal/energy_results.py, source/databricks/calculation_engine/package/databases/wholesale_results_internal/schemas/__init__.py, source/databricks/calculation_engine/package/databases/wholesale_results_internal/schemas/hive_energy_results_schema.py, source/databricks/calculation_engine/package/datamigration_hive/schema_config.py, source/databricks/calculation_engine/package/infrastructure/paths.py, source/databricks/calculation_engine/tests/calculator_job/conftest.py, source/databricks/calculation_engine/tests/calculator_job/test_wholesale_calculation.py, source/databricks/calculation_engine/tests/databases/wholesale_results_internal/test_energy_storage_model_factory.py
This reverts commit 1642ce9a6959345388f97027e2b8b14154d02ba9.
=> Revert "refac: Removed writes to HIVE energy tables (#2796)"

source/databricks/calculation_engine/package/datamigration/migration_scripts/202409231300_update_table__wholesale_basis_data_internal__time_series_points.sql
This is part of a series of PRs that improves performance of the view `metering_point_time_series_v1`.
=> feat: Hydrate new time series points columns

source/databricks/settlement_report/settlement_report_job/domain/report_generator.py, source/databricks/settlement_report/settlement_report_job/domain/time_series_factory.py, source/databricks/settlement_report/settlement_report_job/domain/time_series_writer.py, source/dotnet/subsystem-tests/Features/SettlementReports/SettlementReportJobGeneratesZipScenario.cs
=> refac: Segregate factory and writer in settlement report 

source/dotnet/subsystem-tests/Features/SettlementReports/SettlementReportJobPerformanceScenario.cs
We need the name of the scenario class to be able to implement the filter in dh3-environments.
In a future PR we will then implement the actual test within the scenario class.
Part of: https://app.zenhub.com/workspaces/taskforce-settlement-reports-66d955bb0ac43f0036e87e5c/issues/gh/energinet-datahub/team-raccoons/841
=> feat: Empty performance scenario test

source/databricks/calculation_engine/package/datamigration/migration_scripts/202409251700_cluster__wholesale_basis_data_internal__time_series_points.sql, source/databricks/calculation_engine/package/datamigration/migration_scripts/202509251700_cluster__wholesale_basis_data_internal__time_series_points.sql
Add liquid clustering to improve query speed.
PR was created by renaming and modifying an old clustering script to keep the test suite fast.
=> feat: Optimize table `wholesale_basis_data_internal.time_series_points`

source/databricks/calculation_engine/package/calculation/calculation_core.py
=> feat: Filter out child from metering point time series basis data when energy calculation

source/databricks/calculation_engine/package/databases/wholesale_results_internal/energy_results.py
This reverts commit 3befff78419fccb56b87059378c60b1ead9bb371.
=> Revert "Added local checkpointing instead of caching. (#2861)"

source/databricks/calculation_engine/package/databases/wholesale_results_internal/energy_results.py
The attempt to mitigate period failures of calculations didn't seem to help. This PR reverts the code.
=> refac: Remove fix attempt

.github/dependabot.yml
Reverts Energinet-DataHub/opengeh-wholesale#2886
does no seem to work as i thought
=> Revert "refac: Update dependabot.yml with pip and docker"

source/databricks/settlement_report/settlement_report_job/domain/time_series/prepare_for_csv.py, source/databricks/settlement_report/tests/domain/test_execute_hourly_time_series.py, source/databricks/settlement_report/tests/domain/test_execute_quarterly_time_series.py
=> feat: Set energy_supplier_id as first column in time series

source/databricks/settlement_report/settlement_report_job/utils.py
=> refac: Use 'translate' to set decimal separator

source/databricks/settlement_report/settlement_report_job/domain/report_data_type.py, source/databricks/settlement_report/settlement_report_job/domain/report_name_factory.py, source/databricks/settlement_report/tests/domain/test_report_name_factory.py
=> feat: Add wholesale to report name factory

source/databricks/settlement_report/settlement_report_job/domain/csv_column_names.py, source/databricks/settlement_report/settlement_report_job/domain/csv_writer.py, source/databricks/settlement_report/settlement_report_job/domain/energy_results/prepare_for_csv.py, source/databricks/settlement_report/settlement_report_job/domain/time_series/prepare_for_csv.py, source/databricks/settlement_report/settlement_report_job/domain/wholesale_results/prepare_for_csv.py, source/databricks/settlement_report/tests/domain/test_csv_writer.py, source/databricks/settlement_report/tests/domain/test_execute_energy_results.py, source/databricks/settlement_report/tests/domain/test_execute_hourly_time_series.py, source/databricks/settlement_report/tests/domain/test_execute_quarterly_time_series.py, source/databricks/settlement_report/tests/domain/time_series/test_prepare_for_csv.py, source/databricks/settlement_report/tests/test_factories/time_series_csv_factory.py
=> refac: CsvColumnNames

source/databricks/settlement_report/settlement_report_job/domain/report_naming_convention.py, source/databricks/settlement_report/settlement_report_job/domain/wholesale_results/prepare_for_csv.py
=> refac: Use enums in report_naming_convention.py

source/databricks/settlement_report/settlement_report_job/domain/csv_writer.py, source/databricks/settlement_report/settlement_report_job/domain/report_generator.py, source/databricks/settlement_report/settlement_report_job/entry_point.py, source/databricks/settlement_report/tests/domain/test_execute_wholesale_results.py
=> feat: Execute wholesale results

source/databricks/settlement_report/settlement_report_job/domain/csv_column_names.py, source/databricks/settlement_report/settlement_report_job/domain/csv_writer.py, source/databricks/settlement_report/settlement_report_job/domain/energy_results/prepare_for_csv.py, source/databricks/settlement_report/settlement_report_job/domain/time_series/prepare_for_csv.py, source/databricks/settlement_report/settlement_report_job/domain/wholesale_results/prepare_for_csv.py, source/databricks/settlement_report/tests/domain/test_csv_writer.py, source/databricks/settlement_report/tests/domain/test_execute_energy_results.py, source/databricks/settlement_report/tests/domain/test_execute_hourly_time_series.py, source/databricks/settlement_report/tests/domain/test_execute_quarterly_time_series.py, source/databricks/settlement_report/tests/domain/test_execute_wholesale_results.py, source/databricks/settlement_report/tests/domain/time_series/test_prepare_for_csv.py, source/databricks/settlement_report/tests/test_factories/time_series_csv_factory.py
=> refac: Rename csv column names

source/databricks/settlement_report/settlement_report_job/domain/wholesale_results/read_and_filter.py, source/databricks/settlement_report/settlement_report_job/domain/wholesale_results/wholesale_results_factory.py, source/databricks/settlement_report/tests/domain/wholesale_results/test_wholesale_read_and_filter.py
=> feat: Add more filtering to wholesale results

source/databricks/settlement_report/tests/domain/test_execute_wholesale_results.py
=> refac: Add tests  for execute_wholesale_results

source/databricks/settlement_report/settlement_report_job/domain/wholesale_results/read_and_filter.py, source/databricks/settlement_report/tests/data_seeding/standard_wholesale_fixing_scenario_data_generator.py, source/databricks/settlement_report/tests/domain/test_execute_wholesale_results.py, source/databricks/settlement_report/tests/domain/wholesale_results/test_wholesale_read_and_filter.py
=> refac: amount_per_charge settlement report

source/databricks/settlement_report/settlement_report_job/domain/dataframe_utils/factory_filters.py, source/databricks/settlement_report/settlement_report_job/domain/repository_filtering.py, source/databricks/settlement_report/settlement_report_job/domain/wholesale_results/read_and_filter.py, source/databricks/settlement_report/tests/domain/charge_links/test_charge_links_read_and_filter.py
=> refac: Change charge link is tax according to business requirements

source/databricks/settlement_report/settlement_report_job/domain/report_generator.py, source/databricks/settlement_report/settlement_report_job/domain/task_type.py
=> feat: Add wholesale results to zip

source/databricks/settlement_report/settlement_report_job/domain/energy_results/energy_results_factory.py, source/databricks/settlement_report/settlement_report_job/domain/monthly_amounts/monthly_amounts_factory.py, source/databricks/settlement_report/settlement_report_job/domain/settlement_report_args_utils.py, source/databricks/settlement_report/settlement_report_job/domain/wholesale_results/wholesale_results_factory.py
=> refac: Use shared 'should_have_one_result_file_per_grid_area' method 

source/databricks/settlement_report/settlement_report_job/domain/report_generator.py
=> fix: Use correct path for zip task

source/databricks/settlement_report/settlement_report_job/infrastructure/order_by_columns.py, source/databricks/settlement_report/tests/data_seeding/standard_wholesale_fixing_scenario_data_generator.py, source/databricks/settlement_report/tests/domain/test_execute_monthly_amounts.py
The get_order_by function for MonthlyAmounts wasn't tested properly, and for SYO and Grid Area it was including instead of excluding a specific column which another part of the system was excluding, leading to analysis-exceptions.
=> fix: Fixed missing negation, and unit test covering it

source/databricks/settlement_report/settlement_report_job/entry_points/entry_point.py, source/databricks/settlement_report/settlement_report_job/entry_points/task_type.py
=> refac: Add missing charge price point entry point

source/databricks/settlement_report/settlement_report_job/entry_points/task_factory.py
=> refac: Add charge price points to task_factory.py

source/databricks/settlement_report/settlement_report_job/domain/monthly_amounts/prepare_for_csv.py, source/databricks/settlement_report/settlement_report_job/domain/monthly_amounts/read_and_filter.py, source/databricks/settlement_report/tests/domain/monthly_amounts/test_monthly_amounts_prepare_for_csv.py, source/databricks/settlement_report/tests/domain/monthly_amounts/test_monthly_amounts_read_and_filter.py, source/databricks/settlement_report/tests/entry_points/tasks/test_execute_monthly_amounts.py
=> fix: Include charge owner id column for monthly amounts

source/databricks/settlement_report/settlement_report_job/infrastructure/csv_writer.py, source/databricks/settlement_report/tests/infrastructure/test_csv_writer.py, source/databricks/settlement_report/tests/test_factories/time_series_points_csv_factory.py
=> fix: Only include chunk index in file name if more than one chunk

source/databricks/calculation_engine/tests/features/energy_calculation/given_minimal_standard_energy_scenario/then/energy_results/grid_loss.csv, source/databricks/calculation_engine/tests/features/readme.md, source/databricks/calculation_engine/tests/features/utils/assertion.py, source/databricks/calculation_engine/tests/helpers/data_frame_utils.py
=> test: Add calculation_result_id skip 

.docker/requirements.txt, source/databricks/calculation_engine/setup.py
=> chore: Bump some pip dependencies

.docker/requirements.txt, source/databricks/settlement_report/setup.py, source/databricks/settlement_report/tests/entry_points/test_entry_points.py
=> refac: Bump settlement report setup packages

.github/workflows/ci-dotnet.yml, source/dotnet/wholesale-api/Edi.UnitTests/Validators/WholesaleServicesRequest/WholesaleServicesRequestValidatorTests.cs
=> fix: Update test to not fail in December

.docker/requirements.txt, source/databricks/calculation_engine/package/datamigration/migration.py, source/databricks/calculation_engine/setup.py
Bump to newest version which simplifies the spark sql migration.
=> core: Bump python packages version to 5.0.1

.github/CODEOWNERS
https://app.zenhub.com/workspaces/team-fusion-6193fe815d79fc0011e741b1/issues/gh/energinet-datahub/team-the-outlaws/2847
=> 2847: remove Outlaws and Ratatosk

source/dotnet/subsystem-tests/Features/Calculations/BalanceFixingCalculationScenario.cs, source/dotnet/subsystem-tests/Features/Calculations/WholesaleFixingCalculationScenario.cs, source/dotnet/wholesale-api/Orchestrations.IntegrationTests/Fixtures/OrchestrationsAppFixture.cs, source/dotnet/wholesale-api/Orchestrations.IntegrationTests/Functions/Calculation/CalculationOrchestrationActivitiesTests.cs, source/dotnet/wholesale-api/Orchestrations.IntegrationTests/Functions/Calculation/CalculationOrchestrationStateTests.cs, source/dotnet/wholesale-api/Orchestrations.IntegrationTests/Functions/Calculation/CalculationTriggerTests.cs, source/dotnet/wholesale-api/Orchestrations.IntegrationTests/Functions/ScheduleCalculations/CalculationsSchedulerHandlerTests.cs, source/dotnet/wholesale-api/Orchestrations/Functions/Calculation/CalculationOrchestration.cs, source/dotnet/wholesale-api/Orchestrations/Functions/Calculation/CalculationTrigger.cs, source/dotnet/wholesale-api/Orchestrations/Functions/ScheduleCalculation/CalculationSchedulerHandler.cs, source/dotnet/wholesale-api/Orchestrations/Functions/ScheduleCalculation/CalculationStarter.cs
Disable calculation using the Wholsale subsystem, since they should now be run using the Process Manager. All unusing code regarding calculations will be deleted in a future PR.
=> feat: Disable calculations using the Wholesale subsystem

source/databricks/calculation_engine/tests/conftest.py, source/databricks/calculation_engine/tests/scenarios/conftest.py
added read_csv_path
story: 543
=> feat: added read_csv_path

.github/workflows/detect-changes.yml, .github/workflows/packages-publish.yml, source/dotnet/wholesale-integration-events-package/Contracts.Documentation/release-notes/release-notes.md, source/dotnet/wholesale-integration-events-package/Contracts/Contracts.csproj
https://github.com/tj-actions/changed-files/issues/2463#issuecomment-2727015784
=> Update tj-actions/changed-files to v46.0.1

source/databricks/calculation_engine/package/optimize_job/delta_optimization.py
=> fix: configure logging takes logging_settings

source/geh_wholesale/pyproject.toml, source/geh_wholesale/src/geh_wholesale/calculator_job.py, source/geh_wholesale/src/geh_wholesale/optimize_job/delta_optimization.py, source/geh_wholesale/tests/conftest.py, source/geh_wholesale/uv.lock
changed geh comment version to 5.5.2
=> upgraded geh commen version

source/geh_wholesale/pyproject.toml, source/geh_wholesale/tests/scenarios/wholesale_calculation/given_calculation_covers_multiple_ga/test_output.py, source/geh_wholesale/tests/scenarios/wholesale_calculation/given_es_and_brp_and_res_change/test_output.py, source/geh_wholesale/tests/scenarios/wholesale_calculation/given_extra_fees_or_subscriptions_are_added/test_output.py, source/geh_wholesale/tests/scenarios/wholesale_calculation/given_minimal_standard_wholesale_scenario/test_output.py, source/geh_wholesale/tests/scenarios/wholesale_calculation/given_no_active_price_points_for_price_elements/test_output.py, source/geh_wholesale/tests/scenarios/wholesale_calculation/given_price_elements_starts_or_stops/test_output.py, source/geh_wholesale/uv.lock
=> chore: bump opentelemetry

.github/workflows/cd.yml
=> ci: required deployment variables were missing

source/geh_wholesale/pyproject.toml, source/geh_wholesale/tests/entry_points/test_entry_points.py, source/geh_wholesale/uv.lock
add project script test
story: 649
=> feat: add project script test

.github/workflows/detect-changes.yml, global.json, source/dotnet/Directory.Build.props, source/dotnet/Wholesale.sln, source/dotnet/subsystem-tests/Features/Calculations/Fixtures/CalculationJobScenarioFixture.cs, source/dotnet/subsystem-tests/SubsystemTests.csproj
=> chore: Update to .NET 9

source/geh_wholesale/tests/databases/migrations_wholesale/repository/test_read_time_series_points.py
Implemented a method that creates a MigrationsWholesaleRepository for testing.
=> refac: Cleaned test_read_time_series_points
