Energinet-DataHub/opengeh-wholesale

source/dotnet/IntegrationTests.Core/IntegrationTests.Core.csproj, source/dotnet/IntegrationTests/IntegrationTests.csproj, source/dotnet/Tests/Tests.csproj
Bumps the following packages:
- [Energinet.DataHub.Core.TestCommon](https://github.com/Energinet-DataHub/geh-core) from 2.3.3 to 2.3.4.
- [Energinet.DataHub.Core.FunctionApp.TestCommon](https://github.com/Energinet-DataHub/geh-core) from 2.3.3 to 2.3.4.
- [coverlet.collector](https://github.com/coverlet-coverage/coverlet) from 3.1.0 to 3.1.2.
* #56 #52
=> Dependabot Bumps

source/dotnet/IntegrationTests.Core/Fixtures/WebApi/WholesaleWebApiFixture.cs, source/dotnet/IntegrationTests/WebApi/BearerTokenTests.cs, source/dotnet/IntegrationTests/WebApi/V1/BatchControllerTests.cs
Add test cases to verify that a token is validated when a request is processed.
The reason for changing the `ASPNETCORE_ENVIRONMENT` environmental variable is that it alters the code path in `Startup.cs`. With a value of `Testing` we skip the _Developer experience_ and match that of production.
``` csharp
if (env.IsDevelopment()) <- this prevents us from adding the middleware
{
app.UseDeveloperExceptionPage();
app.UseSwagger();
app.UseSwaggerUI();
}
else
{
// This middleware has to be configured after 'UseRouting' for 'AllowAnonymousAttribute' to work.
// We dont want JwtToken when running locally
app.UseMiddleware<JwtTokenMiddleware>();
}
```
=> Test user authentication

build/infrastructure/main/func-integrationeventlistener.tf
Name of KV secret was changed in "shared resources" by this PR: https://github.com/Energinet-DataHub/geh-shared-resources/pull/232
Current PR ensures we use the new KV secret name.
=> Update kv secret name to match new name in "shared resources"

source/databricks/package/integration_events_persister.py
Adding storedTime of when data was stored in the parquet table. This is used for partitioning. And for filtering on time when we want to know how data looked at a specific time in history
* #32
=> add stored time

source/dotnet/IntegrationTests/Fixture/Database/SenderDatabaseManager.cs, source/dotnet/IntegrationTests/Fixture/Database/WholesaleDatabaseManager.cs, source/dotnet/ProcessManager/Program.cs, source/dotnet/Sender/Program.cs, source/dotnet/WebApi/Configuration/ServiceCollectionExtensions.cs
Try to improve database recilliency with Entity Framework. See
- [this documentation](https://docs.microsoft.com/en-us/ef/core/miscellaneous/connection-resiliency)
- [this error](https://portal.azure.com/#view/AppInsightsExtension/DetailsV2Blade/ComponentId~/%7B%22SubscriptionId%22%3A%220f12dae0-3f9d-46ae-93a7-7091ff0b950d%22%2C%22ResourceGroup%22%3A%22rg-DataHub-SharedResouces-B-002%22%2C%22Name%22%3A%22appi-shared-sharedres-b-002%22%2C%22LinkedApplicationType%22%3A0%2C%22ResourceId%22%3A%22%252Fsubscriptions%252F0f12dae0-3f9d-46ae-93a7-7091ff0b950d%252FresourceGroups%252Frg-DataHub-SharedResouces-B-002%252Fproviders%252FMicrosoft.Insights%252Fcomponents%252Fappi-shared-sharedres-b-002%22%2C%22ResourceType%22%3A%22microsoft.insights%252Fcomponents%22%2C%22IsAzureFirst%22%3Afalse%7D/DataMo …
=> fix: Try to improve database outtage related errors

source/dotnet/IntegrationEventListener/IntegrationEventListener.csproj
Error in b-002 [here](https://portal.azure.com/#view/AppInsightsExtension/DetailsV2Blade/ComponentId~/%7B%22SubscriptionId%22%3A%220f12dae0-3f9d-46ae-93a7-7091ff0b950d%22%2C%22ResourceGroup%22%3A%22rg-DataHub-SharedResouces-B-002%22%2C%22Name%22%3A%22appi-shared-sharedres-b-002%22%2C%22LinkedApplicationType%22%3A0%2C%22ResourceId%22%3A%22%252Fsubscriptions%252F0f12dae0-3f9d-46ae-93a7-7091ff0b950d%252FresourceGroups%252Frg-DataHub-SharedResouces-B-002%252Fproviders%252FMicrosoft.Insights%252Fcomponents%252Fappi-shared-sharedres-b-002%22%2C%22ResourceType%22%3A%22microsoft.insights%252Fcomponents%22%2C%22IsAzureFirst%22%3Afalse%7D/DataModel~/%7B%22eventId%22%3A%22828e83ab-17c5-11ed-90e0-000d3aac8608%22%2C%22timestamp%22%3A%222022-08-09T09%3A26%3A59.127Z%22%2C%22cacheId%22%3A%2212f52e07-6fa6- …
=> fix: Update market participant package to fix receival of events

build/infrastructure/main/dbwj-calculator.tf, build/infrastructure/main/dbwj-integrationeventspersister.tf
```max_retries``` does not apply to the runs when not placed inside the ```tasks``` section. I cannot find documentation mentioning this, but it appears to work now.
```max_concurrent_runs``` and ```always_running``` are not affected.
=> bug: max_retries not applying

source/dotnet/Application/Batches/BatchApplicationService.cs, source/dotnet/Domain/BatchAggregate/Batch.cs, source/dotnet/Tests/Domain/BatchAggregate/BatchTests.cs
There does not appear to be a way to restart jobs without triggering a new run (and a new JobRunId). A batch must therefore be made aware of the new JobRunId after a restart. 
Alternatively, separating the cluster from job creation in TF may prevent the jobs from shutting down. However, the documentation says: "We strongly suggest to use new_cluster for greater reliability."
#159
=> feat: Restart cancelled runs.

.github/actions/publish-release-contents/action.yml, build/infrastructure/env/t-001/mssql-database_override.tf, build/infrastructure/env/u-001/mssql-database_override.tf, build/infrastructure/env/u-002/mssql-database_override.tf, build/infrastructure/main/locals.tf, build/infrastructure/main/mssql-database.tf, build/infrastructure/main/mssqldb-applicationaccess.tf, build/infrastructure/main/variables.tf
Enable Identity based Access Management on the SQL database used by the domain.
The application hosts (web apps and function apps) are assigned as reader and writes on the database, and the developer group is assigned as readers.
A SQL authentication connection string still exists as this is currently needed to perform data migrations.
=> SQL database - use new TF module to use IAM

source/databricks/package/__init__.py, source/databricks/package/calculator_job.py, source/databricks/tests/integration/calculator/test_calculator.py
The calculator used in production was no longer exposed in `__init__`. Resulting in a `TypeError: 'module' object is not callable` error. 
this PR will reintroduce it, along with a test that verifies that the `calculator` can run.
* #32
=> fix: calculator used in production

source/databricks/package/balance_fixing_total_production.py, source/databricks/tests/integration/calculator/balance_fixing_total_production/test_get_enriched_time_series_points_df.py
According to SME time series with the same registration time as earlier received time series must be rejected by validation. Thus wholesale does not need to anticipate anything else than the registration date time already being both unique and decisive.
* #32
=> fix: Remove wrong/irrelevant secondary sorting of time series points

source/databricks/package/balance_fixing_total_production.py, source/databricks/tests/integration/calculator/balance_fixing_total_production/test_get_metering_points_df.py
According to team Batman the correct ordering for replay of metering point created and connected events are by effective date.
* #32
=> fix: Order metering point events by effective date

build/infrastructure/main/kv-shared-resources-sql.tf, build/infrastructure/main/mssql-database.tf
Move the SQL database into the SQL Server elastic pool.
This will not require backup, as no data is lost
=> use elastic pool

.github/workflows/ci.yml, source/databricks/package/balance_fixing_total_production.py, source/databricks/package/calculator_job.py, source/databricks/tests/integration/calculator/test_calculator_job.py
The entry point for the calculator_job start() must be parameterless for it to be called trough the wheel. 
zoneinfo was not in use so it is no longer imported
=> fix: calculator start must be parameterless

source/databricks/package/calculator_job.py
the start method of the calculator should be parameterless and only be renamed along with the package's entry point. So this PR will add a small comment to help remember this.
=> refac: start() with comment

.github/workflows/packages-publish.yml
Needed in order to test prerelease of NuGet package in [this PR](#359).
Pre-release of NuGet packages from PRs require the workflow with the dispatch trigger to exist in main. The remainder of the workflow will be added in the other PR.
* #17
=> feat: Enable triggering NuGet prerelease

source/dotnet/Services/Infrastructure/BasisData/BatchFileManager.cs
`PeekEndpoint` failed with a 404 after inspecting the URI used to get the result
https://stdatalakesharedresu001.dfs.core.windows.net/processes?resource=filesystem&directory=results%2Fbatch_id%3D195e433b-a751-49b2-8a32-3f3a90687d65%2Fgrid_area%3DGridAreaCode%20%7B%20Code%20%3D%20806%20%7D&recursive=false&upn=false
The path using the GridAreaCode appears to be missing the class instead of the code value
* #17
=> bug: read result path with code value

source/dotnet/Services/IntegrationTests/Hosts/WebApiIntegrationTestHost.cs, source/dotnet/Services/IntegrationTests/WebApi/WebApiTests.cs, source/dotnet/Services/WebApi/Configuration/ServiceCollectionExtensions.cs, source/dotnet/Services/WebApi/Startup.cs
=> fix: revert to read db connectionstring from configuration

source/dotnet/Services/IntegrationEventListener/MarketParticipant/EnergySupplierChangedDto.cs, source/dotnet/Services/Tests/IntegrationEventListener/MarketParticipant/EnergySupplierChangedDtoFactoryTests.cs
Market participant representation of the unique identifier for the metering point is called AccountpointId, for Wholesale perspective, this becomes unnecessary when we wish to window our metering points downstream.
* #201
=> refac: AccountpointId -> MeteringPointId

source/databricks/package/balance_fixing_total_production.py, source/databricks/tests/integration/calculator/balance_fixing_total_production/test_get_master_basis_data.py
When master basis data was created, the fields `VALIDFROM` and `VALIDTO` was populated from the metering points `effectiveDate` and the `toEffectiveDate`. Which was incorrect in some cases. 
Metering points with an `effectiveDate` before the requested aggregation start period should have the period start as `VALIDOFROM`.
Metering points with an `toEffectiveDate` after the requested aggregation end period should have the period end as `VALIDOTO`.
There is a picture on the referenced story to better illustrate the requested changes.
* #201
=> feat: Masterbasisdata dates changes

source/databricks/package/balance_fixing_total_production.py, source/databricks/tests/integration/calculator/balance_fixing_total_production/test_get_metering_points_df.py
The connection state was unhandled in the case of the period created from the `EnergySupplierChanged` event. 
This PR will make sure periods that area created from that event have the last known connection state from the events with the same `MeteringpointId`
* #201
=> fix: Balancefixing window connection state fix energysupplierchanged

.devcontainer/devcontainer.json
Changes the python language server from Jedi to Pylance.
Pylance is a more advanced language server than Jedi and provides a lot more help when coding, this includes the ability to see if a import is used or not
* #0000
=> refac:Replace Jedi with Pylance

source/databricks/package/integration_events_persister_streaming.py, source/databricks/tests/integration/integration_events_persister/test_integration_events_persister.py
Streaming cloud not be started due to missing argument. The argument was passed in [this pr](https://github.com/Energinet-DataHub/dh3-infrastructure/pull/33)
This PR will parse the argument and mark is as required. (The required flag is missing from the calculator job, ill create another PR to update it)
* #508
=> bug: eventsstreaming is missing log-level argument

source/databricks/package/datamigration/data_lake_file_manager.py
=> fix: use storage url (and not storage name) to initialize DataLakeServiceClient

source/dotnet/Contracts/BatchDtoV2.cs, source/dotnet/Contracts/GridAreaDto.cs, source/dotnet/Packages/Client/Client.csproj, source/dotnet/Services/Application/Application.csproj, source/dotnet/Services/Application/Batches/BatchDto.cs, source/dotnet/Services/Application/Batches/BatchDtoMapper.cs, source/dotnet/Services/WebApi/Controllers/V2/BatchDtoV2Mapper.cs
This PR renames BatchGridAreaDto to GridAreaDto to better reflect that it is a grid area object and not a specific grid area on a batch object.
The next PR will create a new dto with the name BatchGridAreaDto that contains a batch with a specific grid area and its processes.
* #317
=> Refac: Rename BatchGridAreaDto to GridAreaDto

source/databricks/package/balance_fixing_total_production.py, source/databricks/tests/integration/calculator/balance_fixing_total_production/test_get_output_master_basis_data_df.py
We were missing the field `TYPEOFMP` due to a missing refactor since we transitioned to the static metering point dataset.
* #502
=> fix: TYPEOFMP in masterdata

source/databricks/setup.py
=> fix: Add missing `python-dateutil` module to wheel

source/databricks/setup.py
This change will make sure the `tests` folder is not included when building the wheel.
* #610
=> build: remove test folder from the wheel

source/contracts/internal/calculation-job-parameters-reference.txt, source/databricks/package/calculator_job.py, source/databricks/tests/integration/calculator/test_calculator_job.py, source/dotnet/Services/Infrastructure/JobRunner/DatabricksCalculatorJobParametersFactory.cs
This PR will remove any remnants of the "snapshot-datetime". I have made sure that the `calculator-job` is not called with the parameter any longer.
https://github.com/Energinet-DataHub/dh3-infrastructure/blob/main/wholesale/terraform/main/dbwj-calculator.tf
* #625
=> refac: remove snapshot-datetime

source/databricks/tests/integration/calculator/steps/wholesale/test_subscription_calculators.py
Some tests were left out on my last PR. This PR will reintroduce some tests in `test_subscription_calculators.py`
* #625
=> refac: comment in tests in test_subscription_calculators

source/dotnet/Services/Domain/BatchAggregate/Batch.cs, source/dotnet/Services/DomainTests/WebApiTests.cs, source/dotnet/Services/Infrastructure/JobRunner/DatabricksCalculatorJobParametersFactory.cs, source/dotnet/Services/IntegrationTests/ProcessManager/BasisDataApplicationServiceTests.cs, source/dotnet/Services/IntegrationTests/ProcessManager/BatchApplicationServiceTests.cs, source/dotnet/Services/IntegrationTests/TestCommon/Infrastructure/BatchRepositoryTests.cs, source/dotnet/Services/IntegrationTests/TestCommon/ProcessManager/SubmitCreatedBatchesEndpointTests.cs, source/dotnet/Services/IntegrationTests/TestCommon/WebApi/BatchControllerTests.cs, source/dotnet/Services/Tests/Application/BatchDtoMapperTests.cs, source/dotnet/Services/Tests/Domain/BatchAggregate/BatchBuilder.cs, source/dotnet/Services/Tests/Domain/BatchAggregate/BatchFactoryTests.cs, source/dotnet/Services/Tests/Domain/BatchAggregate/BatchTests.cs, source/dotnet/Services/Tests/Infrastructure/JobRunner/DatabricksCalculatorJobParametersFactoryTests.cs
Observed behaviour:
- 1 millisecond offset from midnight (period end received from BFF) may cause missing some calculation input
- Generated basis data reports has wrong period end time (off by 1 millisecond from midnight)
Decided solution:
- Accept - and validate - that period end received from BFF is exactly one millisecond before midnight.
- Invoke calculator job with a period end value adjusted one millisecond to be exactly at midnight in order to prevent missing required calculation input
- (Will be done in another PR) Wholesale web API returns HTTP BadRequest upon unexpected period end time
* #664
=> fix: Validate batch period end

source/databricks/package/calculator_job.py
This Pr will change the call to `exit()` when exiting the calculator if the storage is locked to `sys.exit()`. The error is observed on this run here: https://adb-5870161604877074.14.azuredatabricks.net/?o=5870161604877074#job/1119732257340915/run/2667721
A fix was found here: https://stackoverflow.com/questions/45066518/nameerror-name-exit-is-not-defined
* #199
=> fix: calculator cant call exit

source/databricks/package/schemas/metering_point_period_schema.py, source/databricks/package/schemas/time_series_point_schema.py
Metering points of type D02, D17, D18, D20, and D99 are not used in wholesale and should be omitted.
Time series quantity must always be in kWh (kilo Watt hour).
* #690
=> refac: Make migration contracts more specific

source/dotnet/Services/Application/ProcessResult/ProcessStepResultApplicationService.cs, source/dotnet/Services/Tests/Application/ProcessResult/ProcessResultApplicationServiceTests.cs
It is best practice to design for globalization and localization. This involves developing in a culture neutral way. See more [here](https://learn.microsoft.com/en-us/dotnet/core/extensions/globalization-and-localization).
The added test would fail on host systems not using a culture (number formatting) where '.' (dots) are used as decimal separators.
* #199
=> fix: Fix culture error while parsing decimal from string

source/databricks/tests/integration/calculator/balance_fixing/test_get_enriched_time_series_points_df.py, source/databricks/tests/integration/calculator/test_calculator_job.py
Adding a test that verifies that the number of rows in the result is as expected. The test data start/end at 23:00, so we adjust the batch period to this period also.
* #199
=> Added test__result_file_have_correct_number_of_rows_based_on_period

source/databricks/package/balance_fixing.py, source/databricks/package/calculator_job.py, source/databricks/package/file_writers/basis_data_writer.py, source/databricks/package/file_writers/process_step_result_writer.py, source/databricks/package/infrastructure.py, source/databricks/tests/conftest.py, source/databricks/tests/helpers/assert_calculation_file_path.py, source/databricks/tests/integration/calculator/file_writers/test_process_step_result_writer.py, source/databricks/tests/integration/calculator/test_calculator_job.py
With this PR, ProcessStepResultWriter is responsible for defining the path where results are stored - calculator_job is no longer responsible for constucting parts of the relative path. 
It is now also possible to move the tests to test_process_step_result_writwer
* #199
=> refac: move file path contract test to test_process_step_result_writer

source/dotnet/Services/DatabaseMigration/DatabaseMigration.csproj, source/dotnet/Services/DatabaseMigration/Scripts/202302031300_Fix_Batch_PeriodEnds.sql, source/dotnet/Services/Domain/BatchAggregate/Batch.cs, source/dotnet/Services/Infrastructure/Calculations/DatabricksCalculationParametersFactory.cs, source/dotnet/Services/IntegrationTests/Fixtures/TestHelpers/Periods.cs, source/dotnet/Services/IntegrationTests/Infrastructure/BatchRepositoryTests.cs, source/dotnet/Services/IntegrationTests/ProcessManager/BatchApplicationServiceTests.cs, source/dotnet/Services/IntegrationTests/ProcessManager/PublishProcessCompletedIntegrationEventEndpointTests.cs, source/dotnet/Services/IntegrationTests/ProcessManager/SettlementReportApplicationServiceTests.cs, source/dotnet/Services/IntegrationTests/ProcessManager/SubmitCreatedBatchesEndpointTests.cs, source/dotnet/Services/IntegrationTests/WebApi/BatchControllerTests.cs, source/dotnet/Services/UnitTests/Domain/BatchAggregate/BatchBuilder.cs, source/dotnet/Services/UnitTests/Domain/BatchAggregate/BatchFactoryTests.cs, source/dotnet/Services/UnitTests/Domain/BatchAggregate/BatchTests.cs, source/dotnet/Services/UnitTests/Infrastructure/Calculations/DatabricksCalculatorJobParametersFactoryTests.cs, source/dotnet/Services/WebApi/Controllers/V2/BatchController.cs
Move front-end related workaround of period ends being 1 ms before midnight to the boundaries of the web API. This solves the error of publishing batch completed integration events with bad period end.
* #0000
=> fix: Bug fix and move "period end off by 1ms hack" to boundary of web API

source/dotnet/Services/Application/ProcessStep/IProcessStepApplicationService.cs, source/dotnet/Services/Application/ProcessStep/ProcessStepApplicationService.cs, source/dotnet/Services/WebApi.IntegrationTests/WebApi/ProcessStepControllerTests.cs, source/dotnet/Services/WebApi.IntegrationTests/WebApi/V3/ProcessStepBalanceResponsiblePartyTests.cs, source/dotnet/Services/WebApi.IntegrationTests/WebApi/V3/ProcessStepEnergySupplierTests.cs, source/dotnet/Services/WebApi.IntegrationTests/WebApi/V3/ProcessStepResultTests.cs, source/dotnet/Services/WebApi.UnitTests/Application/ProcessStep/ProcessStepApplicationServiceTests.cs, source/dotnet/Services/WebApi.UnitTests/Infrastructure/SettlementReport/SettlementReportRepositoryTests.cs, source/dotnet/Services/WebApi/Configuration/ServiceCollectionExtensions.cs, source/dotnet/Services/WebApi/V2/BatchController.cs, source/dotnet/Services/WebApi/V2/BatchDtoV2Mapper.cs, source/dotnet/Services/WebApi/V2/IBatchDtoV2Mapper.cs, source/dotnet/Services/WebApi/V2/ProcessStepControllerV21.cs, source/dotnet/Services/WebApi/V2/ProcessStepControllerV22.cs, source/dotnet/Services/WebApi/V2/ProcessStepControllerV23.cs, source/dotnet/Services/WebApi/V2/SettlementReportController.cs, source/dotnet/Services/WebApi/V3/ActorDto.cs, source/dotnet/Services/WebApi/V3/ProcessStepBalanceResponsibleParty/ProcessStepBalanceResponsiblePartyController.cs, source/dotnet/Services/WebApi/V3/ProcessStepEnergySupplier/ProcessStepEnergySupplierController.cs, source/dotnet/Services/WebApi/V3/ProcessStepResult/ProcessStepResultController.cs
This pr will refactor the ProcessStepApplicationService to no longer be coupled with the exposed models: `ProcessResultRequstDto `and `ProcessResultRequstDtoV2`. 
Some namespaces were not updated, this PR will also update them.
* #782
=> refac: ProcessStepApplicationService

source/databricks/package/steps/aggregation/__init__.py, source/databricks/package/steps/aggregation/aggregators.py, source/databricks/tests/integration/calculator/steps/aggregation/test_flex_consumption_ga_brp_es.py, source/databricks/tests/integration/calculator/steps/aggregation/test_non_profiled_consumption_ga_brp_es.py, source/databricks/tests/integration/calculator/steps/aggregation/test_production_ga_brp_es.py
Change private methods in aggregators.py to use one underscore instead of two, to follow python standards.
Remove the private method from __init__.py and import the private method directly into the tests files that use the method
* #782
=> fix: use one underscore for private methods

source/databricks/package/balance_fixing.py, source/databricks/package/codelists/grouping.py, source/databricks/package/constants/colname.py, source/databricks/package/constants/partition_key_name.py, source/databricks/package/file_writers/basis_data_writer.py, source/databricks/package/file_writers/process_step_result_writer.py, source/databricks/package/infrastructure.py, source/databricks/tests/integration/calculator/file_writers/test_actors_writer.py, source/databricks/tests/integration/calculator/file_writers/test_process_step_result_writer.py, source/databricks/tests/integration/calculator/test_calculator_job.py
Write data to delta table (while also still writing to the datalake as before). The delta table is stored in the calculation-output (next to all the batches). We now use 'time_series_type' and 'grouping' as partitioning when we store to the normal data lake. This means that we need to use the 'append' safemode. This was done to streamline the code a bit - hopefully we will anyway eventually remove the normal datalake writings.
With the PR the delta lake will have the following columns:  batch_id, time_series_type, grid_area, quarter_time, quality, grouping, balance_responsible_id, energy_supplier_id
* #892
=> refac: write result to delta table

source/contracts/internal/calculation-job-parameters-reference.txt, source/databricks/package/args_helper.py, source/dotnet/Services/WebApi.UnitTests/Infrastructure/Calculations/DatabricksCalculatorJobParametersFactoryTests.cs
=> fix: Handle 0-prefixed grid area codes correctly in calculator job args

source/databricks/package/balance_fixing.py, source/databricks/tests/integration/calculator/test_calculator_job.py
=> bug: switched result to consumption for es_brp_ga

source/dotnet/Services/WebApi/V2/BatchControllerV21.cs, source/dotnet/Services/WebApi/V2/ProcessStepControllerV21.cs, source/dotnet/Services/WebApi/V2/ProcessStepControllerV22.cs, source/dotnet/Services/WebApi/V2/ProcessStepControllerV23.cs, source/dotnet/Services/WebApi/V2/ProcessStepControllerV24.cs, source/dotnet/Services/WebApi/V3/ProcessStepBalanceResponsibleParty/ProcessStepBalanceResponsiblePartyController.cs, source/dotnet/Services/WebApi/V3/ProcessStepEnergySupplier/ProcessStepEnergySupplierController.cs, source/dotnet/Services/WebApi/V3/ProcessStepResult/ProcessStepResultController.cs
EDI no longer uses the WebAPI, so we no longer have to `[AllowAnonymous]` on the controller methods they used.
* #886
=> refac: removed [AllowAnonymous] from WholesaleAPI

source/dotnet/wholesale-api/WebApi.UnitTests/WebApi/V3/ProcessStepResultFactoryTests.cs, source/dotnet/wholesale-api/WebApi/V3/ProcessStepResult/ProcessStepResultDto.cs, source/dotnet/wholesale-api/WebApi/V3/ProcessStepResult/ProcessStepResultFactory.cs
The `TimeSeriesType` was missing from the `ProcessStepResultDto` in the V3 API.
* #0000
=> feat: add TimeSeriesType to ProcessStepResultDto in V3

source/databricks/calculation-engine/package/datamigration/migration_scripts/202304191400_Add_result_table.py, source/databricks/calculation-engine/package/file_writers/process_step_result_writer.py, source/databricks/calculation-engine/package/schemas/results_schema.py, source/databricks/calculation-engine/tests/datamigration/test_migration_scripts.py, source/databricks/calculation-engine/tests/integration/calculator/file_writers/test_process_step_result_writer.py
It appears that writing to delta from pyspark requires the same ordering of the columns in the dataframe as of the columns in the delta table.
=> fix: Correct bad schema ordering

source/dotnet/wholesale-api/WebApi/Configuration/ServiceCollectionExtensions.cs
=> fix: use credential when creating DataLakeServiceClient in WebApi

source/dotnet/domain-tests/Fixtures/AuthorizedClientFixture.cs, source/dotnet/domain-tests/WebApiTests.cs
this PR changes timeout handling in domain test to CancellationTokenSource.CancelAfter instead of maxWaitTime on RecceiveMessageAsync which does not seem to work when deployed.
Also added a autodelete feature on the service bus subscription being created for the test, after being idle for 1 hour it will delete itself.
* #0000
=> refac: use more explicit timeout on domain test

source/dotnet/wholesale-integration-events-package/Contracts.Documentation/release-notes/release-notes.md, source/dotnet/wholesale-integration-events-package/Contracts/Contracts.csproj
The EDI solution has a problem with the generated NuGet package. Some newer values are missing. 
This PR bumps the version number to see if the new NuGet package contains the newer values. This is not a fix.
For example:
WholeSale
EDI
[## References](https://app.zenhub.com/workspaces/phoenix--60a6105157304f00119be86e/issues/gh/energinet-datahub/team-batman/22)
* #0000
=> refac: bumped contracts verison

source/dotnet/Directory.Build.props
=> chore(deps): bump Microsoft.CodeAnalysis.NetAnalyzers from 7.0.1 to 7.0.3 in /source/dotnet

source/dotnet/domain-tests/DomainTests.csproj, source/dotnet/wholesale-api/Batches/Batches.IntegrationTests/Batches.IntegrationTests.csproj, source/dotnet/wholesale-api/Batches/Batches.UnitTests/Batches.UnitTests.csproj, source/dotnet/wholesale-api/CalculationResults/CalculationResults.IntegrationTests/CalculationResults.IntegrationTests.csproj, source/dotnet/wholesale-api/CalculationResults/CalculationResults.UnitTests/CalculationResults.UnitTests.csproj, source/dotnet/wholesale-api/Events/Events.IntegrationTests/Events.IntegrationTests.csproj, source/dotnet/wholesale-api/Events/Events.UnitTests/Events.UnitTests.csproj, source/dotnet/wholesale-api/Test.Core/Test.Core.csproj, source/dotnet/wholesale-api/WebApi.IntegrationTests/WebApi.IntegrationTests.csproj, source/dotnet/wholesale-api/WebApi.UnitTests/WebApi.UnitTests.csproj
The certificte used in Azurite has been expired, which means that integration tests that use Azurite fails. This has been fixed in the latest version of TestCommon.
* #0000
=> chore(deps): bump TestCommon from 4.3.1 to 4.3.2

source/dotnet/domain-tests/DomainTests.csproj, source/dotnet/wholesale-api/Batches/Batches.IntegrationTests/Batches.IntegrationTests.csproj, source/dotnet/wholesale-api/Batches/Batches.UnitTests/Batches.UnitTests.csproj, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/CalculationResults.Infrastructure.csproj, source/dotnet/wholesale-api/CalculationResults/CalculationResults.IntegrationTests/CalculationResults.IntegrationTests.csproj, source/dotnet/wholesale-api/CalculationResults/CalculationResults.UnitTests/CalculationResults.UnitTests.csproj, source/dotnet/wholesale-api/Events/Communication/Communication/Communication.csproj, source/dotnet/wholesale-api/Events/Events.Infrastructure/Events.Infrastructure.csproj, source/dotnet/wholesale-api/Events/Events.IntegrationTests/Events.IntegrationTests.csproj, source/dotnet/wholesale-api/Events/Events.UnitTests/Events.UnitTests.csproj, source/dotnet/wholesale-api/Test.Core/Test.Core.csproj, source/dotnet/wholesale-api/WebApi.IntegrationTests/WebApi.IntegrationTests.csproj, source/dotnet/wholesale-api/WebApi.UnitTests/WebApi.UnitTests.csproj
Bumps [Azure.Storage.Files.DataLake](https://github.com/Azure/azure-sdk-for-net) from 12.14.0 to 12.15.0.
Bumps [Energinet.DataHub.Core.JsonSerialization](https://github.com/Energinet-DataHub/geh-core) from 2.2.6 to 2.2.7.
Bumps [Google.Protobuf](https://github.com/protocolbuffers/protobuf) from 3.23.3 to 3.23.4.
Bumps [Grpc.Tools](https://github.com/grpc/grpc) from 2.56.0 to 2.56.2.
Bumps [Energinet.DataHub.Core.FunctionApp.TestCommon](https://github.com/Energinet-DataHub/geh-core) from 4.3.2 to 4.3.3.
Bumps [Energinet.DataHub.Core.TestCommon](https://github.com/Energinet-DataHub/geh-core) from 4.3.2 to 4.3.3.
* #0000
=> chore(deps): bumps

source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/SqlStatements/SqlStatementClient.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.UnitTests/Infrastructure/SqlStatements/SqlStatementClientBuilder.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.UnitTests/Infrastructure/SqlStatements/SqlStatementClientTests.cs
This PR fixes a bug where the client in a loop doesn't use the new response from the Databricks API, but continues to use the original response.
In addition, the client keeps querying for status results without a back-off algorithm. This has been added to lower the immense load on the API.
* #1314
=> fix: Fix bugs in `SqlStatementClient`

source/databricks/calculation-engine/tests/integration/calculation_input/test_calculation_input_reader.py
The added tests that check input table schemas (Databricks) don't change.
https://app.zenhub.com/workspaces/mandalorian-5fd22a1a59e4740018f5ab5a/issues/gh/energinet-datahub/green-energy-hub/470
=> test: Added schema compare tests (input reader)

source/dotnet/wholesale-api/WebApi.UnitTests/WebApi/HealthChecks/DataBricks/DatabricksJobsApiHealthCheckTests.cs, source/dotnet/wholesale-api/WebApi.UnitTests/WebApi/HealthChecks/DataBricks/DatabricksSqlStatementsApiHealthCheckTests.cs, source/dotnet/wholesale-api/WebApi.UnitTests/WebApi/HealthChecks/DataLake/DataLakeHealthCheckTests.cs
Added tests of Databricks Health Checks to verify the hourly interval, that is, the open period in which health checks are made. It can for example be from 8am to 4pm. The functionality is implemented to avoid flooding the dependency and thereby reducing the cost.
https://app.zenhub.com/workspaces/mandalorian-5fd22a1a59e4740018f5ab5a/issues/gh/energinet-datahub/opengeh-wholesale/1366
=> test: Added tests of Databricks Health Checks

source/databricks/calculation-engine/package/calculation/energy/aggregators.py, source/databricks/calculation-engine/package/calculation/energy/transformations/aggregation_result_formatter.py, source/databricks/calculation-engine/package/calculation/energy/transformations/apply_grid_loss_adjustment.py, source/databricks/calculation-engine/package/common/schemas.py, source/databricks/calculation-engine/tests/calculation/energy/aggregators/test_flex_consumption.py, source/databricks/calculation-engine/tests/calculation/energy/aggregators/test_flex_consumption_ga_brp_es.py, source/databricks/calculation-engine/tests/calculation/energy/aggregators/test_non_profiled_consumption.py, source/databricks/calculation-engine/tests/calculation/energy/aggregators/test_non_profiled_consumption_ga_brp_es.py, source/databricks/calculation-engine/tests/calculation/energy/aggregators/test_production.py, source/databricks/calculation-engine/tests/calculation/energy/aggregators/test_production_ga_brp_es.py, source/databricks/calculation-engine/tests/calculation/energy/exchange_aggregators/test_net_exchange_grid_area_aggregation.py, source/databricks/calculation-engine/tests/calculation/energy/exchange_aggregators/test_net_exchange_neighbour.py, source/databricks/calculation-engine/tests/calculation/energy/grid_loss_calculator/test_grid_loss_calculation.py, source/databricks/calculation-engine/tests/calculation/energy/grid_loss_calculator/test_negative_grid_loss.py, source/databricks/calculation-engine/tests/calculation/energy/grid_loss_calculator/test_positive_grid_loss.py, source/databricks/calculation-engine/tests/calculation/energy/grid_loss_calculator/test_total_consumption.py, source/databricks/calculation-engine/tests/calculation/energy/transformations/test_adjust_flex_consumption.py, source/databricks/calculation-engine/tests/calculation/energy/transformations/test_adjust_production.py, source/databricks/calculation-engine/tests/calculation/energy/transformations/test_aggregation_result_formatter.py, source/databricks/calculation-engine/tests/common/test_schemas.py
- Stop using production function `create_dataframe_from_aggregation_result_schema` to generate test data.
- Improve schema checking.
The final goal in future PRs is to get rid of `create_dataframe_from_aggregation_result_schema`.
=> refac: Improve `aggregation_result_format` and usage

source/dotnet/wholesale-api/WebApi.IntegrationTests/WebApi.IntegrationTests.csproj
This PR removes a few unused dependencies in `WebApi.IntegrationTests`. They probably originate from a copy of IntegrationTests in the archived Charges domain ;-)
=> chore: Remove unused dependencies

source/dotnet/wholesale-api/Edi.UnitTests/Validators/AggregatedTimeSeriesRequestValidatorTests.cs, source/dotnet/wholesale-api/Edi.UnitTests/Validators/EnergySupplierValidatorTest.cs, source/dotnet/wholesale-api/Edi/Validation/AggregatedTimeSerie/Rules/EnergySupplierFieldValidationRule.cs, source/dotnet/wholesale-api/Edi/Validation/ValidationError.cs
Add new validation message for when the `EnergySupplier` field doesn't match `RequestedByActorId` after new requirements.
Task: https://github.com/Energinet-DataHub/opengeh-wholesale/pull/1520
=> feat: Add new validation message to EnergySupplier validator

source/dotnet/wholesale-api/CalculationResults/CalculationResults.UnitTests/Infrastructure/SqlStatements/Mappers/WholesaleResult/ChargeTypeMapperTests.cs
Added a test that compares the charge type contract against the model. 
https://app.zenhub.com/workspaces/mandalorian-5fd22a1a59e4740018f5ab5a/issues/gh/energinet-datahub/green-energy-hub/476
=> test: added contract test of charge type

source/dotnet/wholesale-api/Edi.UnitTests/Builders/AggregatedTimeSeriesRequestBuilder.cs, source/dotnet/wholesale-api/Edi.UnitTests/Validators/AggregatedTimeSeriesRequestValidatorTests.cs, source/dotnet/wholesale-api/Edi.UnitTests/Validators/BalanceResponsibleValidatorTest.cs, source/dotnet/wholesale-api/Edi.UnitTests/Validators/EnergySupplierValidatorTest.cs, source/dotnet/wholesale-api/Edi/Contracts/AggregatedTimeSeriesRequest.proto, source/dotnet/wholesale-api/Edi/EdiRegistration.cs, source/dotnet/wholesale-api/Edi/Validation/ActorNumberValidationHelper.cs, source/dotnet/wholesale-api/Edi/Validation/AggregatedTimeSerie/Rules/BalanceResponsibleValidationRule.cs, source/dotnet/wholesale-api/Edi/Validation/AggregatedTimeSerie/Rules/EnergySupplierValidationRule.cs, source/dotnet/wholesale-api/Edi/Validation/ValidationError.cs
Add balance responsible validation to AggregatedTimeSeriesRequest, which validates that the balance responsible field is correct, if the request is sent by an balance responsible
Tasks: 
Story: 
https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-mosaic/12
References:
https://github.com/Energinet-DataHub/opengeh-edi/pull/566
=> feat: Balance Responsible validation on Aggregarted Time Serie Request

source/dotnet/wholesale-api/Edi.UnitTests/AggregatedTimeSeriesRequestAcceptedMessageFactoryTests.cs, source/dotnet/wholesale-api/Edi/Contracts/AggregatedTimeSeriesRequestAccepted.proto, source/dotnet/wholesale-api/Edi/Factories/AggregatedTimeSeriesRequestAcceptedMessageFactory.cs
Remove Period & Settlement Version from `AggregatedTimeSeriesRequestAccepted`, since they are already stored in EDI
EDI PR: https://github.com/Energinet-DataHub/opengeh-edi/pull/592
=> refac: Remove period & settlement version from request accepted message

source/dotnet/wholesale-api/Events/Events.Infrastructure/IntegrationEvents/AmountPerChargeResultProducedV1.cs, source/dotnet/wholesale-api/Events/Events.Infrastructure/IntegrationEvents/Factories/AmountPerChargeResultProducedV1Factory.cs, source/dotnet/wholesale-api/Events/Events.Infrastructure/IntegrationEvents/Factories/MonthlyAmountPerChargeResultProducedV1Factory.cs, source/dotnet/wholesale-api/Events/Events.Infrastructure/IntegrationEvents/MonthlyAmountPerChargeResultProducedV1.cs, source/dotnet/wholesale-api/Events/Events.Infrastructure/IntegrationEvents/Protos/amount_per_charge_result_produced_v1.proto, source/dotnet/wholesale-api/Events/Events.Infrastructure/IntegrationEvents/Protos/monthly_amount_per_charge_result_produced_v1.proto, source/dotnet/wholesale-api/Events/Events.Infrastructure/IntegrationEvents/Protos/total_monthly_amount_result_produced_v1.proto, source/dotnet/wholesale-api/Events/Events.UnitTests/Infrastructure/IntegrationEvents/Factories/AmountPerChargeResultProducedV1FactoryTests.cs, source/dotnet/wholesale-api/Events/Events.UnitTests/Infrastructure/IntegrationEvents/Factories/MonthlyAmountPerChargeResultProducedV1FactoryTests.cs, source/dotnet/wholesale-integration-events-package/Contracts.Documentation/release-notes/release-notes.md, source/dotnet/wholesale-integration-events-package/Contracts.Tests/AmountPerChargeResultProducedV1Tests.cs, source/dotnet/wholesale-integration-events-package/Contracts.Tests/MonthlyAmountPerChargeResultProducedV1Tests.cs, source/dotnet/wholesale-integration-events-package/Contracts/Contracts.csproj
Currency is now added to the contract for AmountPerChargeResultProducedV1 and MonthlyAmountPerChargeResultProducedV1. The wholesale domain expect everything to be in DKK, so the currency is hard coded in the factories that create the events.
Also, the protobuf files have been modified so that there are no 'jumps' in the increments of the indices in the proto. This is a breaking change, but since there are still no consumers to the event it has it will simply be bumped as a minor instead (to avoid all the complexity of major bumping).
=> feat: Add currency to contracts for wholesale results

source/dotnet/domain-tests/DomainTests.csproj, source/dotnet/domain-tests/DomainTestsBase.cs, source/dotnet/domain-tests/Fixtures/AuthorizedClientFixture.cs, source/dotnet/domain-tests/Fixtures/AuthorizedClientFixtureOutput.cs, source/dotnet/domain-tests/Fixtures/LazyFixtureBase.cs, source/dotnet/domain-tests/Fixtures/LazyFixtureFactory.cs, source/dotnet/domain-tests/Fixtures/UnauthorizedClientFixture.cs, source/dotnet/domain-tests/xunit.runner.json
Support use of IMessageSink (see https://xunit.net/docs/capturing-output#output-in-extensions) from domain tests fixtures to be able to log to output without using "Console.WriteLine".
Example of output from build log:
Example of output from log in VS 2022:
Read about xUnit output here: https://xunit.net/docs/capturing-output#output-in-extensions
=> refac: Improve test output from domain tests fixtures

source/databricks/calculation_engine/package/calculation/energy/exchange_aggregators.py, source/databricks/calculation_engine/package/calculation/preparation/transformations/metering_point_time_series.py, source/databricks/calculation_engine/tests/calculation/energy/exchange_aggregators/test_aggregate_net_exchange_per_neighbour_ga.py, source/databricks/calculation_engine/tests/calculation/energy/quarterly_metering_point_time_series_factories.py
According to SME (updated in decision log in Confluence) we must support cases where only exchange metering point(s) of neighboring grid areas in one direction exist. Support for this is added in this PR in addition to tests of aggregated distinct qualities.
=> test: aggregate_net_exchange_per_neighbour_ga qualities

source/dotnet/domain-tests/Fixtures/AuthorizedClientFixture.cs, source/dotnet/domain-tests/Fixtures/AuthorizedClientFixtureOutput.cs
The current implementation of domain tests read all messages from the service bus and deletes them, even if the calculation id of the message doesn't match one of the just completed calculations.
This PR changes this behavior so we peek messages and only delete those that matches the calculation id of the just completed calculations. Other messages are abandoned and left on the service bus.
=> refac: domain tests should only delete relevant messages 

source/dotnet/domain-tests/Fixtures/CalculationScenario.cs, source/dotnet/domain-tests/Fixtures/Orderers/PriorityOrderer.cs, source/dotnet/domain-tests/Fixtures/SettlementDownloadInput.cs, source/dotnet/domain-tests/Fixtures/SettlementReportScenarioFixture.cs, source/dotnet/domain-tests/Fixtures/SettlementReportScenarioState.cs, source/dotnet/domain-tests/SettlementFeatureTests.cs
Rewritten download settlement report domain test to follow a kind of BDD.
Note that this test was previously skipped due to timeout. 
https://app.zenhub.com/workspaces/mandalorian-5fd22a1a59e4740018f5ab5a/issues/gh/energinet-datahub/team-mandalorian/80
=> refac: Settlement domain test to BDD style

source/dotnet/domain-tests/CalculationFeatureTests.cs, source/dotnet/domain-tests/Fixtures/Attributes/ScenarioStepAttribute.cs, source/dotnet/domain-tests/Fixtures/Orderers/ScenarioStepOrderer.cs, source/dotnet/domain-tests/SettlementFeatureTests.cs
Rename PriorityAttribute and PriorityOrderer to ScenarioStepAttribute and ScenarioStepOrderer.
These new names better reflect how we use them and link their names to the classes they are used on (XxxScenario).
=> ScenarioStep and orderer

source/databricks/calculation_engine/package/calculation/calculator_args.py, source/databricks/calculation_engine/package/calculation_input/table_reader.py, source/databricks/calculation_engine/package/calculator_job.py, source/databricks/calculation_engine/package/calculator_job_args.py, source/databricks/calculation_engine/package/infrastructure/paths.py, source/databricks/calculation_engine/tests/calculation_input/test_table_reader.py, source/databricks/calculation_engine/tests/calculator_job/conftest.py, source/databricks/calculation_engine/tests/helpers/data_frame_utils.py, source/databricks/calculation_engine/tests/helpers/delta_table_utils.py
Since our input tables will soon belong to another workspace, we need to modify the way we refer to them when reading. Using path instead of names make it Independent of the workspace. 
Also, some tests are added to TableReader, so that we test against a Delta table rather than a mock.
=> refac: Read calculation input using path 

source/dotnet/wholesale-api/Edi.UnitTests/AggregatedTimeSeriesRequestHandlerTests.cs, source/dotnet/wholesale-api/Edi.UnitTests/Builders/AggregatedTimeSeriesRequestBuilder.cs, source/dotnet/wholesale-api/Edi.UnitTests/Factories/AggregatedTimeSeriesRequestAcceptedMessageFactoryTests.cs, source/dotnet/wholesale-api/Edi.UnitTests/Factories/AggregatedTimeSeriesRequestFactoryTests.cs, source/dotnet/wholesale-api/Edi.UnitTests/Factories/AggregatedTimeSeriesRequestRejectedMessageFactoryTests.cs, source/dotnet/wholesale-api/Edi/AggregatedTimeSeriesRequestHandler.cs, source/dotnet/wholesale-api/Edi/Contracts/AggregatedTimeSeriesRequest.proto, source/dotnet/wholesale-api/Edi/EdiRegistration.cs, source/dotnet/wholesale-api/Edi/Factories/AggregatedTimeSeriesRequestFactory.cs, source/dotnet/wholesale-api/Edi/Models/AggregationPerRoleAndGridArea.cs
If an energy supplier or balance responsible request aggregated time series for a specific grid area and there is no data. We check if the actor has data for another grid area and return a matching error
=> feat: Add error message if an actor has no data for requested grid area but has data in another grid area

source/databricks/calculation_engine/package/calculation/calculation.py, source/databricks/calculation_engine/package/calculation/preparation/transformations/charge_types.py
Currently, wholesale calculation reads raw time series although the time series data is already available via metering_point_time_series. This gives high performance penalty. In this PR metering_point_time_series is sent to the wholesale calculation instead, thereby avoiding the extra loading from delta lake.
=> refac: Use metering_point_time_series in tariff calculation

source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/CalculationResults/Statements/AggregatedTimeSeriesQueryStatement.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.IntegrationTests/Infrastructure/RequestCalculationResult/AggregatedTimeSeriesQueriesTests.cs
Ensure we group the result by grid area to avoid creating multiple results for the same grid area
=> fix: calculation result should be group by grid area

source/databricks/calculation_engine/package/calculation/calculation.py, source/databricks/calculation_engine/package/calculation/energy/energy_calculation.py, source/databricks/calculation_engine/package/calculation_output/basis_data_writer.py
A part from adding calculation id to log message, this PR also moves basis data writing to the end of the flow. This makes it easier investigate performance of csv writing, because all data is already materialized when writing basis data
=> refac: Add calculation id to log message

source/databricks/calculation_engine/package/calculation/calculator_args.py, source/databricks/calculation_engine/package/calculation/energy/energy_calculation.py, source/databricks/calculation_engine/package/calculation_output/energy_calculation_result_writer.py, source/databricks/calculation_engine/package/calculator_job.py, source/databricks/calculation_engine/package/calculator_job_args.py, source/databricks/calculation_engine/tests/calculator_job/conftest.py, source/databricks/calculation_engine/tests/infrastructure/test_get_calculator_args.py
Adding log statement when leavin write(...). This makes it easier to see the performance of each energy calculation
Also, a minor type-o in is fixed (time_series_periods -> time_series_points)
=> refac: Add logging in energy_calculation_result_writer

source/dotnet/domain-tests/Fixtures/DatabricksClientExtensions.cs
Job list API docs. was incorrect with regards to "limit" (max is not 100 but 25), so I decided to use name filter instead, which is also better anyways: https://docs.databricks.com/api/workspace/jobs/list
=> Filter Job list by job name when requesting jobs

.docker/entrypoint.sh, .github/actions/python-unit-test/action.yml
We might not need retry anymore, and it complicates the CI pipeline. So we will make an experiment at remove it for now, and then create a task so we remember to follow up in a month or so. If we did not experience issues within that month, we expect it can be removed forever.
=> refac: Remove retry of python tests

source/databricks/calculation_engine/tests/conftest.py
in Python tests the fixture, migrations_executed, deleted both calculation_input and calculation_output. The migrations should not touch calculation_input. This caused that some test could fail if they were relying on input, which was deleted by the migrations_executed  fixture.
=> fix: Do not remove calculation_input folder in migrations_executed fixture

.docker/entrypoint.sh, .github/actions/python-unit-test/action.yml, .github/workflows/ci-databricks.yml
We want to split python tests so we can run some on one GitHub runner and others on another runner, so they run in parallel and our CI pipeline becomes faster.
To do this we need to be able to define a filter that pytest can understand.
=> feat: Filter python tests

source/dotnet/domain-tests/Features/Databricks/Fixtures/CalculationJobScenarioFixture.cs
The run parameter is not needed in the new environment where we are running the test
=> refac: remove redundant runparameter

source/databricks/calculation_engine/package/datamigration/migration.py, source/databricks/calculation_engine/package/datamigration/migration_script_args.py, source/databricks/calculation_engine/package/datamigration/migration_scripts/202401101200_Add_calculation_input_tables_to_database.sql, source/databricks/calculation_engine/package/datamigration/migration_scripts/202401121500_Add_calculation_input_tables_to_database.sql, source/databricks/calculation_engine/package/infrastructure/paths.py, source/databricks/calculation_engine/tests/calculation_input/table_reader/test_read_charge_links_periods.py, source/databricks/calculation_engine/tests/calculation_input/table_reader/test_read_charge_master_data_periods.py, source/databricks/calculation_engine/tests/calculation_input/table_reader/test_read_charge_price_points.py, source/databricks/calculation_engine/tests/calculation_input/table_reader/test_read_metering_point_periods.py, source/databricks/calculation_engine/tests/calculation_input/table_reader/test_read_time_series_points.py, source/databricks/calculation_engine/tests/conftest.py, source/databricks/calculation_engine/tests/datamigration/test_migration.py
This improves the developer experience by making the calculation input tables provided by the migrations domain available in the wholesale Databricks workspace.
It also supports the special cases of the `dev_002` and `sandbox_002` environments where the default calculation input folder for delta tables is overridden.
=> feat: Add calculation input tables to database

source/dotnet/subsystem-tests/Features/Calculations/WholesaleFixingCalculationScenario.cs
The test AndThen_ACalculationTelemetryLogIsCreated failed due to an updated search parametres.
=> test: Fixed failing subsystem test

source/dotnet/subsystem-tests/Features/Telemetry/BackgroundServiceTelemetryScenario.cs, source/dotnet/subsystem-tests/Features/Telemetry/Fixtures/TelemetryScenarioFixture.cs, source/dotnet/subsystem-tests/Features/Telemetry/RequestTelemetryScenario.cs, source/dotnet/subsystem-tests/Features/Telemetry/States/BackgroundServiceTelemetryScenarioState.cs, source/dotnet/subsystem-tests/Features/Telemetry/States/RequestTelemetryScenarioState.cs, source/dotnet/subsystem-tests/Features/Telemetry/States/TelemetryEventMatch.cs, source/dotnet/subsystem-tests/Features/Telemetry/States/TelemetryQueryResult.cs, source/dotnet/wholesale-api/WebApi/Startup.cs, source/dotnet/wholesale-api/WebApi/Telemetry/SubsystemInitializer.cs
Part of:
https://app.zenhub.com/workspaces/mandalorian-5fd22a1a59e4740018f5ab5a/issues/gh/energinet-datahub/team-mandalorian/38
=> Set ApplicationVersion and Subsystem in all telemetry events

source/dotnet/wholesale-api/Edi.UnitTests/Factories/AggregatedTimeSeriesRequestAcceptedMessageFactoryTests.cs, source/dotnet/wholesale-api/Edi/Contracts/AggregatedTimeSeriesRequestAccepted.proto, source/dotnet/wholesale-api/Edi/Factories/AggregatedTimeSeriesRequestAcceptedMessageFactory.cs, source/dotnet/wholesale-api/Edi/Mappers/QuantityQualityMapper.cs
Update the AggregatedTimeSeriesRequestAccepted event to utilise a set of quantity qualities just like EnergyResultProducedV2.
=> feat: Update ATS-requests to utilise a quantity quality set

source/dotnet/subsystem-tests/Features/Calculations/Fixtures/CalculationScenarioFixture.cs
Added ';' as delimitor when parsing CVS files.
=> fix: Fixing failing subsystem test

source/databricks/calculation_engine/package/calculation/calculation.py
Before:
When performing a wholesale calculation the metering points that were written into basis data csv only container production and consumption. 
Now:
We also include all types that goes into the calculations.
=> fix: Include all metering point types in basis data

source/dotnet/subsystem-tests/Features/SettlementReport/SettlementReportScenario.cs
The settlement report subsystem tests was relying on data from wholesale fixing which was never generated. Instead we should rely on balance fixing test data. Also, because settlement reports for wholesale fixing is not yet supported
=> fix: Use balance fixing test data for settlment report instead of wholesale fixing

source/dotnet/subsystem-tests/Features/Calculations/BalanceFixingCalculationScenario.cs, source/dotnet/subsystem-tests/Features/Calculations/Fixtures/CalculationScenarioFixture.cs, source/dotnet/subsystem-tests/Features/Calculations/WholesaleFixingCalculationScenario.cs
Part of:
https://app.zenhub.com/workspaces/mandalorian-5fd22a1a59e4740018f5ab5a/issues/gh/energinet-datahub/team-mandalorian/171
=> refac: Subsystem tests - Fail fast

source/dotnet/wholesale-api/Edi.UnitTests/Builders/AggregatedTimeSeriesRequestBuilder.cs, source/dotnet/wholesale-api/Edi.UnitTests/Validators/AggregatedTimeSeriesRequestValidatorTests.cs, source/dotnet/wholesale-api/Edi.UnitTests/Validators/BalanceResponsibleValidatorTest.cs, source/dotnet/wholesale-api/Edi/Validation/AggregatedTimeSeries/Rules/BalanceResponsibleValidationRule.cs
This pull request adds validation rules for the business reason, when the requester of Aggregated Times series is a balance responsible 
https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-mosaic/57
=> feat: Add validation rule for business reason as a balance responsible

source/databricks/calculation_engine/tests/calculation_input/test_input_table_schemas.py, source/databricks/exploratory-notebooks/issue-32/balance-fixing-poc.py, source/databricks/static-test-data/README.md, source/dotnet/wholesale-api/Calculations/Calculations.UnitTests/Infrastructure/CalculationState/CalculationExecutionStateInfrastructureServiceTests.cs, source/dotnet/wholesale-api/Calculations/Calculations.UnitTests/Infrastructure/CalculationState/CalculationStateMapperTests.cs, source/dotnet/wholesale-api/Calculations/Calculations.UnitTests/Infrastructure/Calculations/DatabricksCalculatorJobRunnerTests.cs, source/dotnet/wholesale-api/WebApi/HealthChecks/HealthCheckNames.cs, source/dotnet/wholesale-api/WebApi/Startup.cs, source/dotnet/wholesale-integration-events-package/Contracts.Documentation/documentation.md, source/dotnet/wholesale-integration-events-package/Contracts.Documentation/release-notes/release-notes.md, source/dotnet/wholesale-integration-events-package/Contracts/Contracts.csproj
Tested deployment to sandbox_002: https://github.com/Energinet-DataHub/dh3-environments/actions/runs/7842849532
Part of: https://app.zenhub.com/workspaces/mandalorian-5fd22a1a59e4740018f5ab5a/issues/gh/energinet-datahub/team-mandalorian/131
=> refac: Rename "domain" and health checks

source/databricks/calculation_engine/package/calculation/calculation.py, source/databricks/calculation_engine/package/calculation/preparation/transformations/charge_types/__init__.py, source/databricks/calculation_engine/package/calculation/preparation/transformations/charge_types/fees.py, source/databricks/calculation_engine/package/calculation/preparation/transformations/charge_types/subscriptions.py, source/databricks/calculation_engine/package/calculation/preparation/transformations/charge_types/tariffs.py, source/databricks/calculation_engine/tests/calculation/preparation/transformations/charge_types/test_fees.py, source/databricks/calculation_engine/tests/calculation/preparation/transformations/charge_types/test_subscriptions.py, source/databricks/calculation_engine/tests/calculation/preparation/transformations/charge_types/test_tariffs.py
Seqregate charge types into separate modules for each type. In upcoming PRs there will be more charge-type-specific logic in the individual modules
=> refac: Segregate charge types

source/dotnet/wholesale-api/WebApi.IntegrationTests/CompositionRootTests.cs
Part of:
https://app.zenhub.com/workspaces/mandalorian-5fd22a1a59e4740018f5ab5a/issues/gh/energinet-datahub/team-mandalorian/219
=> refac: CompositeRoot test to set required settings

source/dotnet/subsystem-tests/Features/Telemetry/TimerTriggerTelemetryScenario.cs, source/dotnet/wholesale-api/WebApi.IntegrationTests/CompositionRootTests.cs
When logging to Applications Insights (AI) it can take minutes before logs appear, so it would seem that we need to raise the wait time.
Part of:
https://app.zenhub.com/workspaces/mandalorian-5fd22a1a59e4740018f5ab5a/issues/gh/energinet-datahub/team-mandalorian/234
=> fix: Subsystem test - telemetry

source/dotnet/wholesale-api/Events/Events.Infrastructure/IntegrationEvents/EventProviders/WholesaleResultEventProvider.cs, source/dotnet/wholesale-api/Events/Events.UnitTests/Infrastructure/IntegrationEvents/EventProviders/WholesaleResultEventProviderTests.cs
Currently we don't publish subscription results, so we need to ignore those results. With this PR results are ignored if they are not tariffs.
=> fix: Ignore results from which events cannot be created instead of throwing an exception

source/dotnet/wholesale-api/Edi.UnitTests/Validators/RequestedByActorRoleValidationRuleTest.cs, source/dotnet/wholesale-api/Edi/Extensions/DependencyInjection/EdiExtensions.cs, source/dotnet/wholesale-api/Edi/Validation/AggregatedTimeSeries/Rules/RequestedByActorRoleValidationRule.cs
In order to support a current---albeit hopefully temporary---use case, we need a validation check on actor roles. The "hack" as it was, is to allow a DDM to make requests as if they acted as a MDR. If the DDM forgets to change their "I request as a XXX role" from DDM to MDR, they should get a async validation error.
=> feat: DDM can request as if either DDM or MDR

source/databricks/calculation_engine/package/calculation/energy/aggregators/exchange_aggregators.py, source/databricks/calculation_engine/package/calculation/energy/aggregators/grid_loss_aggregators.py, source/databricks/calculation_engine/package/calculation/energy/aggregators/transformations/aggregate_sum_and_quality.py, source/databricks/calculation_engine/package/calculation/energy/data_structures/energy_results.py, source/databricks/calculation_engine/package/calculation/output/energy_storage_model_factory.py, source/databricks/calculation_engine/package/calculation/preparation/data_structures/prepared_tariffs.py, source/databricks/calculation_engine/package/calculation/preparation/transformations/charge_types/tariffs.py, source/databricks/calculation_engine/package/calculation/wholesale/get_wholesale_metering_point_time_series.py, source/databricks/calculation_engine/package/calculation/wholesale/tariff_calculators.py, source/databricks/calculation_engine/tests/calculation/dataframe_defaults.py, source/databricks/calculation_engine/tests/calculation/energy/aggregations/exchange_aggregators/test_aggregate_net_exchange_per_ga_v8.py, source/databricks/calculation_engine/tests/calculation/energy/aggregations/exchange_aggregators/test_aggregate_net_exchange_per_neighbour_ga_v8.py, source/databricks/calculation_engine/tests/calculation/energy/aggregations/grid_loss_aggregators/test_apply_grid_loss_adjustment.py, source/databricks/calculation_engine/tests/calculation/energy/aggregations/grid_loss_aggregators/test_calculate_total_consumption.py, source/databricks/calculation_engine/tests/calculation/energy/aggregations/grid_loss_aggregators/test_negative_grid_loss.py, source/databricks/calculation_engine/tests/calculation/energy/aggregations/grid_loss_aggregators/test_positive_grid_loss.py, source/databricks/calculation_engine/tests/calculation/energy/aggregations/grouping_aggregators/test_aggregate_per_ga.py, source/databricks/calculation_engine/tests/calculation/energy/aggregations/grouping_aggregators/test_aggregate_per_ga_and_brp.py, source/databricks/calculation_engine/tests/calculation/energy/aggregations/grouping_aggregators/test_aggregate_per_ga_and_es.py, source/databricks/calculation_engine/tests/calculation/energy/aggregations/metering_point_time_series_aggregators/test_aggregate_per_ga_and_brp_and_es.py, source/databricks/calculation_engine/tests/calculation/energy/aggregations/transformations/test_aggregate_quantity_and_quality.py, source/databricks/calculation_engine/tests/calculation/energy/aggregations/transformations/test_aggregate_sum_quantity_and_qualities.py, source/databricks/calculation_engine/tests/calculation/energy/energy_results_factories.py, source/databricks/calculation_engine/tests/calculation/energy/test_energy_results.py, source/databricks/calculation_engine/tests/calculation/output/test_energy_storage_model_factory.py, source/databricks/calculation_engine/tests/calculation/preparation/transformations/charge_types/test_tariffs.py
=> refac: Skip use of `Colname.sum_quantity` in pyspark

.docker/entrypoint.sh
An [unintentional break](https://github.com/pytest-dev/pytest/issues/4048) was introduced in pytest between 3.6 and 3.8. To circumvent this problem the CI now uses paths to python tests instead of the -k expressions.
=> refac: Use python paths in docker in CI

.docker/entrypoint.sh
Reverts Energinet-DataHub/opengeh-wholesale#2057
#2057 broke the pipeline in an unexpected way and I have no other quick fixes than reverting.
=> Revert "refac: Use python paths in docker in CI"

.docker/entrypoint.sh
=> refac: Use paths to control python test execution in CI

.github/workflows/ci-databricks.yml
Logic tests consist of both energy calculation and wholesale calculation tests. They use almost 10 minutes in the CI. This PR splits the two in to separate job runs to reduce the total time.
=> chore: Split pyspark logic tests for better CI performance

.docker/entrypoint.sh
=> feat: Enable extended globbing for python test paths in CI

source/dotnet/wholesale-api/Edi.UnitTests/AggregatedTimeSeriesRequestHandlerTests.cs, source/dotnet/wholesale-api/Edi.UnitTests/Calculations/CompletedCalculationRetrieverTest.cs, source/dotnet/wholesale-api/Edi.UnitTests/WholesaleServicesRequestHandlerTests.cs, source/dotnet/wholesale-api/Edi/AggregatedTimeSeriesRequestHandler.cs, source/dotnet/wholesale-api/Edi/Calculations/CompletedCalculationRetriever.cs, source/dotnet/wholesale-api/Edi/Calculations/LatestCalculationsForPeriod.cs, source/dotnet/wholesale-api/Edi/WholesaleServicesRequestHandler.cs
If we can't find any calculation for the request periode and calculation type we now return "No Data" instead of throwing missing calculation exception. 
However, if we finds calculation for part of the requested period, we throw exception with missing calculation.
=> fix: return no data if calculation does not exist for requested period

.docker/Dockerfile
I was mistaken. Azure CLI should not have been removed as it is used by the `pyspark` integration tests.
This PR re-adds the Azure CLI to the docker image. A few optimizations has been used as well:
- Reduce the number of layers by gathering several RUN commands into a single
- Move COPY of spark defaults to after more reusable layers
=> fix: Re-add Azure CLI to Docker image

source/dotnet/subsystem-tests/SubsystemTests.csproj, source/dotnet/wholesale-api/Calculations/Calculations.Application/Calculations.Application.csproj, source/dotnet/wholesale-api/Calculations/Calculations.Infrastructure/Calculations.Infrastructure.csproj, source/dotnet/wholesale-api/Common.Infrastructure/Common.Infrastructure.csproj, source/dotnet/wholesale-api/Edi/Edi.csproj, source/dotnet/wholesale-api/Events/Events.Application/Events.Application.csproj, source/dotnet/wholesale-api/Events/Events.Infrastructure/Events.Infrastructure.csproj, source/dotnet/wholesale-api/Orchestration/Orchestration.csproj, source/dotnet/wholesale-api/Test.Core/Test.Core.csproj, source/dotnet/wholesale-api/WebApi/WebApi.csproj
Update NuGet package dependencies to ensure we use the newly released App package that uses .NET 8.
=> refac: Update NuGet package dependencies

.github/CODEOWNERS
Make Mosaic co-codeowners of .NET source code.
=> refac: Make Mosaic co-codeowners of .NET source code

source/databricks/calculation_engine/tests/features/utils/scenario_fixture2.py
If the number of expected files in a logic test is zero an exception is thrown. This ensures the test doesn't become green when the expected files folder is empty.
=> refac: Added expected files guard in logic test 

.devcontainer/devcontainer.json, .docker/Dockerfile, .docker/mamba_requirements.txt, .docker/requirements.txt, .docker/spark-defaults.conf, source/databricks/README.md, source/databricks/calculation_engine/setup.py, source/databricks/debugz.sh
Update to Docker base image `ghcr.io/energinet-datahub/pyspark-slim:3.5.1-2`, which is significantly smaller than the previous versions.
In addition, some obsolete stuff has been removed. This is primarily to reduce the image size further.
The resulting wholesale image is 3.74 GB.
=> chore: Update to latest docker base image

.devcontainer/devcontainer.json
Enable vscode dev container functionality with newest pyspark-slim image version
=> fix: vscode devcontainer

.docker/Dockerfile
1. Update to base image `ghcr.io/energinet-datahub/pyspark-slim:3.5.1-3`, which fixes broken devcontainer
2. Reduce image size by approximately 1GB by removing the layer `RUN fix-permissions "${CONDA_DIR}"`
=> chore: Docker image optimizations

source/databricks/calculation_engine/package/calculation/wholesale/total_monthly_amount_calculator.py, source/databricks/calculation_engine/tests/calculation/wholesale/test_total_monthly_amount_calculator.py
The left join operation in the total monthly amount calculator gave to many rows. This is fixed in this PR
=> fix: Total monthly amount issue when multiple energy suppliers

source/databricks/calculation_engine/package/calculation/energy/aggregators/exchange_aggregators.py, source/databricks/calculation_engine/package/calculation/energy/aggregators/metering_point_time_series_aggregators.py, source/databricks/calculation_engine/package/calculation/energy/energy_calculation.py, source/databricks/calculation_engine/package/calculation/energy/hour_to_quarter.py, source/databricks/calculation_engine/package/calculation/preparation/data_structures/metering_point_time_series.py, source/databricks/calculation_engine/tests/calculation/energy/aggregations/exchange_aggregators/test_aggregate_net_exchange_per_ga.py, source/databricks/calculation_engine/tests/calculation/energy/aggregations/exchange_aggregators/test_aggregate_net_exchange_per_ga_v8.py, source/databricks/calculation_engine/tests/calculation/energy/aggregations/exchange_aggregators/test_aggregate_net_exchange_per_neighbour_ga.py, source/databricks/calculation_engine/tests/calculation/energy/aggregations/exchange_aggregators/test_aggregate_net_exchange_per_neighbour_ga_v8.py, source/databricks/calculation_engine/tests/calculation/energy/aggregations/metering_point_time_series_aggregators/test_aggregate_per_ga_and_brp_and_es.py, source/databricks/calculation_engine/tests/calculation/energy/metering_point_time_series_factories.py
Rename quarterly_metering_point_time_series to metering_point_time_series since it is not just quarterly in the upcoming PRs
=> refac: no more quarterly_metering_point_time_series

source/dotnet/wholesale-api/Orchestrations.IntegrationTests/Fixtures/OrchestrationsAppFixture.cs, source/dotnet/wholesale-api/Orchestrations.IntegrationTests/Functions/Calculation/CalculationOrchestrationTests.cs, source/dotnet/wholesale-api/Orchestrations/Extensions/Options/CalculationJobStatusMonitorOptions.cs, source/dotnet/wholesale-api/Orchestrations/Functions/Calculation/CalculationOrchestration.cs, source/dotnet/wholesale-api/Orchestrations/Functions/Calculation/CalculationTrigger.cs, source/dotnet/wholesale-api/Orchestrations/Functions/Calculation/Model/CalculationOrchestrationInput.cs, source/dotnet/wholesale-api/Orchestrations/Program.cs
Part of:
https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-mosaic/182
=> refac: Configure Calculation orchestration

source/dotnet/wholesale-integration-events-package/Contracts.Documentation/release-notes/release-notes.md, source/dotnet/wholesale-integration-events-package/Contracts/Contracts.csproj
Ensure TotalMonthlyAmountResultProducedV1 partial class is added in the nuget package by adding a missing reference to TotalMonthlyAmountResultProducedV1 partial class.
=> fix: missing reference to TotalMonthlyAmountResultProducedV1.cs

source/databricks/calculation_engine/package/datamigration/migration_scripts/202405081100_Modify_settlement_report_metering_point_time_series_v1_view.sql
Added the create settlement_report_metering_point_time_series_v1_view script (with rename of view).
Currently, the settlement_report_metering_point_time_series_v1_view is missing in several environments. 
Might be due to a missing GO in the script.
=> fix: settlement_report_metering_point_time_series_v1_view

source/databricks/calculation_engine/package/calculation/energy/resolution_transition_factory.py, source/databricks/calculation_engine/tests/calculation/energy/test_resolution_transition_factory.py
fixes issue where transition datetime and period end had the same datetime but was not included in hour resolution, which it should be
=> refac: fix resolution transition datetime missing equal

source/dotnet/wholesale-api/CalculationResults/CalculationResults.Application/SettlementReports_v2/SettlementReportDownloadHandler.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.IntegrationTests/Application/SettlementReports/SettlementReportDownloadHandlerIntegrationTests.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Interfaces/SettlementReports_v2/ISettlementReportDownloadHandler.cs, source/dotnet/wholesale-api/Orchestrations/Functions/SettlementReports/SettlementReportDownloadTrigger.cs
Adds a check to the download settlement report function, to see if a user is FAS and therefore is allowed to download all reports.
=> feat: Add FAS check to download

source/databricks/calculation_engine/package/calculation/wholesale/wholesale_calculation.py
Cache hourly tariff before calculating/materializing monthly amount and total monthly amount. This will hopefully increase the performance for monthly and total monthly (see current times below):
=> refac: Cache hourly tariff before calculating monthly amounts

source/dotnet/wholesale-api/Edi.UnitTests/Validators/WholesaleServicesRequest/ChargeTypeValidatorTests.cs, source/dotnet/wholesale-api/Edi.UnitTests/Validators/WholesaleServicesRequest/WholesaleServicesRequestValidatorTests.cs, source/dotnet/wholesale-api/Edi/Extensions/DependencyInjection/EdiExtensions.cs, source/dotnet/wholesale-api/Edi/Validation/WholesaleServicesRequest/Rules/ChargeTypeValidationRule.cs
Validation of chargeType. Since their type must at most be 10 characters long. Return error message with faulted type
=> feat: Add validation rule for chargetypes in wholesale services requests

source/databricks/calculation_engine/tests/features/public_data_models/test_public_data_model_views.py, source/databricks/calculation_engine/tests/features/utils/views/public_data_models_databases_and_schemas.py
Replace non-useful error output, when expected schemas are not found. New output:
Fix the path to expected schemas so the test works regardless of how the pytest session was started.
=> fix: Fix `test_public_data_model_views.py`

source/dotnet/wholesale-api/CalculationResults/CalculationResults.Application/SettlementReports_v2/SettlementReportRequestHandler.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.IntegrationTests/Application/SettlementReports/SettlementReportRequestHandlerIntegrationTests.cs
Azure doesn't support IANA timezone ids so replaced the IANA With the windows equivalent
=> Changed timezone Id from IANA to Windows

source/databricks/calculation_engine/package/calculation/preparation/transformations/charge_types/explode_charge_price_information_within_periods.py, source/databricks/calculation_engine/package/calculation/preparation/transformations/charge_types/subscriptions_and_fees.py, source/databricks/calculation_engine/package/calculation/preparation/transformations/charge_types/tariffs.py, source/databricks/calculation_engine/tests/calculation/preparation/transformations/charge_types/test_subscriptions_and_fees_get_prepared_subscriptions.py
Fees and subscriptions now uses the same method as tariffs to explode charge_price_information based on charge_resolution. By doing this we fix an issue with duplicate charge_times in the explode method.
=> fix: Handle start and stop of subscription/fee on the same day

source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/SettlementReports_v2/Generators/EnergyResultFileGenerator.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/SettlementReports_v2/Generators/MeteringPointMasterDataFileGenerator.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/SettlementReports_v2/Generators/MonthlyAmountFileGenerator.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/SettlementReports_v2/Generators/WholesaleResultFileGenerator.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/SettlementReports_v2/Statements/SettlementReportChargeLinkPeriodsCountQueryStatement.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.IntegrationTests/Application/SettlementReports/SettlementReportFileRequestHandlerIntegrationTests.cs
We need to ensure that all grid area values in the basis data CSV files are always 3 characters in length, padded with 0'es if they are less.
=> chore: Add padding to filegenerators for gridarea fields

source/dotnet/database-migration/DatabaseMigration.csproj, source/dotnet/subsystem-tests/SubsystemTests.csproj, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Application/CalculationResults.Application.csproj, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/CalculationResults.Infrastructure.csproj, source/dotnet/wholesale-api/CalculationResults/CalculationResults.IntegrationTests/CalculationResults.IntegrationTests.csproj, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Interfaces/CalculationResults.Interfaces.csproj, source/dotnet/wholesale-api/CalculationResults/CalculationResults.UnitTests/CalculationResults.UnitTests.csproj, source/dotnet/wholesale-api/Calculations/Calculations.Application/Calculations.Application.csproj, source/dotnet/wholesale-api/Calculations/Calculations.Infrastructure/Calculations.Infrastructure.csproj, source/dotnet/wholesale-api/Calculations/Calculations.IntegrationTests/Calculations.IntegrationTests.csproj, source/dotnet/wholesale-api/Calculations/Calculations.Interfaces/Calculations.Interfaces.csproj, source/dotnet/wholesale-api/Calculations/Calculations.UnitTests/Calculations.UnitTests.csproj, source/dotnet/wholesale-api/Common.Infrastructure/Common.Infrastructure.csproj, source/dotnet/wholesale-api/Common.Interfaces/Common.Interfaces.csproj, source/dotnet/wholesale-api/Edi.UnitTests/Edi.UnitTests.csproj, source/dotnet/wholesale-api/Edi/Edi.csproj, source/dotnet/wholesale-api/Events/Events.Application/Events.Application.csproj, source/dotnet/wholesale-api/Events/Events.Infrastructure/Events.Infrastructure.csproj, source/dotnet/wholesale-api/Events/Events.IntegrationTests/Events.IntegrationTests.csproj, source/dotnet/wholesale-api/Events/Events.Interfaces/Events.Interfaces.csproj, source/dotnet/wholesale-api/Events/Events.UnitTests/Events.UnitTests.csproj, source/dotnet/wholesale-api/Orchestrations.IntegrationTests/Orchestrations.IntegrationTests.csproj, source/dotnet/wholesale-api/Orchestrations/Orchestrations.csproj, source/dotnet/wholesale-api/Test.Core/Test.Core.csproj, source/dotnet/wholesale-api/WebApi.IntegrationTests/WebApi.IntegrationTests.csproj, source/dotnet/wholesale-api/WebApi.UnitTests/WebApi.UnitTests.csproj, source/dotnet/wholesale-api/WebApi/WebApi.csproj
Bumps [Microsoft.VisualStudio.Threading.Analyzers](https://github.com/microsoft/vs-threading) from 17.9.28 to 17.10.48.
Bumps [Microsoft.OpenApi.Readers](https://github.com/Microsoft/OpenAPI.NET) from 1.6.14 to 1.6.15.
Bumps [Microsoft.NET.Test.Sdk](https://github.com/microsoft/vstest) from 17.9.0 to 17.10.0.
Bumps [Microsoft.Extensions.Logging.AzureAppServices](https://github.com/dotnet/aspnetcore) from 8.0.4 to 8.0.6.
=> chore: Dependabot bumps

source/databricks/calculation_engine/contracts/calculation-job-parameters-reference.txt, source/databricks/calculation_engine/package/calculation/calculator_args.py, source/databricks/calculation_engine/package/calculator_job.py, source/databricks/calculation_engine/package/calculator_job_args.py, source/databricks/calculation_engine/tests/calculation/basis_data/basis_data_test_factory.py, source/databricks/calculation_engine/tests/calculation/energy/test_resolution_transition_factory.py, source/databricks/calculation_engine/tests/calculator_job/conftest.py, source/databricks/calculation_engine/tests/conftest.py, source/databricks/calculation_engine/tests/features/utils/calculation_args.py, source/databricks/calculation_engine/tests/infrastructure/test_get_calculator_args.py
NOTE: This enables setting the flag from outside. Simulation is, however, not implemented and the calculation will throw an exception if a simulation is started.
This enables Mosaic to implement their part of simulation invocation when they fancy it.
=> feat: Add `--simulation` flag for calculation invocation

source/databricks/calculation_engine/package/calculation/basis_data/schemas/__init__.py, source/databricks/calculation_engine/package/calculation/basis_data/schemas/charge_link_periods_schema.py, source/databricks/calculation_engine/package/calculation/basis_data/schemas/charge_price_information_periods_schema.py, source/databricks/calculation_engine/package/datamigration_hive/schema_config.py, source/databricks/calculation_engine/tests/calculation/basis_data/basis_data_test_factory.py, source/databricks/calculation_engine/tests/calculation/basis_data/test_basis_data_factory.py, source/databricks/calculation_engine/tests/calculator_job/test_wholesale_calculation.py
Prefix introduced so that we can afterwards use the original name for unity catalog. On UC the to_date will be NOT NULL
=> refac: Pre-fix charge basis data schema to 'hive_

source/dotnet/wholesale-api/Orchestrations/Extensions/Options/CalculationOrchestrationMonitorOptions.cs
In the calculation orchestration, raise the time we wait for an "messages enqueued" event from EDI.
Wait time is now 14 days.
Deployment tested to `dev_002`: https://github.com/Energinet-DataHub/dh3-environments/actions/runs/10162775438
=> refac: Raise wait time for "messages enqueued" event

source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/CalculationResults/Statements/AmountsPerChargeWholesaleServicesDatabricksContract.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/CalculationResults/Statements/IWholesaleServicesDatabricksContract.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/CalculationResults/Statements/MonthlyAmountsPerChargeWholesaleServicesDatabricksContract.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/CalculationResults/Statements/TotalMonthlyAmountWholesaleServicesDatabricksContract.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/CalculationResults/Statements/WholesaleServicesQueryStatementHelper.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.IntegrationTests/Infrastructure/RequestCalculationResult/WholesaleServicesQueriesCsvTests.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Interfaces/CalculationResults/Model/WholesaleResults/WholesaleServicesQueryParameters.cs, source/dotnet/wholesale-api/Edi/Factories/WholesaleServicesRequestMapper.cs, source/dotnet/wholesale-api/Edi/Models/WholesaleServicesRequest.cs, source/dotnet/wholesale-api/Edi/WholesaleServicesRequestHandler.cs
Include is_tax charges in request results for charge owners, when no charge owner is provided as part of request parameters. Only is_tax results for the provided set of grid areas are included. The validation rules ensures, that the charge owner is the owner of all of the grid areas in the requests.
=> feat: Include is_tax results for charge owners in wholesale requests

.docker/entrypoint.sh
Example of test output that was truncated:
=> feat: Avoid truncating pytest test output in CI

source/databricks/calculation_engine/package/infrastructure/paths.py, source/databricks/calculation_engine/tests/contracts/data_products_databases_and_schemas.py
quick change of hardcode "migrations_wholesale" to new "shared_wholesale_input", i will make another PR that makes this not harcoded and fixes other naming inconsistencies
=> refac: Rename to shared_wholesale_input

source/dotnet/wholesale-api/Calculations/Calculations.Application/Model/Calculations/CalculationDtoMapper.cs, source/dotnet/wholesale-api/Calculations/Calculations.Infrastructure/Persistence/Calculations/CalculationRepository.cs, source/dotnet/wholesale-api/Calculations/Calculations.IntegrationTests/Infrastructure/Persistence/Calculation/CalculationRepositoryTests.cs, source/dotnet/wholesale-api/Calculations/Calculations.Interfaces/Models/CalculationDto.cs, source/dotnet/wholesale-api/WebApi/V3/Calculation/CalculationDto.cs, source/dotnet/wholesale-api/WebApi/V3/Calculation/CalculationDtoMapper.cs
- Fix calculation API not including `ScheduledAt` field
- Fix search endpoint not returning scheduled calculations that hasn't started yet
=> fix: Fix calculation api endpoints for scheduled calculations

source/dotnet/wholesale-api/WebApi.UnitTests/WebApi/V3/CalculationOrchestrationStateMapperTests.cs, source/dotnet/wholesale-api/WebApi/V3/Calculation/CalculationOrchestrationState.cs, source/dotnet/wholesale-api/WebApi/V3/Calculation/CalculationOrchestrationStateMapper.cs
- Fix missing orchestration state map in Web API
- Add test to ensure all possible inputs are mapped
=> fix: Fix missing orchestration state map in Web API

source/dotnet/subsystem-tests/Features/Calculations/BalanceFixingCalculationScenario.cs
Increase allowed time difference since 30s can fail in CD
=> test: Increase allowed time difference for scheduled calculation in subsystem test

source/dotnet/subsystem-tests/Features/Calculations/WholesaleFixingCalculationScenario.cs
See title.
Deployed to `dev_002`: https://github.com/Energinet-DataHub/dh3-environments/actions/runs/10633750896
=> fix: Subsystem name in subsystem tests

source/databricks/.gitignore, source/databricks/settlement_report/settlement_report_job/domain/report_generator.py, source/databricks/settlement_report/settlement_report_job/entrypoint.py, source/databricks/settlement_report/setup.py, source/databricks/settlement_report/tests/conftest.py, source/databricks/settlement_report/tests/domain/test_settlement_report_args.py, source/databricks/settlement_report/tests/entrypoints/conftest.py, source/databricks/settlement_report/tests/entrypoints/test_entry_points.py
Add test of settlement report job wheel entrypoint.
Refac for a single domain logic entry point (`report_generator.execute()`).
=> feat: Test settlement report entrypoint

source/databricks/settlement_report/settlement_report_job/domain/report_generator.py
This PR places the zip file in the root instead of in a dedicated folder. Also its name should be the id of the report
=> feat: Use report_id in zip-filename for settlement reports

source/databricks/settlement_report/contracts/settlement-report-job-parameters-reference.txt, source/databricks/settlement_report/settlement_report_job/domain/settlement_report_args.py, source/databricks/settlement_report/settlement_report_job/domain/time_series_writer.py, source/databricks/settlement_report/settlement_report_job/infrastructure/settlement_report_job_args.py, source/databricks/settlement_report/settlement_report_job/utils.py, source/databricks/settlement_report/tests/conftest.py, source/databricks/settlement_report/tests/domain/test_report_name_factory.py, source/databricks/settlement_report/tests/infrastructure/test_settlement_report_args.py, source/databricks/settlement_report/tests/test_settlement_report_utils.py
This PR introduces a SettlementReportArgs called "locale", which is checked in the "write_files" function of the time_series writer. 
It chooses the delimiter of the CSV file, with english being "," and danish using ";" due to danish also requireing floats/doubles/decimals to use a comma like "123,4" vs the english standard "123.4"
However, due to pyspark's CSV implementation not having a setting to change the "." to a "," it is required to do manually, by casting every relevant field to strings and replacing the character. 
It also adds unit tests to the write_files function, testing the order_by argument as well.
=> feat: Allow choice of locale affecting CSV format

source/databricks/settlement_report/settlement_report_job/infrastructure/settlement_report_job_args.py
=> fix: Set locale to "da-DK" by default

source/dotnet/subsystem-tests/Features/SettlementReports/SettlementReportJobGeneratesZipScenario.cs, source/dotnet/subsystem-tests/Features/SettlementReports/SettlementReportJobPerformanceScenario.cs
Add --include-basis-data to subsystem test - otherwise there will be no files to zip at this point
=> fix: Add --include-basis-data argument to settlement report job in subsystem test

source/databricks/calculation_engine/package/databases/wholesale_results_internal/energy_results.py
Changes the ".cache()" introduced to allieviate the incident of "indeterminate" shuffles into a ".localCheckpoint()", which does a proper checkpoint of the data rather than keeping it in memory. The difference between local and non-local checkpoints, is that local saves to local executor storage, whereas proper checkpoints write to fault-reliant HDFS. 
However, writing to HDFS is expensive, and writing to locally cuts out all network involved, and is as such much faster and easier to quickly attempt. The alternative requires a specific path in storage where we can write to, but that is the next step.
=> Added local checkpointing instead of caching.

source/databricks/settlement_report/settlement_report_job/domain/csv_writer.py, source/databricks/settlement_report/settlement_report_job/domain/report_generator.py, source/databricks/settlement_report/tests/domain/test_csv_writer.py
Refactors the time_series_writer of the SettlementReportJob to be more generic, in preparation for the remaining file types.
It now generalises the pre-processing of input, and allows for clear separations based on ReportType.
=> refac: Generalise time_series_writer as csv_writer

source/databricks/settlement_report/settlement_report_job/domain/csv_writer.py, source/databricks/settlement_report/settlement_report_job/domain/report_generator.py, source/databricks/settlement_report/settlement_report_job/domain/time_series/prepare_for_csv.py, source/databricks/settlement_report/settlement_report_job/domain/time_series/read_and_filter.py, source/databricks/settlement_report/settlement_report_job/domain/time_series/time_series_factory.py, source/databricks/settlement_report/settlement_report_job/entry_point.py, source/databricks/settlement_report/settlement_report_job/infrastructure/settlement_report_job_args.py, source/databricks/settlement_report/settlement_report_job/logging/__init__.py, source/databricks/settlement_report/settlement_report_job/logging/decorators.py, source/databricks/settlement_report/settlement_report_job/logging/logger.py, source/databricks/settlement_report/settlement_report_job/logging/logging_configuration.py, source/databricks/settlement_report/tests/conftest.py
Move all logging to a logging subpackage. This removes most of the remaining dependencies from `domain` to `infrastructure`. This also makes logging almost ready to extract into its own shared package.
=> refac: Refac logging and remove domain dependencies to infra logging

source/databricks/settlement_report/settlement_report_job/domain/report_generator.py, source/databricks/settlement_report/settlement_report_job/entry_point.py, source/databricks/settlement_report/setup.py, source/databricks/settlement_report/tests/entry_points/test_entry_points.py
Adds the entry point necessary to start a task that points to execute_energy_results.
This is needed for a DH3 infrastructure PR that will follow this one, such that the job includes the energy_result file type.
=> feat: Added entry point for execute_energy_results

source/databricks/settlement_report/settlement_report_job/utils.py, source/databricks/settlement_report/tests/test_settlement_report_utils.py
As noted by Irene, the current default CSV writer's options has a timestampFormat using milliseconds. 
This PR gets rid of it, regardless of what locale has been chosen.
=> fix: Added timestampFormat as CSV option

source/databricks/settlement_report/settlement_report_job/utils.py, source/databricks/settlement_report/tests/domain/test_csv_writer.py
Changes a few things on the advice of Irene, such that:
Chunks are now 1-indexed instead of 0-indexed.
If a file is already small enough that it would be in one chunk, the flag prevent-large-files is disregarded basically.
=> Changed prevent-large-files behaviour

source/databricks/settlement_report/settlement_report_job/domain/csv_column_names.py, source/databricks/settlement_report/settlement_report_job/domain/csv_writer.py, source/databricks/settlement_report/settlement_report_job/domain/energy_results/energy_results_factory.py, source/databricks/settlement_report/settlement_report_job/domain/energy_results/prepare_for_csv.py, source/databricks/settlement_report/settlement_report_job/utils.py, source/databricks/settlement_report/tests/domain/test_csv_writer.py, source/databricks/settlement_report/tests/domain/test_execute_energy_results.py
Currently, when we set split_report_by_grid_area, we end up partitioning by grid_area_code in energy_results.
This means that the actual column data is dropped, and we have now decided we always want to keep it.
To do so, this PR creates an EphemeralColumn copy of the grid_area_code, and uses that for the partitioning.
=> fix: Creates an ephemeral Grid Area Code to keep partition column.

source/databricks/settlement_report/settlement_report_job/domain/csv_writer.py, source/databricks/settlement_report/settlement_report_job/utils.py, source/databricks/settlement_report/tests/domain/test_csv_writer.py
If a request is sent in, which would result in not having grid area be a partition column for energy results, but at the same time having energy_supplier_id (or chunk_index) being a partition column, then it would fail. This fixes it, by not always assuming grid area is a partition column.
=> fix: Grid Area is no longer always assumed as a partition  column

source/databricks/settlement_report/settlement_report_job/domain/csv_writer.py, source/databricks/settlement_report/settlement_report_job/domain/report_generator.py, source/databricks/settlement_report/settlement_report_job/infrastructure/paths.py, source/databricks/settlement_report/tests/domain/assertion.py, source/databricks/settlement_report/tests/domain/test_csv_writer.py, source/databricks/settlement_report/tests/domain/test_execute_charge_links.py, source/databricks/settlement_report/tests/domain/test_execute_energy_results.py, source/databricks/settlement_report/tests/domain/test_execute_hourly_time_series.py, source/databricks/settlement_report/tests/domain/test_execute_quarterly_time_series.py, source/databricks/settlement_report/tests/domain/test_execute_wholesale_results.py
Instead of storing full paths in tasks values we only store the file names. This reduces the size of the task values (there is a limit of 48 KiB
=> fix: Avoid large size on task values 

source/databricks/settlement_report/settlement_report_job/utils.py
Chunk indexes are calculated incorrectly.
Currently, the chunk_index uses the rownumber of the _entire dataframe_ to calculate a chunk. However, this means each chunk could be practically empty.
=> fix: Added partitioning to chunk index

source/dotnet/subsystem-tests/Features/Calculations/BalanceFixingCalculationScenario.cs
Since we no longer write to HIVE, the sub-system timeout has been lowered to 18 minutes.
=> refac: Reduce time limit on sub system test

source/databricks/settlement_report/settlement_report_job/domain/order_by_columns.py
The list of order by columns for monthly_amouints naïvely assumes that all columns are always present, even though CHARGEOWNER might be dropped if you are Grid Access Provider og System Operator. This PR fixes that, by adding it as an order by column on the condition that it is an existing column.
=> fix: Added CHARGEOWNER conditionally in MonthlyAmounts orderby

source/dotnet/subsystem-tests/Features/SettlementReports/SettlementReportWholesaleCalculationsJobGeneratesZipScenario.cs
=> fix: Don't use hard coded report id in test

source/dotnet/subsystem-tests/Features/SettlementReports/SettlementReportBalanceFixingJobGeneratesZipScenario.cs, source/dotnet/subsystem-tests/Features/SettlementReports/SettlementReportWholesaleCalculationsJobGeneratesZipScenario.cs
=> test: Increase settlemenent report download limit to 20 minutes in subsystem test

source/databricks/calculation_engine/package/optimize_job/delta_optimization.py
The optimize job failed earlier because it's global "_TRACER_NAME" variable wasn't set, which is normally done by configure_logging. This PR adds that configuration, and also adds support for an application insights logging option.
=> fix: Added configure_logging, and uses spans

source/dotnet/subsystem-tests/SubsystemTests.csproj, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Application/CalculationResults.Application.csproj, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/CalculationResults.Infrastructure.csproj, source/dotnet/wholesale-api/CalculationResults/CalculationResults.IntegrationTests/CalculationResults.IntegrationTests.csproj, source/dotnet/wholesale-api/CalculationResults/CalculationResults.Interfaces/CalculationResults.Interfaces.csproj, source/dotnet/wholesale-api/CalculationResults/CalculationResults.UnitTests/CalculationResults.UnitTests.csproj, source/dotnet/wholesale-api/Calculations/Calculations.Application/Calculations.Application.csproj, source/dotnet/wholesale-api/Calculations/Calculations.Infrastructure/Calculations.Infrastructure.csproj, source/dotnet/wholesale-api/Calculations/Calculations.IntegrationTests/Calculations.IntegrationTests.csproj, source/dotnet/wholesale-api/Calculations/Calculations.Interfaces/Calculations.Interfaces.csproj, source/dotnet/wholesale-api/Calculations/Calculations.UnitTests/Calculations.UnitTests.csproj, source/dotnet/wholesale-api/Common.Infrastructure/Common.Infrastructure.csproj, source/dotnet/wholesale-api/Edi.UnitTests/Edi.UnitTests.csproj, source/dotnet/wholesale-api/Events/Events.IntegrationTests/Events.IntegrationTests.csproj, source/dotnet/wholesale-api/Events/Events.UnitTests/Events.UnitTests.csproj, source/dotnet/wholesale-api/Orchestrations/Orchestrations.csproj, source/dotnet/wholesale-api/Test.Core/Test.Core.csproj, source/dotnet/wholesale-api/WebApi.IntegrationTests/WebApi.IntegrationTests.csproj, source/dotnet/wholesale-api/WebApi.UnitTests/WebApi.UnitTests.csproj
Bumps [Microsoft.Extensions.DependencyInjection.Abstractions](https://github.com/dotnet/runtime) from 8.0.1 to 9.0.0.
Bumps [Microsoft.Azure.Functions.Worker.ApplicationInsights](https://github.com/Azure/azure-functions-dotnet-worker) from 1.4.0 to 2.0.0
Bumps [FluentAssertions](https://github.com/fluentassertions/fluentassertions) from 6.12.1 to 6.12.2.
Bumps [Microsoft.Extensions.Configuration](https://github.com/dotnet/runtime) from 8.0.0 to 9.0.0.
Bumps [Energinet.DataHub.Core.App.Common.Abstractions](https://github.com/Energinet-DataHub/geh-core) from 13.2.0 to 14.0.0
Bumps [NodaTime](https://github.com/nodatime/nodatime) from 3.1.12 to 3.2.0
=> chore: Bump nuget dependabot

.devcontainer/docker-compose-windows.yml, .devcontainer/docker-compose.yml, .docker/Dockerfile, .docker/entrypoint.sh, .github/workflows/ci-databricks.yml
This pull request includes several changes to configuration files and scripts to improve consistency and functionality across the project. The most important changes include updates to the Docker configuration files, modifications to user permissions in the Dockerfile, and adjustments to the entrypoint script and CI workflow.
This will make sure the user id for the github actions runner is the same as inside the container.
* [`.devcontainer/docker-compose-windows.yml`](diffhunk://#diff-7da8718dba02e6f1fc48c79f17aa699ab5dec440ecc37d751a5480d3035fadcfL8-R11): Updated volume mounts and working directory to use `${HOME}` and corrected the Azure CLI token cache location.
* [`.devcontainer/docker-compose.yml`](diffhunk://#diff-67a4805fdcc6145d7b3ada2a6099a9b2e91c9d0fd108c22f95d2f01d219793d1L8-R1 …
=> Make user id of github actions runner and docker image identical

source/databricks/calculation_engine/package/datamigration/migration_scripts/202501061330_alter_tables__metering_point_type_constraints_added_surplus_production.sql
This PR adds specifically "surplus_production" to the delta constraints for amounts_per_charge taken from migrations.
=> fix: Added surplus production to meter type check

source/dotnet/wholesale-api/Edi.UnitTests/Validators/WholesaleServicesRequest/PeriodValidationRuleTests.cs, source/dotnet/wholesale-api/Edi/Validation/WholesaleServicesRequest/Rules/PeriodValidationRule.cs
This PR will allow requests for wholesale series which overlap a year on local date time. 
- `PeriodValidationRule` now inspects a if the month differ more than 1 from each other, and the year of start and end period is between each other (1), then the start and end of the month is allowed to be -11
- Start: 2024-12-01T23:00:00Z, End: 2025-01-01T23:00:00Z
- Added a test to ensure the cased described is working as intended.
Reference: https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/internal-repo/1535
=> fix: Wholesale requests spanning a change in years

source/dotnet/wholesale-api/Edi.UnitTests/Validators/AggregatedTimeSeriesRequest/RequestedByActorRoleValidationRuleTest.cs, source/dotnet/wholesale-api/Edi.UnitTests/Validators/WholesaleServicesRequest/GridAreaValidatorTest.cs, source/dotnet/wholesale-api/Edi/Contracts/DataHubNames.cs, source/dotnet/wholesale-api/Edi/Validation/AggregatedTimeSeriesRequest/Rules/RequestedByActorRoleValidationRule.cs, source/dotnet/wholesale-api/Edi/Validation/WholesaleServicesRequest/Rules/GridAreaValidationRule.cs, source/dotnet/wholesale-api/Orchestrations.IntegrationTests/Functions/WholesaleInboxTriggerTests.cs
This PR will update constants described in the `DataHubNames` in Wholesale to sync them with the ones in EDI.
Wholesale: https://github.com/Energinet-DataHub/opengeh-wholesale/blob/main/source/dotnet/wholesale-api/Edi/Contracts/DataHubNames.cs
EDI: https://github.com/Energinet-DataHub/opengeh-edi/blob/main/source/BuildingBlocks.Domain/DataHub/DataHubNames.cs
Reference:
=> fix: Reallign DataHubNames with EDI

source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/CalculationResults/Statements/WholesaleServicesQuerySnippetProvider.cs, source/dotnet/wholesale-api/CalculationResults/CalculationResults.IntegrationTests/Infrastructure/RequestCalculationResult/WholesaleServicesQueriesCsvTests.cs
This PR fix incident: INC0429484, where grid operator could get not taxes charges from SYO
Story => https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/internal-repo/1573
dev002 deployment => https://github.com/Energinet-DataHub/dh3-environments/actions/runs/13305380660
=> fix: where grid operator received not tax charges from syo

.github/workflows/ci-databricks.yml, .github/workflows/detect-changes.yml
ubuntu-20.04 is deprecated, brownouts will happen from March 1st
Ref: https://github.com/actions/runner-images/issues/11101
=> Use ubuntu-latest instead of deprecated ubuntu-20.04

.github/workflows/ci-databricks.yml
Ubuntu-22.04 will be deprecated with brownouts starting March 1st
Ref: https://github.com/actions/runner-images/issues/11101
=> Remove large runner reference

source/databricks/calculation_engine/contracts/data_products/wholesale_results/energy_per_brp_v1.py
Exchange is not included in energy_per_brp, so the documentation had an error.
=> doc: Remove 'exchange' from brp data product

source/dotnet/subsystem-tests/Features/Calculations/BalanceFixingCalculationJobScenario.cs, source/dotnet/subsystem-tests/Features/Calculations/Fixtures/CalculationJobScenarioConfiguration.cs, source/dotnet/subsystem-tests/Features/Calculations/Fixtures/CalculationJobScenarioFixture.cs, source/dotnet/subsystem-tests/Features/Calculations/States/CalculationJobScenarioState.cs, source/dotnet/subsystem-tests/Features/Calculations/WholesaleFixingCalculationJobScenario.cs
Tested in `dev_002`:
- First attempt (verify job started and completed): https://github.com/Energinet-DataHub/dh3-environments/actions/runs/13636347750
- Second attempt (+ verify telemetry and views/tables): https://github.com/Energinet-DataHub/dh3-environments/actions/runs/13636885871
- Third attempt (+ verify version): https://github.com/Energinet-DataHub/dh3-environments/actions/runs/13647737375
Part of: https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-mosaic/578
=> refac: Cleanup subsystem tests

source/databricks/calculation_engine/package/optimize_job/delta_optimization.py
Related: https://adb-1539466176548659.19.azuredatabricks.net/jobs/875821125385795/runs/355939263789729?o=1539466176548659
=> chore: logging settings does not take a tracer_name argument

source/geh_wholesale/src/geh_wholesale/databases/migrations_wholesale/repository.py, source/geh_wholesale/tests/databases/migrations_wholesale/repository/test_read_time_series_points.py
Migration time series points table and measurements gold are not equal.
To make them equal, the metering point type is removed from the measurements gold table.
Test added too.
=> bug: Removed metering point type from measurements gold table
